// Code generated by ent, DO NOT EDIT.

package appsetting

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the appsetting type in the database.
	Label = "app_setting"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldKey holds the string denoting the key field in the database.
	FieldKey = "key"
	// FieldAutoStart holds the string denoting the auto_start field in the database.
	FieldAutoStart = "auto_start"
	// FieldAutoRestart holds the string denoting the auto_restart field in the database.
	FieldAutoRestart = "auto_restart"
	// FieldCustomTag holds the string denoting the custom_tag field in the database.
	FieldCustomTag = "custom_tag"
	// FieldSoftwareName holds the string denoting the software_name field in the database.
	FieldSoftwareName = "software_name"
	// FieldProtocol holds the string denoting the protocol field in the database.
	FieldProtocol = "protocol"
	// FieldGracePeriod holds the string denoting the grace_period field in the database.
	FieldGracePeriod = "grace_period"
	// FieldRegion holds the string denoting the region field in the database.
	FieldRegion = "region"
	// FieldRetries holds the string denoting the retries field in the database.
	FieldRetries = "retries"
	// FieldMetricsEnable holds the string denoting the metrics_enable field in the database.
	FieldMetricsEnable = "metrics_enable"
	// FieldMetricsPort holds the string denoting the metrics_port field in the database.
	FieldMetricsPort = "metrics_port"
	// FieldLogLevel holds the string denoting the log_level field in the database.
	FieldLogLevel = "log_level"
	// FieldLogFile holds the string denoting the log_file field in the database.
	FieldLogFile = "log_file"
	// FieldLogJSON holds the string denoting the log_json field in the database.
	FieldLogJSON = "log_json"
	// FieldEdgeIPVersion holds the string denoting the edge_ip_version field in the database.
	FieldEdgeIPVersion = "edge_ip_version"
	// FieldEdgeBindAddress holds the string denoting the edge_bind_address field in the database.
	FieldEdgeBindAddress = "edge_bind_address"
	// FieldPostQuantum holds the string denoting the post_quantum field in the database.
	FieldPostQuantum = "post_quantum"
	// FieldNoTLSVerify holds the string denoting the no_tls_verify field in the database.
	FieldNoTLSVerify = "no_tls_verify"
	// FieldExtraArgs holds the string denoting the extra_args field in the database.
	FieldExtraArgs = "extra_args"
	// FieldMcpEnabled holds the string denoting the mcp_enabled field in the database.
	FieldMcpEnabled = "mcp_enabled"
	// FieldS3WebdavEnabled holds the string denoting the s3_webdav_enabled field in the database.
	FieldS3WebdavEnabled = "s3_webdav_enabled"
	// FieldS3WebdavActiveKey holds the string denoting the s3_webdav_active_key field in the database.
	FieldS3WebdavActiveKey = "s3_webdav_active_key"
	// FieldS3WebdavAccessMode holds the string denoting the s3_webdav_access_mode field in the database.
	FieldS3WebdavAccessMode = "s3_webdav_access_mode"
	// FieldS3WebdavDedicatedBindHost holds the string denoting the s3_webdav_dedicated_bind_host field in the database.
	FieldS3WebdavDedicatedBindHost = "s3_webdav_dedicated_bind_host"
	// FieldS3WebdavDedicatedPort holds the string denoting the s3_webdav_dedicated_port field in the database.
	FieldS3WebdavDedicatedPort = "s3_webdav_dedicated_port"
	// FieldS3WebdavDedicatedAutoStart holds the string denoting the s3_webdav_dedicated_auto_start field in the database.
	FieldS3WebdavDedicatedAutoStart = "s3_webdav_dedicated_auto_start"
	// FieldS3WebdavDedicatedDomainMode holds the string denoting the s3_webdav_dedicated_domain_mode field in the database.
	FieldS3WebdavDedicatedDomainMode = "s3_webdav_dedicated_domain_mode"
	// FieldS3WebdavDedicatedCustomDomain holds the string denoting the s3_webdav_dedicated_custom_domain field in the database.
	FieldS3WebdavDedicatedCustomDomain = "s3_webdav_dedicated_custom_domain"
	// FieldS3WebdavDedicatedTunnelHostname holds the string denoting the s3_webdav_dedicated_tunnel_hostname field in the database.
	FieldS3WebdavDedicatedTunnelHostname = "s3_webdav_dedicated_tunnel_hostname"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the appsetting in the database.
	Table = "app_settings"
)

// Columns holds all SQL columns for appsetting fields.
var Columns = []string{
	FieldID,
	FieldKey,
	FieldAutoStart,
	FieldAutoRestart,
	FieldCustomTag,
	FieldSoftwareName,
	FieldProtocol,
	FieldGracePeriod,
	FieldRegion,
	FieldRetries,
	FieldMetricsEnable,
	FieldMetricsPort,
	FieldLogLevel,
	FieldLogFile,
	FieldLogJSON,
	FieldEdgeIPVersion,
	FieldEdgeBindAddress,
	FieldPostQuantum,
	FieldNoTLSVerify,
	FieldExtraArgs,
	FieldMcpEnabled,
	FieldS3WebdavEnabled,
	FieldS3WebdavActiveKey,
	FieldS3WebdavAccessMode,
	FieldS3WebdavDedicatedBindHost,
	FieldS3WebdavDedicatedPort,
	FieldS3WebdavDedicatedAutoStart,
	FieldS3WebdavDedicatedDomainMode,
	FieldS3WebdavDedicatedCustomDomain,
	FieldS3WebdavDedicatedTunnelHostname,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// KeyValidator is a validator for the "key" field. It is called by the builders before save.
	KeyValidator func(string) error
	// DefaultAutoStart holds the default value on creation for the "auto_start" field.
	DefaultAutoStart bool
	// DefaultAutoRestart holds the default value on creation for the "auto_restart" field.
	DefaultAutoRestart bool
	// DefaultCustomTag holds the default value on creation for the "custom_tag" field.
	DefaultCustomTag string
	// DefaultSoftwareName holds the default value on creation for the "software_name" field.
	DefaultSoftwareName string
	// DefaultProtocol holds the default value on creation for the "protocol" field.
	DefaultProtocol string
	// DefaultGracePeriod holds the default value on creation for the "grace_period" field.
	DefaultGracePeriod string
	// DefaultRegion holds the default value on creation for the "region" field.
	DefaultRegion string
	// DefaultRetries holds the default value on creation for the "retries" field.
	DefaultRetries int
	// DefaultMetricsEnable holds the default value on creation for the "metrics_enable" field.
	DefaultMetricsEnable bool
	// DefaultMetricsPort holds the default value on creation for the "metrics_port" field.
	DefaultMetricsPort int
	// DefaultLogLevel holds the default value on creation for the "log_level" field.
	DefaultLogLevel string
	// DefaultLogFile holds the default value on creation for the "log_file" field.
	DefaultLogFile string
	// DefaultLogJSON holds the default value on creation for the "log_json" field.
	DefaultLogJSON bool
	// DefaultEdgeIPVersion holds the default value on creation for the "edge_ip_version" field.
	DefaultEdgeIPVersion string
	// DefaultEdgeBindAddress holds the default value on creation for the "edge_bind_address" field.
	DefaultEdgeBindAddress string
	// DefaultPostQuantum holds the default value on creation for the "post_quantum" field.
	DefaultPostQuantum bool
	// DefaultNoTLSVerify holds the default value on creation for the "no_tls_verify" field.
	DefaultNoTLSVerify bool
	// DefaultExtraArgs holds the default value on creation for the "extra_args" field.
	DefaultExtraArgs string
	// DefaultMcpEnabled holds the default value on creation for the "mcp_enabled" field.
	DefaultMcpEnabled bool
	// DefaultS3WebdavEnabled holds the default value on creation for the "s3_webdav_enabled" field.
	DefaultS3WebdavEnabled bool
	// DefaultS3WebdavActiveKey holds the default value on creation for the "s3_webdav_active_key" field.
	DefaultS3WebdavActiveKey string
	// DefaultS3WebdavAccessMode holds the default value on creation for the "s3_webdav_access_mode" field.
	DefaultS3WebdavAccessMode string
	// DefaultS3WebdavDedicatedBindHost holds the default value on creation for the "s3_webdav_dedicated_bind_host" field.
	DefaultS3WebdavDedicatedBindHost string
	// DefaultS3WebdavDedicatedPort holds the default value on creation for the "s3_webdav_dedicated_port" field.
	DefaultS3WebdavDedicatedPort int
	// DefaultS3WebdavDedicatedAutoStart holds the default value on creation for the "s3_webdav_dedicated_auto_start" field.
	DefaultS3WebdavDedicatedAutoStart bool
	// DefaultS3WebdavDedicatedDomainMode holds the default value on creation for the "s3_webdav_dedicated_domain_mode" field.
	DefaultS3WebdavDedicatedDomainMode string
	// DefaultS3WebdavDedicatedCustomDomain holds the default value on creation for the "s3_webdav_dedicated_custom_domain" field.
	DefaultS3WebdavDedicatedCustomDomain string
	// DefaultS3WebdavDedicatedTunnelHostname holds the default value on creation for the "s3_webdav_dedicated_tunnel_hostname" field.
	DefaultS3WebdavDedicatedTunnelHostname string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the AppSetting queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByKey orders the results by the key field.
func ByKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKey, opts...).ToFunc()
}

// ByAutoStart orders the results by the auto_start field.
func ByAutoStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAutoStart, opts...).ToFunc()
}

// ByAutoRestart orders the results by the auto_restart field.
func ByAutoRestart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAutoRestart, opts...).ToFunc()
}

// ByCustomTag orders the results by the custom_tag field.
func ByCustomTag(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomTag, opts...).ToFunc()
}

// BySoftwareName orders the results by the software_name field.
func BySoftwareName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSoftwareName, opts...).ToFunc()
}

// ByProtocol orders the results by the protocol field.
func ByProtocol(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProtocol, opts...).ToFunc()
}

// ByGracePeriod orders the results by the grace_period field.
func ByGracePeriod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGracePeriod, opts...).ToFunc()
}

// ByRegion orders the results by the region field.
func ByRegion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRegion, opts...).ToFunc()
}

// ByRetries orders the results by the retries field.
func ByRetries(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRetries, opts...).ToFunc()
}

// ByMetricsEnable orders the results by the metrics_enable field.
func ByMetricsEnable(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetricsEnable, opts...).ToFunc()
}

// ByMetricsPort orders the results by the metrics_port field.
func ByMetricsPort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetricsPort, opts...).ToFunc()
}

// ByLogLevel orders the results by the log_level field.
func ByLogLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLogLevel, opts...).ToFunc()
}

// ByLogFile orders the results by the log_file field.
func ByLogFile(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLogFile, opts...).ToFunc()
}

// ByLogJSON orders the results by the log_json field.
func ByLogJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLogJSON, opts...).ToFunc()
}

// ByEdgeIPVersion orders the results by the edge_ip_version field.
func ByEdgeIPVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEdgeIPVersion, opts...).ToFunc()
}

// ByEdgeBindAddress orders the results by the edge_bind_address field.
func ByEdgeBindAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEdgeBindAddress, opts...).ToFunc()
}

// ByPostQuantum orders the results by the post_quantum field.
func ByPostQuantum(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPostQuantum, opts...).ToFunc()
}

// ByNoTLSVerify orders the results by the no_tls_verify field.
func ByNoTLSVerify(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNoTLSVerify, opts...).ToFunc()
}

// ByExtraArgs orders the results by the extra_args field.
func ByExtraArgs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExtraArgs, opts...).ToFunc()
}

// ByMcpEnabled orders the results by the mcp_enabled field.
func ByMcpEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMcpEnabled, opts...).ToFunc()
}

// ByS3WebdavEnabled orders the results by the s3_webdav_enabled field.
func ByS3WebdavEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldS3WebdavEnabled, opts...).ToFunc()
}

// ByS3WebdavActiveKey orders the results by the s3_webdav_active_key field.
func ByS3WebdavActiveKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldS3WebdavActiveKey, opts...).ToFunc()
}

// ByS3WebdavAccessMode orders the results by the s3_webdav_access_mode field.
func ByS3WebdavAccessMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldS3WebdavAccessMode, opts...).ToFunc()
}

// ByS3WebdavDedicatedBindHost orders the results by the s3_webdav_dedicated_bind_host field.
func ByS3WebdavDedicatedBindHost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldS3WebdavDedicatedBindHost, opts...).ToFunc()
}

// ByS3WebdavDedicatedPort orders the results by the s3_webdav_dedicated_port field.
func ByS3WebdavDedicatedPort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldS3WebdavDedicatedPort, opts...).ToFunc()
}

// ByS3WebdavDedicatedAutoStart orders the results by the s3_webdav_dedicated_auto_start field.
func ByS3WebdavDedicatedAutoStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldS3WebdavDedicatedAutoStart, opts...).ToFunc()
}

// ByS3WebdavDedicatedDomainMode orders the results by the s3_webdav_dedicated_domain_mode field.
func ByS3WebdavDedicatedDomainMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldS3WebdavDedicatedDomainMode, opts...).ToFunc()
}

// ByS3WebdavDedicatedCustomDomain orders the results by the s3_webdav_dedicated_custom_domain field.
func ByS3WebdavDedicatedCustomDomain(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldS3WebdavDedicatedCustomDomain, opts...).ToFunc()
}

// ByS3WebdavDedicatedTunnelHostname orders the results by the s3_webdav_dedicated_tunnel_hostname field.
func ByS3WebdavDedicatedTunnelHostname(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldS3WebdavDedicatedTunnelHostname, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
