// Code generated by ent, DO NOT EDIT.

package appsetting

import (
	"cfui/internal/persist/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLTE(FieldID, id))
}

// Key applies equality check predicate on the "key" field. It's identical to KeyEQ.
func Key(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldKey, v))
}

// AutoStart applies equality check predicate on the "auto_start" field. It's identical to AutoStartEQ.
func AutoStart(v bool) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldAutoStart, v))
}

// AutoRestart applies equality check predicate on the "auto_restart" field. It's identical to AutoRestartEQ.
func AutoRestart(v bool) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldAutoRestart, v))
}

// CustomTag applies equality check predicate on the "custom_tag" field. It's identical to CustomTagEQ.
func CustomTag(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldCustomTag, v))
}

// SoftwareName applies equality check predicate on the "software_name" field. It's identical to SoftwareNameEQ.
func SoftwareName(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldSoftwareName, v))
}

// Protocol applies equality check predicate on the "protocol" field. It's identical to ProtocolEQ.
func Protocol(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldProtocol, v))
}

// GracePeriod applies equality check predicate on the "grace_period" field. It's identical to GracePeriodEQ.
func GracePeriod(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldGracePeriod, v))
}

// Region applies equality check predicate on the "region" field. It's identical to RegionEQ.
func Region(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldRegion, v))
}

// Retries applies equality check predicate on the "retries" field. It's identical to RetriesEQ.
func Retries(v int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldRetries, v))
}

// MetricsEnable applies equality check predicate on the "metrics_enable" field. It's identical to MetricsEnableEQ.
func MetricsEnable(v bool) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldMetricsEnable, v))
}

// MetricsPort applies equality check predicate on the "metrics_port" field. It's identical to MetricsPortEQ.
func MetricsPort(v int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldMetricsPort, v))
}

// LogLevel applies equality check predicate on the "log_level" field. It's identical to LogLevelEQ.
func LogLevel(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldLogLevel, v))
}

// LogFile applies equality check predicate on the "log_file" field. It's identical to LogFileEQ.
func LogFile(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldLogFile, v))
}

// LogJSON applies equality check predicate on the "log_json" field. It's identical to LogJSONEQ.
func LogJSON(v bool) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldLogJSON, v))
}

// EdgeIPVersion applies equality check predicate on the "edge_ip_version" field. It's identical to EdgeIPVersionEQ.
func EdgeIPVersion(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldEdgeIPVersion, v))
}

// EdgeBindAddress applies equality check predicate on the "edge_bind_address" field. It's identical to EdgeBindAddressEQ.
func EdgeBindAddress(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldEdgeBindAddress, v))
}

// PostQuantum applies equality check predicate on the "post_quantum" field. It's identical to PostQuantumEQ.
func PostQuantum(v bool) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldPostQuantum, v))
}

// NoTLSVerify applies equality check predicate on the "no_tls_verify" field. It's identical to NoTLSVerifyEQ.
func NoTLSVerify(v bool) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldNoTLSVerify, v))
}

// ExtraArgs applies equality check predicate on the "extra_args" field. It's identical to ExtraArgsEQ.
func ExtraArgs(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldExtraArgs, v))
}

// McpEnabled applies equality check predicate on the "mcp_enabled" field. It's identical to McpEnabledEQ.
func McpEnabled(v bool) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldMcpEnabled, v))
}

// S3WebdavEnabled applies equality check predicate on the "s3_webdav_enabled" field. It's identical to S3WebdavEnabledEQ.
func S3WebdavEnabled(v bool) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldS3WebdavEnabled, v))
}

// S3WebdavActiveKey applies equality check predicate on the "s3_webdav_active_key" field. It's identical to S3WebdavActiveKeyEQ.
func S3WebdavActiveKey(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldS3WebdavActiveKey, v))
}

// S3WebdavAccessMode applies equality check predicate on the "s3_webdav_access_mode" field. It's identical to S3WebdavAccessModeEQ.
func S3WebdavAccessMode(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldS3WebdavAccessMode, v))
}

// S3WebdavDedicatedBindHost applies equality check predicate on the "s3_webdav_dedicated_bind_host" field. It's identical to S3WebdavDedicatedBindHostEQ.
func S3WebdavDedicatedBindHost(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldS3WebdavDedicatedBindHost, v))
}

// S3WebdavDedicatedPort applies equality check predicate on the "s3_webdav_dedicated_port" field. It's identical to S3WebdavDedicatedPortEQ.
func S3WebdavDedicatedPort(v int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldS3WebdavDedicatedPort, v))
}

// S3WebdavDedicatedAutoStart applies equality check predicate on the "s3_webdav_dedicated_auto_start" field. It's identical to S3WebdavDedicatedAutoStartEQ.
func S3WebdavDedicatedAutoStart(v bool) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldS3WebdavDedicatedAutoStart, v))
}

// S3WebdavDedicatedDomainMode applies equality check predicate on the "s3_webdav_dedicated_domain_mode" field. It's identical to S3WebdavDedicatedDomainModeEQ.
func S3WebdavDedicatedDomainMode(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldS3WebdavDedicatedDomainMode, v))
}

// S3WebdavDedicatedCustomDomain applies equality check predicate on the "s3_webdav_dedicated_custom_domain" field. It's identical to S3WebdavDedicatedCustomDomainEQ.
func S3WebdavDedicatedCustomDomain(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldS3WebdavDedicatedCustomDomain, v))
}

// S3WebdavDedicatedTunnelHostname applies equality check predicate on the "s3_webdav_dedicated_tunnel_hostname" field. It's identical to S3WebdavDedicatedTunnelHostnameEQ.
func S3WebdavDedicatedTunnelHostname(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldS3WebdavDedicatedTunnelHostname, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldUpdatedAt, v))
}

// KeyEQ applies the EQ predicate on the "key" field.
func KeyEQ(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldKey, v))
}

// KeyNEQ applies the NEQ predicate on the "key" field.
func KeyNEQ(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNEQ(FieldKey, v))
}

// KeyIn applies the In predicate on the "key" field.
func KeyIn(vs ...string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldIn(FieldKey, vs...))
}

// KeyNotIn applies the NotIn predicate on the "key" field.
func KeyNotIn(vs ...string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNotIn(FieldKey, vs...))
}

// KeyGT applies the GT predicate on the "key" field.
func KeyGT(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGT(FieldKey, v))
}

// KeyGTE applies the GTE predicate on the "key" field.
func KeyGTE(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGTE(FieldKey, v))
}

// KeyLT applies the LT predicate on the "key" field.
func KeyLT(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLT(FieldKey, v))
}

// KeyLTE applies the LTE predicate on the "key" field.
func KeyLTE(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLTE(FieldKey, v))
}

// KeyContains applies the Contains predicate on the "key" field.
func KeyContains(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldContains(FieldKey, v))
}

// KeyHasPrefix applies the HasPrefix predicate on the "key" field.
func KeyHasPrefix(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldHasPrefix(FieldKey, v))
}

// KeyHasSuffix applies the HasSuffix predicate on the "key" field.
func KeyHasSuffix(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldHasSuffix(FieldKey, v))
}

// KeyEqualFold applies the EqualFold predicate on the "key" field.
func KeyEqualFold(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEqualFold(FieldKey, v))
}

// KeyContainsFold applies the ContainsFold predicate on the "key" field.
func KeyContainsFold(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldContainsFold(FieldKey, v))
}

// AutoStartEQ applies the EQ predicate on the "auto_start" field.
func AutoStartEQ(v bool) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldAutoStart, v))
}

// AutoStartNEQ applies the NEQ predicate on the "auto_start" field.
func AutoStartNEQ(v bool) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNEQ(FieldAutoStart, v))
}

// AutoRestartEQ applies the EQ predicate on the "auto_restart" field.
func AutoRestartEQ(v bool) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldAutoRestart, v))
}

// AutoRestartNEQ applies the NEQ predicate on the "auto_restart" field.
func AutoRestartNEQ(v bool) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNEQ(FieldAutoRestart, v))
}

// CustomTagEQ applies the EQ predicate on the "custom_tag" field.
func CustomTagEQ(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldCustomTag, v))
}

// CustomTagNEQ applies the NEQ predicate on the "custom_tag" field.
func CustomTagNEQ(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNEQ(FieldCustomTag, v))
}

// CustomTagIn applies the In predicate on the "custom_tag" field.
func CustomTagIn(vs ...string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldIn(FieldCustomTag, vs...))
}

// CustomTagNotIn applies the NotIn predicate on the "custom_tag" field.
func CustomTagNotIn(vs ...string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNotIn(FieldCustomTag, vs...))
}

// CustomTagGT applies the GT predicate on the "custom_tag" field.
func CustomTagGT(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGT(FieldCustomTag, v))
}

// CustomTagGTE applies the GTE predicate on the "custom_tag" field.
func CustomTagGTE(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGTE(FieldCustomTag, v))
}

// CustomTagLT applies the LT predicate on the "custom_tag" field.
func CustomTagLT(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLT(FieldCustomTag, v))
}

// CustomTagLTE applies the LTE predicate on the "custom_tag" field.
func CustomTagLTE(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLTE(FieldCustomTag, v))
}

// CustomTagContains applies the Contains predicate on the "custom_tag" field.
func CustomTagContains(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldContains(FieldCustomTag, v))
}

// CustomTagHasPrefix applies the HasPrefix predicate on the "custom_tag" field.
func CustomTagHasPrefix(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldHasPrefix(FieldCustomTag, v))
}

// CustomTagHasSuffix applies the HasSuffix predicate on the "custom_tag" field.
func CustomTagHasSuffix(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldHasSuffix(FieldCustomTag, v))
}

// CustomTagEqualFold applies the EqualFold predicate on the "custom_tag" field.
func CustomTagEqualFold(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEqualFold(FieldCustomTag, v))
}

// CustomTagContainsFold applies the ContainsFold predicate on the "custom_tag" field.
func CustomTagContainsFold(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldContainsFold(FieldCustomTag, v))
}

// SoftwareNameEQ applies the EQ predicate on the "software_name" field.
func SoftwareNameEQ(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldSoftwareName, v))
}

// SoftwareNameNEQ applies the NEQ predicate on the "software_name" field.
func SoftwareNameNEQ(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNEQ(FieldSoftwareName, v))
}

// SoftwareNameIn applies the In predicate on the "software_name" field.
func SoftwareNameIn(vs ...string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldIn(FieldSoftwareName, vs...))
}

// SoftwareNameNotIn applies the NotIn predicate on the "software_name" field.
func SoftwareNameNotIn(vs ...string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNotIn(FieldSoftwareName, vs...))
}

// SoftwareNameGT applies the GT predicate on the "software_name" field.
func SoftwareNameGT(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGT(FieldSoftwareName, v))
}

// SoftwareNameGTE applies the GTE predicate on the "software_name" field.
func SoftwareNameGTE(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGTE(FieldSoftwareName, v))
}

// SoftwareNameLT applies the LT predicate on the "software_name" field.
func SoftwareNameLT(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLT(FieldSoftwareName, v))
}

// SoftwareNameLTE applies the LTE predicate on the "software_name" field.
func SoftwareNameLTE(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLTE(FieldSoftwareName, v))
}

// SoftwareNameContains applies the Contains predicate on the "software_name" field.
func SoftwareNameContains(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldContains(FieldSoftwareName, v))
}

// SoftwareNameHasPrefix applies the HasPrefix predicate on the "software_name" field.
func SoftwareNameHasPrefix(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldHasPrefix(FieldSoftwareName, v))
}

// SoftwareNameHasSuffix applies the HasSuffix predicate on the "software_name" field.
func SoftwareNameHasSuffix(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldHasSuffix(FieldSoftwareName, v))
}

// SoftwareNameEqualFold applies the EqualFold predicate on the "software_name" field.
func SoftwareNameEqualFold(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEqualFold(FieldSoftwareName, v))
}

// SoftwareNameContainsFold applies the ContainsFold predicate on the "software_name" field.
func SoftwareNameContainsFold(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldContainsFold(FieldSoftwareName, v))
}

// ProtocolEQ applies the EQ predicate on the "protocol" field.
func ProtocolEQ(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldProtocol, v))
}

// ProtocolNEQ applies the NEQ predicate on the "protocol" field.
func ProtocolNEQ(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNEQ(FieldProtocol, v))
}

// ProtocolIn applies the In predicate on the "protocol" field.
func ProtocolIn(vs ...string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldIn(FieldProtocol, vs...))
}

// ProtocolNotIn applies the NotIn predicate on the "protocol" field.
func ProtocolNotIn(vs ...string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNotIn(FieldProtocol, vs...))
}

// ProtocolGT applies the GT predicate on the "protocol" field.
func ProtocolGT(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGT(FieldProtocol, v))
}

// ProtocolGTE applies the GTE predicate on the "protocol" field.
func ProtocolGTE(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGTE(FieldProtocol, v))
}

// ProtocolLT applies the LT predicate on the "protocol" field.
func ProtocolLT(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLT(FieldProtocol, v))
}

// ProtocolLTE applies the LTE predicate on the "protocol" field.
func ProtocolLTE(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLTE(FieldProtocol, v))
}

// ProtocolContains applies the Contains predicate on the "protocol" field.
func ProtocolContains(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldContains(FieldProtocol, v))
}

// ProtocolHasPrefix applies the HasPrefix predicate on the "protocol" field.
func ProtocolHasPrefix(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldHasPrefix(FieldProtocol, v))
}

// ProtocolHasSuffix applies the HasSuffix predicate on the "protocol" field.
func ProtocolHasSuffix(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldHasSuffix(FieldProtocol, v))
}

// ProtocolEqualFold applies the EqualFold predicate on the "protocol" field.
func ProtocolEqualFold(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEqualFold(FieldProtocol, v))
}

// ProtocolContainsFold applies the ContainsFold predicate on the "protocol" field.
func ProtocolContainsFold(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldContainsFold(FieldProtocol, v))
}

// GracePeriodEQ applies the EQ predicate on the "grace_period" field.
func GracePeriodEQ(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldGracePeriod, v))
}

// GracePeriodNEQ applies the NEQ predicate on the "grace_period" field.
func GracePeriodNEQ(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNEQ(FieldGracePeriod, v))
}

// GracePeriodIn applies the In predicate on the "grace_period" field.
func GracePeriodIn(vs ...string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldIn(FieldGracePeriod, vs...))
}

// GracePeriodNotIn applies the NotIn predicate on the "grace_period" field.
func GracePeriodNotIn(vs ...string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNotIn(FieldGracePeriod, vs...))
}

// GracePeriodGT applies the GT predicate on the "grace_period" field.
func GracePeriodGT(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGT(FieldGracePeriod, v))
}

// GracePeriodGTE applies the GTE predicate on the "grace_period" field.
func GracePeriodGTE(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGTE(FieldGracePeriod, v))
}

// GracePeriodLT applies the LT predicate on the "grace_period" field.
func GracePeriodLT(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLT(FieldGracePeriod, v))
}

// GracePeriodLTE applies the LTE predicate on the "grace_period" field.
func GracePeriodLTE(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLTE(FieldGracePeriod, v))
}

// GracePeriodContains applies the Contains predicate on the "grace_period" field.
func GracePeriodContains(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldContains(FieldGracePeriod, v))
}

// GracePeriodHasPrefix applies the HasPrefix predicate on the "grace_period" field.
func GracePeriodHasPrefix(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldHasPrefix(FieldGracePeriod, v))
}

// GracePeriodHasSuffix applies the HasSuffix predicate on the "grace_period" field.
func GracePeriodHasSuffix(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldHasSuffix(FieldGracePeriod, v))
}

// GracePeriodEqualFold applies the EqualFold predicate on the "grace_period" field.
func GracePeriodEqualFold(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEqualFold(FieldGracePeriod, v))
}

// GracePeriodContainsFold applies the ContainsFold predicate on the "grace_period" field.
func GracePeriodContainsFold(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldContainsFold(FieldGracePeriod, v))
}

// RegionEQ applies the EQ predicate on the "region" field.
func RegionEQ(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldRegion, v))
}

// RegionNEQ applies the NEQ predicate on the "region" field.
func RegionNEQ(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNEQ(FieldRegion, v))
}

// RegionIn applies the In predicate on the "region" field.
func RegionIn(vs ...string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldIn(FieldRegion, vs...))
}

// RegionNotIn applies the NotIn predicate on the "region" field.
func RegionNotIn(vs ...string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNotIn(FieldRegion, vs...))
}

// RegionGT applies the GT predicate on the "region" field.
func RegionGT(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGT(FieldRegion, v))
}

// RegionGTE applies the GTE predicate on the "region" field.
func RegionGTE(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGTE(FieldRegion, v))
}

// RegionLT applies the LT predicate on the "region" field.
func RegionLT(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLT(FieldRegion, v))
}

// RegionLTE applies the LTE predicate on the "region" field.
func RegionLTE(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLTE(FieldRegion, v))
}

// RegionContains applies the Contains predicate on the "region" field.
func RegionContains(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldContains(FieldRegion, v))
}

// RegionHasPrefix applies the HasPrefix predicate on the "region" field.
func RegionHasPrefix(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldHasPrefix(FieldRegion, v))
}

// RegionHasSuffix applies the HasSuffix predicate on the "region" field.
func RegionHasSuffix(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldHasSuffix(FieldRegion, v))
}

// RegionEqualFold applies the EqualFold predicate on the "region" field.
func RegionEqualFold(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEqualFold(FieldRegion, v))
}

// RegionContainsFold applies the ContainsFold predicate on the "region" field.
func RegionContainsFold(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldContainsFold(FieldRegion, v))
}

// RetriesEQ applies the EQ predicate on the "retries" field.
func RetriesEQ(v int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldRetries, v))
}

// RetriesNEQ applies the NEQ predicate on the "retries" field.
func RetriesNEQ(v int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNEQ(FieldRetries, v))
}

// RetriesIn applies the In predicate on the "retries" field.
func RetriesIn(vs ...int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldIn(FieldRetries, vs...))
}

// RetriesNotIn applies the NotIn predicate on the "retries" field.
func RetriesNotIn(vs ...int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNotIn(FieldRetries, vs...))
}

// RetriesGT applies the GT predicate on the "retries" field.
func RetriesGT(v int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGT(FieldRetries, v))
}

// RetriesGTE applies the GTE predicate on the "retries" field.
func RetriesGTE(v int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGTE(FieldRetries, v))
}

// RetriesLT applies the LT predicate on the "retries" field.
func RetriesLT(v int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLT(FieldRetries, v))
}

// RetriesLTE applies the LTE predicate on the "retries" field.
func RetriesLTE(v int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLTE(FieldRetries, v))
}

// MetricsEnableEQ applies the EQ predicate on the "metrics_enable" field.
func MetricsEnableEQ(v bool) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldMetricsEnable, v))
}

// MetricsEnableNEQ applies the NEQ predicate on the "metrics_enable" field.
func MetricsEnableNEQ(v bool) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNEQ(FieldMetricsEnable, v))
}

// MetricsPortEQ applies the EQ predicate on the "metrics_port" field.
func MetricsPortEQ(v int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldMetricsPort, v))
}

// MetricsPortNEQ applies the NEQ predicate on the "metrics_port" field.
func MetricsPortNEQ(v int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNEQ(FieldMetricsPort, v))
}

// MetricsPortIn applies the In predicate on the "metrics_port" field.
func MetricsPortIn(vs ...int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldIn(FieldMetricsPort, vs...))
}

// MetricsPortNotIn applies the NotIn predicate on the "metrics_port" field.
func MetricsPortNotIn(vs ...int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNotIn(FieldMetricsPort, vs...))
}

// MetricsPortGT applies the GT predicate on the "metrics_port" field.
func MetricsPortGT(v int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGT(FieldMetricsPort, v))
}

// MetricsPortGTE applies the GTE predicate on the "metrics_port" field.
func MetricsPortGTE(v int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGTE(FieldMetricsPort, v))
}

// MetricsPortLT applies the LT predicate on the "metrics_port" field.
func MetricsPortLT(v int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLT(FieldMetricsPort, v))
}

// MetricsPortLTE applies the LTE predicate on the "metrics_port" field.
func MetricsPortLTE(v int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLTE(FieldMetricsPort, v))
}

// LogLevelEQ applies the EQ predicate on the "log_level" field.
func LogLevelEQ(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldLogLevel, v))
}

// LogLevelNEQ applies the NEQ predicate on the "log_level" field.
func LogLevelNEQ(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNEQ(FieldLogLevel, v))
}

// LogLevelIn applies the In predicate on the "log_level" field.
func LogLevelIn(vs ...string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldIn(FieldLogLevel, vs...))
}

// LogLevelNotIn applies the NotIn predicate on the "log_level" field.
func LogLevelNotIn(vs ...string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNotIn(FieldLogLevel, vs...))
}

// LogLevelGT applies the GT predicate on the "log_level" field.
func LogLevelGT(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGT(FieldLogLevel, v))
}

// LogLevelGTE applies the GTE predicate on the "log_level" field.
func LogLevelGTE(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGTE(FieldLogLevel, v))
}

// LogLevelLT applies the LT predicate on the "log_level" field.
func LogLevelLT(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLT(FieldLogLevel, v))
}

// LogLevelLTE applies the LTE predicate on the "log_level" field.
func LogLevelLTE(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLTE(FieldLogLevel, v))
}

// LogLevelContains applies the Contains predicate on the "log_level" field.
func LogLevelContains(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldContains(FieldLogLevel, v))
}

// LogLevelHasPrefix applies the HasPrefix predicate on the "log_level" field.
func LogLevelHasPrefix(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldHasPrefix(FieldLogLevel, v))
}

// LogLevelHasSuffix applies the HasSuffix predicate on the "log_level" field.
func LogLevelHasSuffix(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldHasSuffix(FieldLogLevel, v))
}

// LogLevelEqualFold applies the EqualFold predicate on the "log_level" field.
func LogLevelEqualFold(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEqualFold(FieldLogLevel, v))
}

// LogLevelContainsFold applies the ContainsFold predicate on the "log_level" field.
func LogLevelContainsFold(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldContainsFold(FieldLogLevel, v))
}

// LogFileEQ applies the EQ predicate on the "log_file" field.
func LogFileEQ(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldLogFile, v))
}

// LogFileNEQ applies the NEQ predicate on the "log_file" field.
func LogFileNEQ(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNEQ(FieldLogFile, v))
}

// LogFileIn applies the In predicate on the "log_file" field.
func LogFileIn(vs ...string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldIn(FieldLogFile, vs...))
}

// LogFileNotIn applies the NotIn predicate on the "log_file" field.
func LogFileNotIn(vs ...string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNotIn(FieldLogFile, vs...))
}

// LogFileGT applies the GT predicate on the "log_file" field.
func LogFileGT(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGT(FieldLogFile, v))
}

// LogFileGTE applies the GTE predicate on the "log_file" field.
func LogFileGTE(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGTE(FieldLogFile, v))
}

// LogFileLT applies the LT predicate on the "log_file" field.
func LogFileLT(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLT(FieldLogFile, v))
}

// LogFileLTE applies the LTE predicate on the "log_file" field.
func LogFileLTE(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLTE(FieldLogFile, v))
}

// LogFileContains applies the Contains predicate on the "log_file" field.
func LogFileContains(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldContains(FieldLogFile, v))
}

// LogFileHasPrefix applies the HasPrefix predicate on the "log_file" field.
func LogFileHasPrefix(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldHasPrefix(FieldLogFile, v))
}

// LogFileHasSuffix applies the HasSuffix predicate on the "log_file" field.
func LogFileHasSuffix(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldHasSuffix(FieldLogFile, v))
}

// LogFileEqualFold applies the EqualFold predicate on the "log_file" field.
func LogFileEqualFold(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEqualFold(FieldLogFile, v))
}

// LogFileContainsFold applies the ContainsFold predicate on the "log_file" field.
func LogFileContainsFold(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldContainsFold(FieldLogFile, v))
}

// LogJSONEQ applies the EQ predicate on the "log_json" field.
func LogJSONEQ(v bool) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldLogJSON, v))
}

// LogJSONNEQ applies the NEQ predicate on the "log_json" field.
func LogJSONNEQ(v bool) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNEQ(FieldLogJSON, v))
}

// EdgeIPVersionEQ applies the EQ predicate on the "edge_ip_version" field.
func EdgeIPVersionEQ(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldEdgeIPVersion, v))
}

// EdgeIPVersionNEQ applies the NEQ predicate on the "edge_ip_version" field.
func EdgeIPVersionNEQ(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNEQ(FieldEdgeIPVersion, v))
}

// EdgeIPVersionIn applies the In predicate on the "edge_ip_version" field.
func EdgeIPVersionIn(vs ...string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldIn(FieldEdgeIPVersion, vs...))
}

// EdgeIPVersionNotIn applies the NotIn predicate on the "edge_ip_version" field.
func EdgeIPVersionNotIn(vs ...string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNotIn(FieldEdgeIPVersion, vs...))
}

// EdgeIPVersionGT applies the GT predicate on the "edge_ip_version" field.
func EdgeIPVersionGT(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGT(FieldEdgeIPVersion, v))
}

// EdgeIPVersionGTE applies the GTE predicate on the "edge_ip_version" field.
func EdgeIPVersionGTE(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGTE(FieldEdgeIPVersion, v))
}

// EdgeIPVersionLT applies the LT predicate on the "edge_ip_version" field.
func EdgeIPVersionLT(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLT(FieldEdgeIPVersion, v))
}

// EdgeIPVersionLTE applies the LTE predicate on the "edge_ip_version" field.
func EdgeIPVersionLTE(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLTE(FieldEdgeIPVersion, v))
}

// EdgeIPVersionContains applies the Contains predicate on the "edge_ip_version" field.
func EdgeIPVersionContains(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldContains(FieldEdgeIPVersion, v))
}

// EdgeIPVersionHasPrefix applies the HasPrefix predicate on the "edge_ip_version" field.
func EdgeIPVersionHasPrefix(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldHasPrefix(FieldEdgeIPVersion, v))
}

// EdgeIPVersionHasSuffix applies the HasSuffix predicate on the "edge_ip_version" field.
func EdgeIPVersionHasSuffix(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldHasSuffix(FieldEdgeIPVersion, v))
}

// EdgeIPVersionEqualFold applies the EqualFold predicate on the "edge_ip_version" field.
func EdgeIPVersionEqualFold(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEqualFold(FieldEdgeIPVersion, v))
}

// EdgeIPVersionContainsFold applies the ContainsFold predicate on the "edge_ip_version" field.
func EdgeIPVersionContainsFold(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldContainsFold(FieldEdgeIPVersion, v))
}

// EdgeBindAddressEQ applies the EQ predicate on the "edge_bind_address" field.
func EdgeBindAddressEQ(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldEdgeBindAddress, v))
}

// EdgeBindAddressNEQ applies the NEQ predicate on the "edge_bind_address" field.
func EdgeBindAddressNEQ(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNEQ(FieldEdgeBindAddress, v))
}

// EdgeBindAddressIn applies the In predicate on the "edge_bind_address" field.
func EdgeBindAddressIn(vs ...string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldIn(FieldEdgeBindAddress, vs...))
}

// EdgeBindAddressNotIn applies the NotIn predicate on the "edge_bind_address" field.
func EdgeBindAddressNotIn(vs ...string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNotIn(FieldEdgeBindAddress, vs...))
}

// EdgeBindAddressGT applies the GT predicate on the "edge_bind_address" field.
func EdgeBindAddressGT(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGT(FieldEdgeBindAddress, v))
}

// EdgeBindAddressGTE applies the GTE predicate on the "edge_bind_address" field.
func EdgeBindAddressGTE(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGTE(FieldEdgeBindAddress, v))
}

// EdgeBindAddressLT applies the LT predicate on the "edge_bind_address" field.
func EdgeBindAddressLT(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLT(FieldEdgeBindAddress, v))
}

// EdgeBindAddressLTE applies the LTE predicate on the "edge_bind_address" field.
func EdgeBindAddressLTE(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLTE(FieldEdgeBindAddress, v))
}

// EdgeBindAddressContains applies the Contains predicate on the "edge_bind_address" field.
func EdgeBindAddressContains(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldContains(FieldEdgeBindAddress, v))
}

// EdgeBindAddressHasPrefix applies the HasPrefix predicate on the "edge_bind_address" field.
func EdgeBindAddressHasPrefix(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldHasPrefix(FieldEdgeBindAddress, v))
}

// EdgeBindAddressHasSuffix applies the HasSuffix predicate on the "edge_bind_address" field.
func EdgeBindAddressHasSuffix(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldHasSuffix(FieldEdgeBindAddress, v))
}

// EdgeBindAddressEqualFold applies the EqualFold predicate on the "edge_bind_address" field.
func EdgeBindAddressEqualFold(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEqualFold(FieldEdgeBindAddress, v))
}

// EdgeBindAddressContainsFold applies the ContainsFold predicate on the "edge_bind_address" field.
func EdgeBindAddressContainsFold(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldContainsFold(FieldEdgeBindAddress, v))
}

// PostQuantumEQ applies the EQ predicate on the "post_quantum" field.
func PostQuantumEQ(v bool) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldPostQuantum, v))
}

// PostQuantumNEQ applies the NEQ predicate on the "post_quantum" field.
func PostQuantumNEQ(v bool) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNEQ(FieldPostQuantum, v))
}

// NoTLSVerifyEQ applies the EQ predicate on the "no_tls_verify" field.
func NoTLSVerifyEQ(v bool) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldNoTLSVerify, v))
}

// NoTLSVerifyNEQ applies the NEQ predicate on the "no_tls_verify" field.
func NoTLSVerifyNEQ(v bool) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNEQ(FieldNoTLSVerify, v))
}

// ExtraArgsEQ applies the EQ predicate on the "extra_args" field.
func ExtraArgsEQ(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldExtraArgs, v))
}

// ExtraArgsNEQ applies the NEQ predicate on the "extra_args" field.
func ExtraArgsNEQ(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNEQ(FieldExtraArgs, v))
}

// ExtraArgsIn applies the In predicate on the "extra_args" field.
func ExtraArgsIn(vs ...string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldIn(FieldExtraArgs, vs...))
}

// ExtraArgsNotIn applies the NotIn predicate on the "extra_args" field.
func ExtraArgsNotIn(vs ...string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNotIn(FieldExtraArgs, vs...))
}

// ExtraArgsGT applies the GT predicate on the "extra_args" field.
func ExtraArgsGT(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGT(FieldExtraArgs, v))
}

// ExtraArgsGTE applies the GTE predicate on the "extra_args" field.
func ExtraArgsGTE(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGTE(FieldExtraArgs, v))
}

// ExtraArgsLT applies the LT predicate on the "extra_args" field.
func ExtraArgsLT(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLT(FieldExtraArgs, v))
}

// ExtraArgsLTE applies the LTE predicate on the "extra_args" field.
func ExtraArgsLTE(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLTE(FieldExtraArgs, v))
}

// ExtraArgsContains applies the Contains predicate on the "extra_args" field.
func ExtraArgsContains(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldContains(FieldExtraArgs, v))
}

// ExtraArgsHasPrefix applies the HasPrefix predicate on the "extra_args" field.
func ExtraArgsHasPrefix(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldHasPrefix(FieldExtraArgs, v))
}

// ExtraArgsHasSuffix applies the HasSuffix predicate on the "extra_args" field.
func ExtraArgsHasSuffix(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldHasSuffix(FieldExtraArgs, v))
}

// ExtraArgsEqualFold applies the EqualFold predicate on the "extra_args" field.
func ExtraArgsEqualFold(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEqualFold(FieldExtraArgs, v))
}

// ExtraArgsContainsFold applies the ContainsFold predicate on the "extra_args" field.
func ExtraArgsContainsFold(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldContainsFold(FieldExtraArgs, v))
}

// McpEnabledEQ applies the EQ predicate on the "mcp_enabled" field.
func McpEnabledEQ(v bool) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldMcpEnabled, v))
}

// McpEnabledNEQ applies the NEQ predicate on the "mcp_enabled" field.
func McpEnabledNEQ(v bool) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNEQ(FieldMcpEnabled, v))
}

// S3WebdavEnabledEQ applies the EQ predicate on the "s3_webdav_enabled" field.
func S3WebdavEnabledEQ(v bool) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldS3WebdavEnabled, v))
}

// S3WebdavEnabledNEQ applies the NEQ predicate on the "s3_webdav_enabled" field.
func S3WebdavEnabledNEQ(v bool) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNEQ(FieldS3WebdavEnabled, v))
}

// S3WebdavActiveKeyEQ applies the EQ predicate on the "s3_webdav_active_key" field.
func S3WebdavActiveKeyEQ(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldS3WebdavActiveKey, v))
}

// S3WebdavActiveKeyNEQ applies the NEQ predicate on the "s3_webdav_active_key" field.
func S3WebdavActiveKeyNEQ(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNEQ(FieldS3WebdavActiveKey, v))
}

// S3WebdavActiveKeyIn applies the In predicate on the "s3_webdav_active_key" field.
func S3WebdavActiveKeyIn(vs ...string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldIn(FieldS3WebdavActiveKey, vs...))
}

// S3WebdavActiveKeyNotIn applies the NotIn predicate on the "s3_webdav_active_key" field.
func S3WebdavActiveKeyNotIn(vs ...string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNotIn(FieldS3WebdavActiveKey, vs...))
}

// S3WebdavActiveKeyGT applies the GT predicate on the "s3_webdav_active_key" field.
func S3WebdavActiveKeyGT(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGT(FieldS3WebdavActiveKey, v))
}

// S3WebdavActiveKeyGTE applies the GTE predicate on the "s3_webdav_active_key" field.
func S3WebdavActiveKeyGTE(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGTE(FieldS3WebdavActiveKey, v))
}

// S3WebdavActiveKeyLT applies the LT predicate on the "s3_webdav_active_key" field.
func S3WebdavActiveKeyLT(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLT(FieldS3WebdavActiveKey, v))
}

// S3WebdavActiveKeyLTE applies the LTE predicate on the "s3_webdav_active_key" field.
func S3WebdavActiveKeyLTE(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLTE(FieldS3WebdavActiveKey, v))
}

// S3WebdavActiveKeyContains applies the Contains predicate on the "s3_webdav_active_key" field.
func S3WebdavActiveKeyContains(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldContains(FieldS3WebdavActiveKey, v))
}

// S3WebdavActiveKeyHasPrefix applies the HasPrefix predicate on the "s3_webdav_active_key" field.
func S3WebdavActiveKeyHasPrefix(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldHasPrefix(FieldS3WebdavActiveKey, v))
}

// S3WebdavActiveKeyHasSuffix applies the HasSuffix predicate on the "s3_webdav_active_key" field.
func S3WebdavActiveKeyHasSuffix(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldHasSuffix(FieldS3WebdavActiveKey, v))
}

// S3WebdavActiveKeyEqualFold applies the EqualFold predicate on the "s3_webdav_active_key" field.
func S3WebdavActiveKeyEqualFold(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEqualFold(FieldS3WebdavActiveKey, v))
}

// S3WebdavActiveKeyContainsFold applies the ContainsFold predicate on the "s3_webdav_active_key" field.
func S3WebdavActiveKeyContainsFold(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldContainsFold(FieldS3WebdavActiveKey, v))
}

// S3WebdavAccessModeEQ applies the EQ predicate on the "s3_webdav_access_mode" field.
func S3WebdavAccessModeEQ(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldS3WebdavAccessMode, v))
}

// S3WebdavAccessModeNEQ applies the NEQ predicate on the "s3_webdav_access_mode" field.
func S3WebdavAccessModeNEQ(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNEQ(FieldS3WebdavAccessMode, v))
}

// S3WebdavAccessModeIn applies the In predicate on the "s3_webdav_access_mode" field.
func S3WebdavAccessModeIn(vs ...string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldIn(FieldS3WebdavAccessMode, vs...))
}

// S3WebdavAccessModeNotIn applies the NotIn predicate on the "s3_webdav_access_mode" field.
func S3WebdavAccessModeNotIn(vs ...string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNotIn(FieldS3WebdavAccessMode, vs...))
}

// S3WebdavAccessModeGT applies the GT predicate on the "s3_webdav_access_mode" field.
func S3WebdavAccessModeGT(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGT(FieldS3WebdavAccessMode, v))
}

// S3WebdavAccessModeGTE applies the GTE predicate on the "s3_webdav_access_mode" field.
func S3WebdavAccessModeGTE(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGTE(FieldS3WebdavAccessMode, v))
}

// S3WebdavAccessModeLT applies the LT predicate on the "s3_webdav_access_mode" field.
func S3WebdavAccessModeLT(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLT(FieldS3WebdavAccessMode, v))
}

// S3WebdavAccessModeLTE applies the LTE predicate on the "s3_webdav_access_mode" field.
func S3WebdavAccessModeLTE(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLTE(FieldS3WebdavAccessMode, v))
}

// S3WebdavAccessModeContains applies the Contains predicate on the "s3_webdav_access_mode" field.
func S3WebdavAccessModeContains(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldContains(FieldS3WebdavAccessMode, v))
}

// S3WebdavAccessModeHasPrefix applies the HasPrefix predicate on the "s3_webdav_access_mode" field.
func S3WebdavAccessModeHasPrefix(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldHasPrefix(FieldS3WebdavAccessMode, v))
}

// S3WebdavAccessModeHasSuffix applies the HasSuffix predicate on the "s3_webdav_access_mode" field.
func S3WebdavAccessModeHasSuffix(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldHasSuffix(FieldS3WebdavAccessMode, v))
}

// S3WebdavAccessModeEqualFold applies the EqualFold predicate on the "s3_webdav_access_mode" field.
func S3WebdavAccessModeEqualFold(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEqualFold(FieldS3WebdavAccessMode, v))
}

// S3WebdavAccessModeContainsFold applies the ContainsFold predicate on the "s3_webdav_access_mode" field.
func S3WebdavAccessModeContainsFold(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldContainsFold(FieldS3WebdavAccessMode, v))
}

// S3WebdavDedicatedBindHostEQ applies the EQ predicate on the "s3_webdav_dedicated_bind_host" field.
func S3WebdavDedicatedBindHostEQ(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldS3WebdavDedicatedBindHost, v))
}

// S3WebdavDedicatedBindHostNEQ applies the NEQ predicate on the "s3_webdav_dedicated_bind_host" field.
func S3WebdavDedicatedBindHostNEQ(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNEQ(FieldS3WebdavDedicatedBindHost, v))
}

// S3WebdavDedicatedBindHostIn applies the In predicate on the "s3_webdav_dedicated_bind_host" field.
func S3WebdavDedicatedBindHostIn(vs ...string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldIn(FieldS3WebdavDedicatedBindHost, vs...))
}

// S3WebdavDedicatedBindHostNotIn applies the NotIn predicate on the "s3_webdav_dedicated_bind_host" field.
func S3WebdavDedicatedBindHostNotIn(vs ...string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNotIn(FieldS3WebdavDedicatedBindHost, vs...))
}

// S3WebdavDedicatedBindHostGT applies the GT predicate on the "s3_webdav_dedicated_bind_host" field.
func S3WebdavDedicatedBindHostGT(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGT(FieldS3WebdavDedicatedBindHost, v))
}

// S3WebdavDedicatedBindHostGTE applies the GTE predicate on the "s3_webdav_dedicated_bind_host" field.
func S3WebdavDedicatedBindHostGTE(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGTE(FieldS3WebdavDedicatedBindHost, v))
}

// S3WebdavDedicatedBindHostLT applies the LT predicate on the "s3_webdav_dedicated_bind_host" field.
func S3WebdavDedicatedBindHostLT(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLT(FieldS3WebdavDedicatedBindHost, v))
}

// S3WebdavDedicatedBindHostLTE applies the LTE predicate on the "s3_webdav_dedicated_bind_host" field.
func S3WebdavDedicatedBindHostLTE(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLTE(FieldS3WebdavDedicatedBindHost, v))
}

// S3WebdavDedicatedBindHostContains applies the Contains predicate on the "s3_webdav_dedicated_bind_host" field.
func S3WebdavDedicatedBindHostContains(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldContains(FieldS3WebdavDedicatedBindHost, v))
}

// S3WebdavDedicatedBindHostHasPrefix applies the HasPrefix predicate on the "s3_webdav_dedicated_bind_host" field.
func S3WebdavDedicatedBindHostHasPrefix(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldHasPrefix(FieldS3WebdavDedicatedBindHost, v))
}

// S3WebdavDedicatedBindHostHasSuffix applies the HasSuffix predicate on the "s3_webdav_dedicated_bind_host" field.
func S3WebdavDedicatedBindHostHasSuffix(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldHasSuffix(FieldS3WebdavDedicatedBindHost, v))
}

// S3WebdavDedicatedBindHostEqualFold applies the EqualFold predicate on the "s3_webdav_dedicated_bind_host" field.
func S3WebdavDedicatedBindHostEqualFold(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEqualFold(FieldS3WebdavDedicatedBindHost, v))
}

// S3WebdavDedicatedBindHostContainsFold applies the ContainsFold predicate on the "s3_webdav_dedicated_bind_host" field.
func S3WebdavDedicatedBindHostContainsFold(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldContainsFold(FieldS3WebdavDedicatedBindHost, v))
}

// S3WebdavDedicatedPortEQ applies the EQ predicate on the "s3_webdav_dedicated_port" field.
func S3WebdavDedicatedPortEQ(v int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldS3WebdavDedicatedPort, v))
}

// S3WebdavDedicatedPortNEQ applies the NEQ predicate on the "s3_webdav_dedicated_port" field.
func S3WebdavDedicatedPortNEQ(v int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNEQ(FieldS3WebdavDedicatedPort, v))
}

// S3WebdavDedicatedPortIn applies the In predicate on the "s3_webdav_dedicated_port" field.
func S3WebdavDedicatedPortIn(vs ...int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldIn(FieldS3WebdavDedicatedPort, vs...))
}

// S3WebdavDedicatedPortNotIn applies the NotIn predicate on the "s3_webdav_dedicated_port" field.
func S3WebdavDedicatedPortNotIn(vs ...int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNotIn(FieldS3WebdavDedicatedPort, vs...))
}

// S3WebdavDedicatedPortGT applies the GT predicate on the "s3_webdav_dedicated_port" field.
func S3WebdavDedicatedPortGT(v int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGT(FieldS3WebdavDedicatedPort, v))
}

// S3WebdavDedicatedPortGTE applies the GTE predicate on the "s3_webdav_dedicated_port" field.
func S3WebdavDedicatedPortGTE(v int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGTE(FieldS3WebdavDedicatedPort, v))
}

// S3WebdavDedicatedPortLT applies the LT predicate on the "s3_webdav_dedicated_port" field.
func S3WebdavDedicatedPortLT(v int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLT(FieldS3WebdavDedicatedPort, v))
}

// S3WebdavDedicatedPortLTE applies the LTE predicate on the "s3_webdav_dedicated_port" field.
func S3WebdavDedicatedPortLTE(v int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLTE(FieldS3WebdavDedicatedPort, v))
}

// S3WebdavDedicatedAutoStartEQ applies the EQ predicate on the "s3_webdav_dedicated_auto_start" field.
func S3WebdavDedicatedAutoStartEQ(v bool) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldS3WebdavDedicatedAutoStart, v))
}

// S3WebdavDedicatedAutoStartNEQ applies the NEQ predicate on the "s3_webdav_dedicated_auto_start" field.
func S3WebdavDedicatedAutoStartNEQ(v bool) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNEQ(FieldS3WebdavDedicatedAutoStart, v))
}

// S3WebdavDedicatedDomainModeEQ applies the EQ predicate on the "s3_webdav_dedicated_domain_mode" field.
func S3WebdavDedicatedDomainModeEQ(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldS3WebdavDedicatedDomainMode, v))
}

// S3WebdavDedicatedDomainModeNEQ applies the NEQ predicate on the "s3_webdav_dedicated_domain_mode" field.
func S3WebdavDedicatedDomainModeNEQ(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNEQ(FieldS3WebdavDedicatedDomainMode, v))
}

// S3WebdavDedicatedDomainModeIn applies the In predicate on the "s3_webdav_dedicated_domain_mode" field.
func S3WebdavDedicatedDomainModeIn(vs ...string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldIn(FieldS3WebdavDedicatedDomainMode, vs...))
}

// S3WebdavDedicatedDomainModeNotIn applies the NotIn predicate on the "s3_webdav_dedicated_domain_mode" field.
func S3WebdavDedicatedDomainModeNotIn(vs ...string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNotIn(FieldS3WebdavDedicatedDomainMode, vs...))
}

// S3WebdavDedicatedDomainModeGT applies the GT predicate on the "s3_webdav_dedicated_domain_mode" field.
func S3WebdavDedicatedDomainModeGT(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGT(FieldS3WebdavDedicatedDomainMode, v))
}

// S3WebdavDedicatedDomainModeGTE applies the GTE predicate on the "s3_webdav_dedicated_domain_mode" field.
func S3WebdavDedicatedDomainModeGTE(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGTE(FieldS3WebdavDedicatedDomainMode, v))
}

// S3WebdavDedicatedDomainModeLT applies the LT predicate on the "s3_webdav_dedicated_domain_mode" field.
func S3WebdavDedicatedDomainModeLT(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLT(FieldS3WebdavDedicatedDomainMode, v))
}

// S3WebdavDedicatedDomainModeLTE applies the LTE predicate on the "s3_webdav_dedicated_domain_mode" field.
func S3WebdavDedicatedDomainModeLTE(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLTE(FieldS3WebdavDedicatedDomainMode, v))
}

// S3WebdavDedicatedDomainModeContains applies the Contains predicate on the "s3_webdav_dedicated_domain_mode" field.
func S3WebdavDedicatedDomainModeContains(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldContains(FieldS3WebdavDedicatedDomainMode, v))
}

// S3WebdavDedicatedDomainModeHasPrefix applies the HasPrefix predicate on the "s3_webdav_dedicated_domain_mode" field.
func S3WebdavDedicatedDomainModeHasPrefix(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldHasPrefix(FieldS3WebdavDedicatedDomainMode, v))
}

// S3WebdavDedicatedDomainModeHasSuffix applies the HasSuffix predicate on the "s3_webdav_dedicated_domain_mode" field.
func S3WebdavDedicatedDomainModeHasSuffix(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldHasSuffix(FieldS3WebdavDedicatedDomainMode, v))
}

// S3WebdavDedicatedDomainModeEqualFold applies the EqualFold predicate on the "s3_webdav_dedicated_domain_mode" field.
func S3WebdavDedicatedDomainModeEqualFold(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEqualFold(FieldS3WebdavDedicatedDomainMode, v))
}

// S3WebdavDedicatedDomainModeContainsFold applies the ContainsFold predicate on the "s3_webdav_dedicated_domain_mode" field.
func S3WebdavDedicatedDomainModeContainsFold(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldContainsFold(FieldS3WebdavDedicatedDomainMode, v))
}

// S3WebdavDedicatedCustomDomainEQ applies the EQ predicate on the "s3_webdav_dedicated_custom_domain" field.
func S3WebdavDedicatedCustomDomainEQ(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldS3WebdavDedicatedCustomDomain, v))
}

// S3WebdavDedicatedCustomDomainNEQ applies the NEQ predicate on the "s3_webdav_dedicated_custom_domain" field.
func S3WebdavDedicatedCustomDomainNEQ(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNEQ(FieldS3WebdavDedicatedCustomDomain, v))
}

// S3WebdavDedicatedCustomDomainIn applies the In predicate on the "s3_webdav_dedicated_custom_domain" field.
func S3WebdavDedicatedCustomDomainIn(vs ...string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldIn(FieldS3WebdavDedicatedCustomDomain, vs...))
}

// S3WebdavDedicatedCustomDomainNotIn applies the NotIn predicate on the "s3_webdav_dedicated_custom_domain" field.
func S3WebdavDedicatedCustomDomainNotIn(vs ...string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNotIn(FieldS3WebdavDedicatedCustomDomain, vs...))
}

// S3WebdavDedicatedCustomDomainGT applies the GT predicate on the "s3_webdav_dedicated_custom_domain" field.
func S3WebdavDedicatedCustomDomainGT(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGT(FieldS3WebdavDedicatedCustomDomain, v))
}

// S3WebdavDedicatedCustomDomainGTE applies the GTE predicate on the "s3_webdav_dedicated_custom_domain" field.
func S3WebdavDedicatedCustomDomainGTE(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGTE(FieldS3WebdavDedicatedCustomDomain, v))
}

// S3WebdavDedicatedCustomDomainLT applies the LT predicate on the "s3_webdav_dedicated_custom_domain" field.
func S3WebdavDedicatedCustomDomainLT(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLT(FieldS3WebdavDedicatedCustomDomain, v))
}

// S3WebdavDedicatedCustomDomainLTE applies the LTE predicate on the "s3_webdav_dedicated_custom_domain" field.
func S3WebdavDedicatedCustomDomainLTE(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLTE(FieldS3WebdavDedicatedCustomDomain, v))
}

// S3WebdavDedicatedCustomDomainContains applies the Contains predicate on the "s3_webdav_dedicated_custom_domain" field.
func S3WebdavDedicatedCustomDomainContains(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldContains(FieldS3WebdavDedicatedCustomDomain, v))
}

// S3WebdavDedicatedCustomDomainHasPrefix applies the HasPrefix predicate on the "s3_webdav_dedicated_custom_domain" field.
func S3WebdavDedicatedCustomDomainHasPrefix(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldHasPrefix(FieldS3WebdavDedicatedCustomDomain, v))
}

// S3WebdavDedicatedCustomDomainHasSuffix applies the HasSuffix predicate on the "s3_webdav_dedicated_custom_domain" field.
func S3WebdavDedicatedCustomDomainHasSuffix(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldHasSuffix(FieldS3WebdavDedicatedCustomDomain, v))
}

// S3WebdavDedicatedCustomDomainEqualFold applies the EqualFold predicate on the "s3_webdav_dedicated_custom_domain" field.
func S3WebdavDedicatedCustomDomainEqualFold(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEqualFold(FieldS3WebdavDedicatedCustomDomain, v))
}

// S3WebdavDedicatedCustomDomainContainsFold applies the ContainsFold predicate on the "s3_webdav_dedicated_custom_domain" field.
func S3WebdavDedicatedCustomDomainContainsFold(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldContainsFold(FieldS3WebdavDedicatedCustomDomain, v))
}

// S3WebdavDedicatedTunnelHostnameEQ applies the EQ predicate on the "s3_webdav_dedicated_tunnel_hostname" field.
func S3WebdavDedicatedTunnelHostnameEQ(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldS3WebdavDedicatedTunnelHostname, v))
}

// S3WebdavDedicatedTunnelHostnameNEQ applies the NEQ predicate on the "s3_webdav_dedicated_tunnel_hostname" field.
func S3WebdavDedicatedTunnelHostnameNEQ(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNEQ(FieldS3WebdavDedicatedTunnelHostname, v))
}

// S3WebdavDedicatedTunnelHostnameIn applies the In predicate on the "s3_webdav_dedicated_tunnel_hostname" field.
func S3WebdavDedicatedTunnelHostnameIn(vs ...string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldIn(FieldS3WebdavDedicatedTunnelHostname, vs...))
}

// S3WebdavDedicatedTunnelHostnameNotIn applies the NotIn predicate on the "s3_webdav_dedicated_tunnel_hostname" field.
func S3WebdavDedicatedTunnelHostnameNotIn(vs ...string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNotIn(FieldS3WebdavDedicatedTunnelHostname, vs...))
}

// S3WebdavDedicatedTunnelHostnameGT applies the GT predicate on the "s3_webdav_dedicated_tunnel_hostname" field.
func S3WebdavDedicatedTunnelHostnameGT(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGT(FieldS3WebdavDedicatedTunnelHostname, v))
}

// S3WebdavDedicatedTunnelHostnameGTE applies the GTE predicate on the "s3_webdav_dedicated_tunnel_hostname" field.
func S3WebdavDedicatedTunnelHostnameGTE(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGTE(FieldS3WebdavDedicatedTunnelHostname, v))
}

// S3WebdavDedicatedTunnelHostnameLT applies the LT predicate on the "s3_webdav_dedicated_tunnel_hostname" field.
func S3WebdavDedicatedTunnelHostnameLT(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLT(FieldS3WebdavDedicatedTunnelHostname, v))
}

// S3WebdavDedicatedTunnelHostnameLTE applies the LTE predicate on the "s3_webdav_dedicated_tunnel_hostname" field.
func S3WebdavDedicatedTunnelHostnameLTE(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLTE(FieldS3WebdavDedicatedTunnelHostname, v))
}

// S3WebdavDedicatedTunnelHostnameContains applies the Contains predicate on the "s3_webdav_dedicated_tunnel_hostname" field.
func S3WebdavDedicatedTunnelHostnameContains(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldContains(FieldS3WebdavDedicatedTunnelHostname, v))
}

// S3WebdavDedicatedTunnelHostnameHasPrefix applies the HasPrefix predicate on the "s3_webdav_dedicated_tunnel_hostname" field.
func S3WebdavDedicatedTunnelHostnameHasPrefix(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldHasPrefix(FieldS3WebdavDedicatedTunnelHostname, v))
}

// S3WebdavDedicatedTunnelHostnameHasSuffix applies the HasSuffix predicate on the "s3_webdav_dedicated_tunnel_hostname" field.
func S3WebdavDedicatedTunnelHostnameHasSuffix(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldHasSuffix(FieldS3WebdavDedicatedTunnelHostname, v))
}

// S3WebdavDedicatedTunnelHostnameEqualFold applies the EqualFold predicate on the "s3_webdav_dedicated_tunnel_hostname" field.
func S3WebdavDedicatedTunnelHostnameEqualFold(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEqualFold(FieldS3WebdavDedicatedTunnelHostname, v))
}

// S3WebdavDedicatedTunnelHostnameContainsFold applies the ContainsFold predicate on the "s3_webdav_dedicated_tunnel_hostname" field.
func S3WebdavDedicatedTunnelHostnameContainsFold(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldContainsFold(FieldS3WebdavDedicatedTunnelHostname, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AppSetting) predicate.AppSetting {
	return predicate.AppSetting(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AppSetting) predicate.AppSetting {
	return predicate.AppSetting(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AppSetting) predicate.AppSetting {
	return predicate.AppSetting(sql.NotPredicates(p))
}
