// Code generated by ent, DO NOT EDIT.

package oauthstate

import (
	"cfui/internal/persist/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldLTE(FieldID, id))
}

// State applies equality check predicate on the "state" field. It's identical to StateEQ.
func State(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldEQ(FieldState, v))
}

// CodeVerifier applies equality check predicate on the "code_verifier" field. It's identical to CodeVerifierEQ.
func CodeVerifier(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldEQ(FieldCodeVerifier, v))
}

// RedirectURI applies equality check predicate on the "redirect_uri" field. It's identical to RedirectURIEQ.
func RedirectURI(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldEQ(FieldRedirectURI, v))
}

// Scope applies equality check predicate on the "scope" field. It's identical to ScopeEQ.
func Scope(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldEQ(FieldScope, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldEQ(FieldCreatedAt, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldNotIn(FieldState, vs...))
}

// StateGT applies the GT predicate on the "state" field.
func StateGT(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldGT(FieldState, v))
}

// StateGTE applies the GTE predicate on the "state" field.
func StateGTE(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldGTE(FieldState, v))
}

// StateLT applies the LT predicate on the "state" field.
func StateLT(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldLT(FieldState, v))
}

// StateLTE applies the LTE predicate on the "state" field.
func StateLTE(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldLTE(FieldState, v))
}

// StateContains applies the Contains predicate on the "state" field.
func StateContains(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldContains(FieldState, v))
}

// StateHasPrefix applies the HasPrefix predicate on the "state" field.
func StateHasPrefix(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldHasPrefix(FieldState, v))
}

// StateHasSuffix applies the HasSuffix predicate on the "state" field.
func StateHasSuffix(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldHasSuffix(FieldState, v))
}

// StateEqualFold applies the EqualFold predicate on the "state" field.
func StateEqualFold(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldEqualFold(FieldState, v))
}

// StateContainsFold applies the ContainsFold predicate on the "state" field.
func StateContainsFold(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldContainsFold(FieldState, v))
}

// CodeVerifierEQ applies the EQ predicate on the "code_verifier" field.
func CodeVerifierEQ(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldEQ(FieldCodeVerifier, v))
}

// CodeVerifierNEQ applies the NEQ predicate on the "code_verifier" field.
func CodeVerifierNEQ(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldNEQ(FieldCodeVerifier, v))
}

// CodeVerifierIn applies the In predicate on the "code_verifier" field.
func CodeVerifierIn(vs ...string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldIn(FieldCodeVerifier, vs...))
}

// CodeVerifierNotIn applies the NotIn predicate on the "code_verifier" field.
func CodeVerifierNotIn(vs ...string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldNotIn(FieldCodeVerifier, vs...))
}

// CodeVerifierGT applies the GT predicate on the "code_verifier" field.
func CodeVerifierGT(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldGT(FieldCodeVerifier, v))
}

// CodeVerifierGTE applies the GTE predicate on the "code_verifier" field.
func CodeVerifierGTE(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldGTE(FieldCodeVerifier, v))
}

// CodeVerifierLT applies the LT predicate on the "code_verifier" field.
func CodeVerifierLT(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldLT(FieldCodeVerifier, v))
}

// CodeVerifierLTE applies the LTE predicate on the "code_verifier" field.
func CodeVerifierLTE(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldLTE(FieldCodeVerifier, v))
}

// CodeVerifierContains applies the Contains predicate on the "code_verifier" field.
func CodeVerifierContains(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldContains(FieldCodeVerifier, v))
}

// CodeVerifierHasPrefix applies the HasPrefix predicate on the "code_verifier" field.
func CodeVerifierHasPrefix(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldHasPrefix(FieldCodeVerifier, v))
}

// CodeVerifierHasSuffix applies the HasSuffix predicate on the "code_verifier" field.
func CodeVerifierHasSuffix(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldHasSuffix(FieldCodeVerifier, v))
}

// CodeVerifierEqualFold applies the EqualFold predicate on the "code_verifier" field.
func CodeVerifierEqualFold(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldEqualFold(FieldCodeVerifier, v))
}

// CodeVerifierContainsFold applies the ContainsFold predicate on the "code_verifier" field.
func CodeVerifierContainsFold(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldContainsFold(FieldCodeVerifier, v))
}

// RedirectURIEQ applies the EQ predicate on the "redirect_uri" field.
func RedirectURIEQ(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldEQ(FieldRedirectURI, v))
}

// RedirectURINEQ applies the NEQ predicate on the "redirect_uri" field.
func RedirectURINEQ(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldNEQ(FieldRedirectURI, v))
}

// RedirectURIIn applies the In predicate on the "redirect_uri" field.
func RedirectURIIn(vs ...string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldIn(FieldRedirectURI, vs...))
}

// RedirectURINotIn applies the NotIn predicate on the "redirect_uri" field.
func RedirectURINotIn(vs ...string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldNotIn(FieldRedirectURI, vs...))
}

// RedirectURIGT applies the GT predicate on the "redirect_uri" field.
func RedirectURIGT(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldGT(FieldRedirectURI, v))
}

// RedirectURIGTE applies the GTE predicate on the "redirect_uri" field.
func RedirectURIGTE(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldGTE(FieldRedirectURI, v))
}

// RedirectURILT applies the LT predicate on the "redirect_uri" field.
func RedirectURILT(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldLT(FieldRedirectURI, v))
}

// RedirectURILTE applies the LTE predicate on the "redirect_uri" field.
func RedirectURILTE(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldLTE(FieldRedirectURI, v))
}

// RedirectURIContains applies the Contains predicate on the "redirect_uri" field.
func RedirectURIContains(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldContains(FieldRedirectURI, v))
}

// RedirectURIHasPrefix applies the HasPrefix predicate on the "redirect_uri" field.
func RedirectURIHasPrefix(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldHasPrefix(FieldRedirectURI, v))
}

// RedirectURIHasSuffix applies the HasSuffix predicate on the "redirect_uri" field.
func RedirectURIHasSuffix(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldHasSuffix(FieldRedirectURI, v))
}

// RedirectURIEqualFold applies the EqualFold predicate on the "redirect_uri" field.
func RedirectURIEqualFold(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldEqualFold(FieldRedirectURI, v))
}

// RedirectURIContainsFold applies the ContainsFold predicate on the "redirect_uri" field.
func RedirectURIContainsFold(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldContainsFold(FieldRedirectURI, v))
}

// ScopeEQ applies the EQ predicate on the "scope" field.
func ScopeEQ(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldEQ(FieldScope, v))
}

// ScopeNEQ applies the NEQ predicate on the "scope" field.
func ScopeNEQ(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldNEQ(FieldScope, v))
}

// ScopeIn applies the In predicate on the "scope" field.
func ScopeIn(vs ...string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldIn(FieldScope, vs...))
}

// ScopeNotIn applies the NotIn predicate on the "scope" field.
func ScopeNotIn(vs ...string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldNotIn(FieldScope, vs...))
}

// ScopeGT applies the GT predicate on the "scope" field.
func ScopeGT(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldGT(FieldScope, v))
}

// ScopeGTE applies the GTE predicate on the "scope" field.
func ScopeGTE(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldGTE(FieldScope, v))
}

// ScopeLT applies the LT predicate on the "scope" field.
func ScopeLT(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldLT(FieldScope, v))
}

// ScopeLTE applies the LTE predicate on the "scope" field.
func ScopeLTE(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldLTE(FieldScope, v))
}

// ScopeContains applies the Contains predicate on the "scope" field.
func ScopeContains(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldContains(FieldScope, v))
}

// ScopeHasPrefix applies the HasPrefix predicate on the "scope" field.
func ScopeHasPrefix(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldHasPrefix(FieldScope, v))
}

// ScopeHasSuffix applies the HasSuffix predicate on the "scope" field.
func ScopeHasSuffix(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldHasSuffix(FieldScope, v))
}

// ScopeEqualFold applies the EqualFold predicate on the "scope" field.
func ScopeEqualFold(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldEqualFold(FieldScope, v))
}

// ScopeContainsFold applies the ContainsFold predicate on the "scope" field.
func ScopeContainsFold(v string) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldContainsFold(FieldScope, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldLTE(FieldExpiresAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OAuthState {
	return predicate.OAuthState(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OAuthState) predicate.OAuthState {
	return predicate.OAuthState(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OAuthState) predicate.OAuthState {
	return predicate.OAuthState(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OAuthState) predicate.OAuthState {
	return predicate.OAuthState(sql.NotPredicates(p))
}
