// Code generated by ent, DO NOT EDIT.

package mcptoken

import (
	"cfui/internal/persist/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldLTE(FieldID, id))
}

// TokenID applies equality check predicate on the "token_id" field. It's identical to TokenIDEQ.
func TokenID(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldEQ(FieldTokenID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldEQ(FieldName, v))
}

// TokenHash applies equality check predicate on the "token_hash" field. It's identical to TokenHashEQ.
func TokenHash(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldEQ(FieldTokenHash, v))
}

// Masked applies equality check predicate on the "masked" field. It's identical to MaskedEQ.
func Masked(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldEQ(FieldMasked, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldEQ(FieldCreatedAt, v))
}

// TokenIDEQ applies the EQ predicate on the "token_id" field.
func TokenIDEQ(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldEQ(FieldTokenID, v))
}

// TokenIDNEQ applies the NEQ predicate on the "token_id" field.
func TokenIDNEQ(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldNEQ(FieldTokenID, v))
}

// TokenIDIn applies the In predicate on the "token_id" field.
func TokenIDIn(vs ...string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldIn(FieldTokenID, vs...))
}

// TokenIDNotIn applies the NotIn predicate on the "token_id" field.
func TokenIDNotIn(vs ...string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldNotIn(FieldTokenID, vs...))
}

// TokenIDGT applies the GT predicate on the "token_id" field.
func TokenIDGT(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldGT(FieldTokenID, v))
}

// TokenIDGTE applies the GTE predicate on the "token_id" field.
func TokenIDGTE(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldGTE(FieldTokenID, v))
}

// TokenIDLT applies the LT predicate on the "token_id" field.
func TokenIDLT(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldLT(FieldTokenID, v))
}

// TokenIDLTE applies the LTE predicate on the "token_id" field.
func TokenIDLTE(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldLTE(FieldTokenID, v))
}

// TokenIDContains applies the Contains predicate on the "token_id" field.
func TokenIDContains(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldContains(FieldTokenID, v))
}

// TokenIDHasPrefix applies the HasPrefix predicate on the "token_id" field.
func TokenIDHasPrefix(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldHasPrefix(FieldTokenID, v))
}

// TokenIDHasSuffix applies the HasSuffix predicate on the "token_id" field.
func TokenIDHasSuffix(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldHasSuffix(FieldTokenID, v))
}

// TokenIDEqualFold applies the EqualFold predicate on the "token_id" field.
func TokenIDEqualFold(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldEqualFold(FieldTokenID, v))
}

// TokenIDContainsFold applies the ContainsFold predicate on the "token_id" field.
func TokenIDContainsFold(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldContainsFold(FieldTokenID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldContainsFold(FieldName, v))
}

// TokenHashEQ applies the EQ predicate on the "token_hash" field.
func TokenHashEQ(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldEQ(FieldTokenHash, v))
}

// TokenHashNEQ applies the NEQ predicate on the "token_hash" field.
func TokenHashNEQ(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldNEQ(FieldTokenHash, v))
}

// TokenHashIn applies the In predicate on the "token_hash" field.
func TokenHashIn(vs ...string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldIn(FieldTokenHash, vs...))
}

// TokenHashNotIn applies the NotIn predicate on the "token_hash" field.
func TokenHashNotIn(vs ...string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldNotIn(FieldTokenHash, vs...))
}

// TokenHashGT applies the GT predicate on the "token_hash" field.
func TokenHashGT(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldGT(FieldTokenHash, v))
}

// TokenHashGTE applies the GTE predicate on the "token_hash" field.
func TokenHashGTE(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldGTE(FieldTokenHash, v))
}

// TokenHashLT applies the LT predicate on the "token_hash" field.
func TokenHashLT(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldLT(FieldTokenHash, v))
}

// TokenHashLTE applies the LTE predicate on the "token_hash" field.
func TokenHashLTE(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldLTE(FieldTokenHash, v))
}

// TokenHashContains applies the Contains predicate on the "token_hash" field.
func TokenHashContains(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldContains(FieldTokenHash, v))
}

// TokenHashHasPrefix applies the HasPrefix predicate on the "token_hash" field.
func TokenHashHasPrefix(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldHasPrefix(FieldTokenHash, v))
}

// TokenHashHasSuffix applies the HasSuffix predicate on the "token_hash" field.
func TokenHashHasSuffix(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldHasSuffix(FieldTokenHash, v))
}

// TokenHashEqualFold applies the EqualFold predicate on the "token_hash" field.
func TokenHashEqualFold(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldEqualFold(FieldTokenHash, v))
}

// TokenHashContainsFold applies the ContainsFold predicate on the "token_hash" field.
func TokenHashContainsFold(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldContainsFold(FieldTokenHash, v))
}

// MaskedEQ applies the EQ predicate on the "masked" field.
func MaskedEQ(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldEQ(FieldMasked, v))
}

// MaskedNEQ applies the NEQ predicate on the "masked" field.
func MaskedNEQ(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldNEQ(FieldMasked, v))
}

// MaskedIn applies the In predicate on the "masked" field.
func MaskedIn(vs ...string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldIn(FieldMasked, vs...))
}

// MaskedNotIn applies the NotIn predicate on the "masked" field.
func MaskedNotIn(vs ...string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldNotIn(FieldMasked, vs...))
}

// MaskedGT applies the GT predicate on the "masked" field.
func MaskedGT(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldGT(FieldMasked, v))
}

// MaskedGTE applies the GTE predicate on the "masked" field.
func MaskedGTE(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldGTE(FieldMasked, v))
}

// MaskedLT applies the LT predicate on the "masked" field.
func MaskedLT(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldLT(FieldMasked, v))
}

// MaskedLTE applies the LTE predicate on the "masked" field.
func MaskedLTE(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldLTE(FieldMasked, v))
}

// MaskedContains applies the Contains predicate on the "masked" field.
func MaskedContains(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldContains(FieldMasked, v))
}

// MaskedHasPrefix applies the HasPrefix predicate on the "masked" field.
func MaskedHasPrefix(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldHasPrefix(FieldMasked, v))
}

// MaskedHasSuffix applies the HasSuffix predicate on the "masked" field.
func MaskedHasSuffix(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldHasSuffix(FieldMasked, v))
}

// MaskedEqualFold applies the EqualFold predicate on the "masked" field.
func MaskedEqualFold(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldEqualFold(FieldMasked, v))
}

// MaskedContainsFold applies the ContainsFold predicate on the "masked" field.
func MaskedContainsFold(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldContainsFold(FieldMasked, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MCPToken) predicate.MCPToken {
	return predicate.MCPToken(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MCPToken) predicate.MCPToken {
	return predicate.MCPToken(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MCPToken) predicate.MCPToken {
	return predicate.MCPToken(sql.NotPredicates(p))
}
