// Code generated by ent, DO NOT EDIT.

package tunnelprofile

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the tunnelprofile type in the database.
	Label = "tunnel_profile"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldKey holds the string denoting the key field in the database.
	FieldKey = "key"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldSortOrder holds the string denoting the sort_order field in the database.
	FieldSortOrder = "sort_order"
	// FieldToken holds the string denoting the token field in the database.
	FieldToken = "token"
	// FieldLocalEnabled holds the string denoting the local_enabled field in the database.
	FieldLocalEnabled = "local_enabled"
	// FieldRemoteManagementEnabled holds the string denoting the remote_management_enabled field in the database.
	FieldRemoteManagementEnabled = "remote_management_enabled"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldTunnelID holds the string denoting the tunnel_id field in the database.
	FieldTunnelID = "tunnel_id"
	// FieldAutoStart holds the string denoting the auto_start field in the database.
	FieldAutoStart = "auto_start"
	// FieldAutoRestart holds the string denoting the auto_restart field in the database.
	FieldAutoRestart = "auto_restart"
	// FieldCustomTag holds the string denoting the custom_tag field in the database.
	FieldCustomTag = "custom_tag"
	// FieldSoftwareName holds the string denoting the software_name field in the database.
	FieldSoftwareName = "software_name"
	// FieldProtocol holds the string denoting the protocol field in the database.
	FieldProtocol = "protocol"
	// FieldGracePeriod holds the string denoting the grace_period field in the database.
	FieldGracePeriod = "grace_period"
	// FieldRegion holds the string denoting the region field in the database.
	FieldRegion = "region"
	// FieldRetries holds the string denoting the retries field in the database.
	FieldRetries = "retries"
	// FieldMetricsEnable holds the string denoting the metrics_enable field in the database.
	FieldMetricsEnable = "metrics_enable"
	// FieldMetricsPort holds the string denoting the metrics_port field in the database.
	FieldMetricsPort = "metrics_port"
	// FieldLogLevel holds the string denoting the log_level field in the database.
	FieldLogLevel = "log_level"
	// FieldLogFile holds the string denoting the log_file field in the database.
	FieldLogFile = "log_file"
	// FieldLogJSON holds the string denoting the log_json field in the database.
	FieldLogJSON = "log_json"
	// FieldEdgeIPVersion holds the string denoting the edge_ip_version field in the database.
	FieldEdgeIPVersion = "edge_ip_version"
	// FieldEdgeBindAddress holds the string denoting the edge_bind_address field in the database.
	FieldEdgeBindAddress = "edge_bind_address"
	// FieldEdge holds the string denoting the edge field in the database.
	FieldEdge = "edge"
	// FieldPostQuantum holds the string denoting the post_quantum field in the database.
	FieldPostQuantum = "post_quantum"
	// FieldNoTLSVerify holds the string denoting the no_tls_verify field in the database.
	FieldNoTLSVerify = "no_tls_verify"
	// FieldExtraArgs holds the string denoting the extra_args field in the database.
	FieldExtraArgs = "extra_args"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the tunnelprofile in the database.
	Table = "tunnel_profiles"
)

// Columns holds all SQL columns for tunnelprofile fields.
var Columns = []string{
	FieldID,
	FieldKey,
	FieldName,
	FieldSortOrder,
	FieldToken,
	FieldLocalEnabled,
	FieldRemoteManagementEnabled,
	FieldAccountID,
	FieldTunnelID,
	FieldAutoStart,
	FieldAutoRestart,
	FieldCustomTag,
	FieldSoftwareName,
	FieldProtocol,
	FieldGracePeriod,
	FieldRegion,
	FieldRetries,
	FieldMetricsEnable,
	FieldMetricsPort,
	FieldLogLevel,
	FieldLogFile,
	FieldLogJSON,
	FieldEdgeIPVersion,
	FieldEdgeBindAddress,
	FieldEdge,
	FieldPostQuantum,
	FieldNoTLSVerify,
	FieldExtraArgs,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// KeyValidator is a validator for the "key" field. It is called by the builders before save.
	KeyValidator func(string) error
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// DefaultSortOrder holds the default value on creation for the "sort_order" field.
	DefaultSortOrder int
	// DefaultToken holds the default value on creation for the "token" field.
	DefaultToken string
	// DefaultLocalEnabled holds the default value on creation for the "local_enabled" field.
	DefaultLocalEnabled bool
	// DefaultRemoteManagementEnabled holds the default value on creation for the "remote_management_enabled" field.
	DefaultRemoteManagementEnabled bool
	// DefaultAccountID holds the default value on creation for the "account_id" field.
	DefaultAccountID string
	// DefaultTunnelID holds the default value on creation for the "tunnel_id" field.
	DefaultTunnelID string
	// DefaultAutoStart holds the default value on creation for the "auto_start" field.
	DefaultAutoStart bool
	// DefaultAutoRestart holds the default value on creation for the "auto_restart" field.
	DefaultAutoRestart bool
	// DefaultCustomTag holds the default value on creation for the "custom_tag" field.
	DefaultCustomTag string
	// DefaultSoftwareName holds the default value on creation for the "software_name" field.
	DefaultSoftwareName string
	// DefaultProtocol holds the default value on creation for the "protocol" field.
	DefaultProtocol string
	// DefaultGracePeriod holds the default value on creation for the "grace_period" field.
	DefaultGracePeriod string
	// DefaultRegion holds the default value on creation for the "region" field.
	DefaultRegion string
	// DefaultRetries holds the default value on creation for the "retries" field.
	DefaultRetries int
	// DefaultMetricsEnable holds the default value on creation for the "metrics_enable" field.
	DefaultMetricsEnable bool
	// DefaultMetricsPort holds the default value on creation for the "metrics_port" field.
	DefaultMetricsPort int
	// DefaultLogLevel holds the default value on creation for the "log_level" field.
	DefaultLogLevel string
	// DefaultLogFile holds the default value on creation for the "log_file" field.
	DefaultLogFile string
	// DefaultLogJSON holds the default value on creation for the "log_json" field.
	DefaultLogJSON bool
	// DefaultEdgeIPVersion holds the default value on creation for the "edge_ip_version" field.
	DefaultEdgeIPVersion string
	// DefaultEdgeBindAddress holds the default value on creation for the "edge_bind_address" field.
	DefaultEdgeBindAddress string
	// DefaultEdge holds the default value on creation for the "edge" field.
	DefaultEdge string
	// DefaultPostQuantum holds the default value on creation for the "post_quantum" field.
	DefaultPostQuantum bool
	// DefaultNoTLSVerify holds the default value on creation for the "no_tls_verify" field.
	DefaultNoTLSVerify bool
	// DefaultExtraArgs holds the default value on creation for the "extra_args" field.
	DefaultExtraArgs string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the TunnelProfile queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByKey orders the results by the key field.
func ByKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKey, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// BySortOrder orders the results by the sort_order field.
func BySortOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortOrder, opts...).ToFunc()
}

// ByToken orders the results by the token field.
func ByToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToken, opts...).ToFunc()
}

// ByLocalEnabled orders the results by the local_enabled field.
func ByLocalEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocalEnabled, opts...).ToFunc()
}

// ByRemoteManagementEnabled orders the results by the remote_management_enabled field.
func ByRemoteManagementEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemoteManagementEnabled, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByTunnelID orders the results by the tunnel_id field.
func ByTunnelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTunnelID, opts...).ToFunc()
}

// ByAutoStart orders the results by the auto_start field.
func ByAutoStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAutoStart, opts...).ToFunc()
}

// ByAutoRestart orders the results by the auto_restart field.
func ByAutoRestart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAutoRestart, opts...).ToFunc()
}

// ByCustomTag orders the results by the custom_tag field.
func ByCustomTag(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomTag, opts...).ToFunc()
}

// BySoftwareName orders the results by the software_name field.
func BySoftwareName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSoftwareName, opts...).ToFunc()
}

// ByProtocol orders the results by the protocol field.
func ByProtocol(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProtocol, opts...).ToFunc()
}

// ByGracePeriod orders the results by the grace_period field.
func ByGracePeriod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGracePeriod, opts...).ToFunc()
}

// ByRegion orders the results by the region field.
func ByRegion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRegion, opts...).ToFunc()
}

// ByRetries orders the results by the retries field.
func ByRetries(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRetries, opts...).ToFunc()
}

// ByMetricsEnable orders the results by the metrics_enable field.
func ByMetricsEnable(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetricsEnable, opts...).ToFunc()
}

// ByMetricsPort orders the results by the metrics_port field.
func ByMetricsPort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetricsPort, opts...).ToFunc()
}

// ByLogLevel orders the results by the log_level field.
func ByLogLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLogLevel, opts...).ToFunc()
}

// ByLogFile orders the results by the log_file field.
func ByLogFile(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLogFile, opts...).ToFunc()
}

// ByLogJSON orders the results by the log_json field.
func ByLogJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLogJSON, opts...).ToFunc()
}

// ByEdgeIPVersion orders the results by the edge_ip_version field.
func ByEdgeIPVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEdgeIPVersion, opts...).ToFunc()
}

// ByEdgeBindAddress orders the results by the edge_bind_address field.
func ByEdgeBindAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEdgeBindAddress, opts...).ToFunc()
}

// ByEdge orders the results by the edge field.
func ByEdge(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEdge, opts...).ToFunc()
}

// ByPostQuantum orders the results by the post_quantum field.
func ByPostQuantum(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPostQuantum, opts...).ToFunc()
}

// ByNoTLSVerify orders the results by the no_tls_verify field.
func ByNoTLSVerify(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNoTLSVerify, opts...).ToFunc()
}

// ByExtraArgs orders the results by the extra_args field.
func ByExtraArgs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExtraArgs, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
