// Code generated by ent, DO NOT EDIT.

package s3webdavsetting

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the s3webdavsetting type in the database.
	Label = "s3web_dav_setting"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldKey holds the string denoting the key field in the database.
	FieldKey = "key"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldSortOrder holds the string denoting the sort_order field in the database.
	FieldSortOrder = "sort_order"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldWebdavEnabled holds the string denoting the webdav_enabled field in the database.
	FieldWebdavEnabled = "webdav_enabled"
	// FieldWebdavAuthEnabled holds the string denoting the webdav_auth_enabled field in the database.
	FieldWebdavAuthEnabled = "webdav_auth_enabled"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldEndpointURL holds the string denoting the endpoint_url field in the database.
	FieldEndpointURL = "endpoint_url"
	// FieldRegion holds the string denoting the region field in the database.
	FieldRegion = "region"
	// FieldPathStyle holds the string denoting the path_style field in the database.
	FieldPathStyle = "path_style"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldBucketName holds the string denoting the bucket_name field in the database.
	FieldBucketName = "bucket_name"
	// FieldRootPrefix holds the string denoting the root_prefix field in the database.
	FieldRootPrefix = "root_prefix"
	// FieldMountPath holds the string denoting the mount_path field in the database.
	FieldMountPath = "mount_path"
	// FieldJurisdiction holds the string denoting the jurisdiction field in the database.
	FieldJurisdiction = "jurisdiction"
	// FieldAccessKeyID holds the string denoting the access_key_id field in the database.
	FieldAccessKeyID = "access_key_id"
	// FieldSecretAccessKey holds the string denoting the secret_access_key field in the database.
	FieldSecretAccessKey = "secret_access_key"
	// FieldWebdavUsername holds the string denoting the webdav_username field in the database.
	FieldWebdavUsername = "webdav_username"
	// FieldWebdavPasswordHash holds the string denoting the webdav_password_hash field in the database.
	FieldWebdavPasswordHash = "webdav_password_hash"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the s3webdavsetting in the database.
	Table = "s3_webdav_settings"
)

// Columns holds all SQL columns for s3webdavsetting fields.
var Columns = []string{
	FieldID,
	FieldKey,
	FieldName,
	FieldSortOrder,
	FieldEnabled,
	FieldWebdavEnabled,
	FieldWebdavAuthEnabled,
	FieldProvider,
	FieldEndpointURL,
	FieldRegion,
	FieldPathStyle,
	FieldAccountID,
	FieldBucketName,
	FieldRootPrefix,
	FieldMountPath,
	FieldJurisdiction,
	FieldAccessKeyID,
	FieldSecretAccessKey,
	FieldWebdavUsername,
	FieldWebdavPasswordHash,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// KeyValidator is a validator for the "key" field. It is called by the builders before save.
	KeyValidator func(string) error
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// DefaultSortOrder holds the default value on creation for the "sort_order" field.
	DefaultSortOrder int
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultWebdavEnabled holds the default value on creation for the "webdav_enabled" field.
	DefaultWebdavEnabled bool
	// DefaultWebdavAuthEnabled holds the default value on creation for the "webdav_auth_enabled" field.
	DefaultWebdavAuthEnabled bool
	// DefaultProvider holds the default value on creation for the "provider" field.
	DefaultProvider string
	// DefaultEndpointURL holds the default value on creation for the "endpoint_url" field.
	DefaultEndpointURL string
	// DefaultRegion holds the default value on creation for the "region" field.
	DefaultRegion string
	// DefaultPathStyle holds the default value on creation for the "path_style" field.
	DefaultPathStyle bool
	// DefaultAccountID holds the default value on creation for the "account_id" field.
	DefaultAccountID string
	// DefaultBucketName holds the default value on creation for the "bucket_name" field.
	DefaultBucketName string
	// DefaultRootPrefix holds the default value on creation for the "root_prefix" field.
	DefaultRootPrefix string
	// DefaultMountPath holds the default value on creation for the "mount_path" field.
	DefaultMountPath string
	// DefaultJurisdiction holds the default value on creation for the "jurisdiction" field.
	DefaultJurisdiction string
	// DefaultAccessKeyID holds the default value on creation for the "access_key_id" field.
	DefaultAccessKeyID string
	// DefaultSecretAccessKey holds the default value on creation for the "secret_access_key" field.
	DefaultSecretAccessKey string
	// DefaultWebdavUsername holds the default value on creation for the "webdav_username" field.
	DefaultWebdavUsername string
	// DefaultWebdavPasswordHash holds the default value on creation for the "webdav_password_hash" field.
	DefaultWebdavPasswordHash string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the S3WebDAVSetting queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByKey orders the results by the key field.
func ByKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKey, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// BySortOrder orders the results by the sort_order field.
func BySortOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortOrder, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByWebdavEnabled orders the results by the webdav_enabled field.
func ByWebdavEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWebdavEnabled, opts...).ToFunc()
}

// ByWebdavAuthEnabled orders the results by the webdav_auth_enabled field.
func ByWebdavAuthEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWebdavAuthEnabled, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByEndpointURL orders the results by the endpoint_url field.
func ByEndpointURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndpointURL, opts...).ToFunc()
}

// ByRegion orders the results by the region field.
func ByRegion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRegion, opts...).ToFunc()
}

// ByPathStyle orders the results by the path_style field.
func ByPathStyle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPathStyle, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByBucketName orders the results by the bucket_name field.
func ByBucketName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBucketName, opts...).ToFunc()
}

// ByRootPrefix orders the results by the root_prefix field.
func ByRootPrefix(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRootPrefix, opts...).ToFunc()
}

// ByMountPath orders the results by the mount_path field.
func ByMountPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMountPath, opts...).ToFunc()
}

// ByJurisdiction orders the results by the jurisdiction field.
func ByJurisdiction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJurisdiction, opts...).ToFunc()
}

// ByAccessKeyID orders the results by the access_key_id field.
func ByAccessKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccessKeyID, opts...).ToFunc()
}

// BySecretAccessKey orders the results by the secret_access_key field.
func BySecretAccessKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSecretAccessKey, opts...).ToFunc()
}

// ByWebdavUsername orders the results by the webdav_username field.
func ByWebdavUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWebdavUsername, opts...).ToFunc()
}

// ByWebdavPasswordHash orders the results by the webdav_password_hash field.
func ByWebdavPasswordHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWebdavPasswordHash, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
