// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cfui/internal/persist/ent/appsetting"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// AppSetting is the model entity for the AppSetting schema.
type AppSetting struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Key holds the value of the "key" field.
	Key string `json:"key,omitempty"`
	// AutoStart holds the value of the "auto_start" field.
	AutoStart bool `json:"auto_start,omitempty"`
	// AutoRestart holds the value of the "auto_restart" field.
	AutoRestart bool `json:"auto_restart,omitempty"`
	// CustomTag holds the value of the "custom_tag" field.
	CustomTag string `json:"custom_tag,omitempty"`
	// SoftwareName holds the value of the "software_name" field.
	SoftwareName string `json:"software_name,omitempty"`
	// Protocol holds the value of the "protocol" field.
	Protocol string `json:"protocol,omitempty"`
	// GracePeriod holds the value of the "grace_period" field.
	GracePeriod string `json:"grace_period,omitempty"`
	// Region holds the value of the "region" field.
	Region string `json:"region,omitempty"`
	// Retries holds the value of the "retries" field.
	Retries int `json:"retries,omitempty"`
	// MetricsEnable holds the value of the "metrics_enable" field.
	MetricsEnable bool `json:"metrics_enable,omitempty"`
	// MetricsPort holds the value of the "metrics_port" field.
	MetricsPort int `json:"metrics_port,omitempty"`
	// LogLevel holds the value of the "log_level" field.
	LogLevel string `json:"log_level,omitempty"`
	// LogFile holds the value of the "log_file" field.
	LogFile string `json:"log_file,omitempty"`
	// LogJSON holds the value of the "log_json" field.
	LogJSON bool `json:"log_json,omitempty"`
	// EdgeIPVersion holds the value of the "edge_ip_version" field.
	EdgeIPVersion string `json:"edge_ip_version,omitempty"`
	// EdgeBindAddress holds the value of the "edge_bind_address" field.
	EdgeBindAddress string `json:"edge_bind_address,omitempty"`
	// PostQuantum holds the value of the "post_quantum" field.
	PostQuantum bool `json:"post_quantum,omitempty"`
	// NoTLSVerify holds the value of the "no_tls_verify" field.
	NoTLSVerify bool `json:"no_tls_verify,omitempty"`
	// ExtraArgs holds the value of the "extra_args" field.
	ExtraArgs string `json:"extra_args,omitempty"`
	// McpEnabled holds the value of the "mcp_enabled" field.
	McpEnabled bool `json:"mcp_enabled,omitempty"`
	// S3WebdavEnabled holds the value of the "s3_webdav_enabled" field.
	S3WebdavEnabled bool `json:"s3_webdav_enabled,omitempty"`
	// S3WebdavActiveKey holds the value of the "s3_webdav_active_key" field.
	S3WebdavActiveKey string `json:"s3_webdav_active_key,omitempty"`
	// S3WebdavAccessMode holds the value of the "s3_webdav_access_mode" field.
	S3WebdavAccessMode string `json:"s3_webdav_access_mode,omitempty"`
	// S3WebdavDedicatedBindHost holds the value of the "s3_webdav_dedicated_bind_host" field.
	S3WebdavDedicatedBindHost string `json:"s3_webdav_dedicated_bind_host,omitempty"`
	// S3WebdavDedicatedPort holds the value of the "s3_webdav_dedicated_port" field.
	S3WebdavDedicatedPort int `json:"s3_webdav_dedicated_port,omitempty"`
	// S3WebdavDedicatedAutoStart holds the value of the "s3_webdav_dedicated_auto_start" field.
	S3WebdavDedicatedAutoStart bool `json:"s3_webdav_dedicated_auto_start,omitempty"`
	// S3WebdavDedicatedDomainMode holds the value of the "s3_webdav_dedicated_domain_mode" field.
	S3WebdavDedicatedDomainMode string `json:"s3_webdav_dedicated_domain_mode,omitempty"`
	// S3WebdavDedicatedCustomDomain holds the value of the "s3_webdav_dedicated_custom_domain" field.
	S3WebdavDedicatedCustomDomain string `json:"s3_webdav_dedicated_custom_domain,omitempty"`
	// S3WebdavDedicatedTunnelHostname holds the value of the "s3_webdav_dedicated_tunnel_hostname" field.
	S3WebdavDedicatedTunnelHostname string `json:"s3_webdav_dedicated_tunnel_hostname,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AppSetting) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case appsetting.FieldAutoStart, appsetting.FieldAutoRestart, appsetting.FieldMetricsEnable, appsetting.FieldLogJSON, appsetting.FieldPostQuantum, appsetting.FieldNoTLSVerify, appsetting.FieldMcpEnabled, appsetting.FieldS3WebdavEnabled, appsetting.FieldS3WebdavDedicatedAutoStart:
			values[i] = new(sql.NullBool)
		case appsetting.FieldID, appsetting.FieldRetries, appsetting.FieldMetricsPort, appsetting.FieldS3WebdavDedicatedPort:
			values[i] = new(sql.NullInt64)
		case appsetting.FieldKey, appsetting.FieldCustomTag, appsetting.FieldSoftwareName, appsetting.FieldProtocol, appsetting.FieldGracePeriod, appsetting.FieldRegion, appsetting.FieldLogLevel, appsetting.FieldLogFile, appsetting.FieldEdgeIPVersion, appsetting.FieldEdgeBindAddress, appsetting.FieldExtraArgs, appsetting.FieldS3WebdavActiveKey, appsetting.FieldS3WebdavAccessMode, appsetting.FieldS3WebdavDedicatedBindHost, appsetting.FieldS3WebdavDedicatedDomainMode, appsetting.FieldS3WebdavDedicatedCustomDomain, appsetting.FieldS3WebdavDedicatedTunnelHostname:
			values[i] = new(sql.NullString)
		case appsetting.FieldCreatedAt, appsetting.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AppSetting fields.
func (_m *AppSetting) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case appsetting.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case appsetting.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				_m.Key = value.String
			}
		case appsetting.FieldAutoStart:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field auto_start", values[i])
			} else if value.Valid {
				_m.AutoStart = value.Bool
			}
		case appsetting.FieldAutoRestart:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field auto_restart", values[i])
			} else if value.Valid {
				_m.AutoRestart = value.Bool
			}
		case appsetting.FieldCustomTag:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field custom_tag", values[i])
			} else if value.Valid {
				_m.CustomTag = value.String
			}
		case appsetting.FieldSoftwareName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field software_name", values[i])
			} else if value.Valid {
				_m.SoftwareName = value.String
			}
		case appsetting.FieldProtocol:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field protocol", values[i])
			} else if value.Valid {
				_m.Protocol = value.String
			}
		case appsetting.FieldGracePeriod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field grace_period", values[i])
			} else if value.Valid {
				_m.GracePeriod = value.String
			}
		case appsetting.FieldRegion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field region", values[i])
			} else if value.Valid {
				_m.Region = value.String
			}
		case appsetting.FieldRetries:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field retries", values[i])
			} else if value.Valid {
				_m.Retries = int(value.Int64)
			}
		case appsetting.FieldMetricsEnable:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field metrics_enable", values[i])
			} else if value.Valid {
				_m.MetricsEnable = value.Bool
			}
		case appsetting.FieldMetricsPort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field metrics_port", values[i])
			} else if value.Valid {
				_m.MetricsPort = int(value.Int64)
			}
		case appsetting.FieldLogLevel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field log_level", values[i])
			} else if value.Valid {
				_m.LogLevel = value.String
			}
		case appsetting.FieldLogFile:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field log_file", values[i])
			} else if value.Valid {
				_m.LogFile = value.String
			}
		case appsetting.FieldLogJSON:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field log_json", values[i])
			} else if value.Valid {
				_m.LogJSON = value.Bool
			}
		case appsetting.FieldEdgeIPVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field edge_ip_version", values[i])
			} else if value.Valid {
				_m.EdgeIPVersion = value.String
			}
		case appsetting.FieldEdgeBindAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field edge_bind_address", values[i])
			} else if value.Valid {
				_m.EdgeBindAddress = value.String
			}
		case appsetting.FieldPostQuantum:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field post_quantum", values[i])
			} else if value.Valid {
				_m.PostQuantum = value.Bool
			}
		case appsetting.FieldNoTLSVerify:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field no_tls_verify", values[i])
			} else if value.Valid {
				_m.NoTLSVerify = value.Bool
			}
		case appsetting.FieldExtraArgs:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field extra_args", values[i])
			} else if value.Valid {
				_m.ExtraArgs = value.String
			}
		case appsetting.FieldMcpEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field mcp_enabled", values[i])
			} else if value.Valid {
				_m.McpEnabled = value.Bool
			}
		case appsetting.FieldS3WebdavEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field s3_webdav_enabled", values[i])
			} else if value.Valid {
				_m.S3WebdavEnabled = value.Bool
			}
		case appsetting.FieldS3WebdavActiveKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field s3_webdav_active_key", values[i])
			} else if value.Valid {
				_m.S3WebdavActiveKey = value.String
			}
		case appsetting.FieldS3WebdavAccessMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field s3_webdav_access_mode", values[i])
			} else if value.Valid {
				_m.S3WebdavAccessMode = value.String
			}
		case appsetting.FieldS3WebdavDedicatedBindHost:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field s3_webdav_dedicated_bind_host", values[i])
			} else if value.Valid {
				_m.S3WebdavDedicatedBindHost = value.String
			}
		case appsetting.FieldS3WebdavDedicatedPort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field s3_webdav_dedicated_port", values[i])
			} else if value.Valid {
				_m.S3WebdavDedicatedPort = int(value.Int64)
			}
		case appsetting.FieldS3WebdavDedicatedAutoStart:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field s3_webdav_dedicated_auto_start", values[i])
			} else if value.Valid {
				_m.S3WebdavDedicatedAutoStart = value.Bool
			}
		case appsetting.FieldS3WebdavDedicatedDomainMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field s3_webdav_dedicated_domain_mode", values[i])
			} else if value.Valid {
				_m.S3WebdavDedicatedDomainMode = value.String
			}
		case appsetting.FieldS3WebdavDedicatedCustomDomain:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field s3_webdav_dedicated_custom_domain", values[i])
			} else if value.Valid {
				_m.S3WebdavDedicatedCustomDomain = value.String
			}
		case appsetting.FieldS3WebdavDedicatedTunnelHostname:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field s3_webdav_dedicated_tunnel_hostname", values[i])
			} else if value.Valid {
				_m.S3WebdavDedicatedTunnelHostname = value.String
			}
		case appsetting.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case appsetting.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AppSetting.
// This includes values selected through modifiers, order, etc.
func (_m *AppSetting) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AppSetting.
// Note that you need to call AppSetting.Unwrap() before calling this method if this AppSetting
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AppSetting) Update() *AppSettingUpdateOne {
	return NewAppSettingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AppSetting entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AppSetting) Unwrap() *AppSetting {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AppSetting is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AppSetting) String() string {
	var builder strings.Builder
	builder.WriteString("AppSetting(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("key=")
	builder.WriteString(_m.Key)
	builder.WriteString(", ")
	builder.WriteString("auto_start=")
	builder.WriteString(fmt.Sprintf("%v", _m.AutoStart))
	builder.WriteString(", ")
	builder.WriteString("auto_restart=")
	builder.WriteString(fmt.Sprintf("%v", _m.AutoRestart))
	builder.WriteString(", ")
	builder.WriteString("custom_tag=")
	builder.WriteString(_m.CustomTag)
	builder.WriteString(", ")
	builder.WriteString("software_name=")
	builder.WriteString(_m.SoftwareName)
	builder.WriteString(", ")
	builder.WriteString("protocol=")
	builder.WriteString(_m.Protocol)
	builder.WriteString(", ")
	builder.WriteString("grace_period=")
	builder.WriteString(_m.GracePeriod)
	builder.WriteString(", ")
	builder.WriteString("region=")
	builder.WriteString(_m.Region)
	builder.WriteString(", ")
	builder.WriteString("retries=")
	builder.WriteString(fmt.Sprintf("%v", _m.Retries))
	builder.WriteString(", ")
	builder.WriteString("metrics_enable=")
	builder.WriteString(fmt.Sprintf("%v", _m.MetricsEnable))
	builder.WriteString(", ")
	builder.WriteString("metrics_port=")
	builder.WriteString(fmt.Sprintf("%v", _m.MetricsPort))
	builder.WriteString(", ")
	builder.WriteString("log_level=")
	builder.WriteString(_m.LogLevel)
	builder.WriteString(", ")
	builder.WriteString("log_file=")
	builder.WriteString(_m.LogFile)
	builder.WriteString(", ")
	builder.WriteString("log_json=")
	builder.WriteString(fmt.Sprintf("%v", _m.LogJSON))
	builder.WriteString(", ")
	builder.WriteString("edge_ip_version=")
	builder.WriteString(_m.EdgeIPVersion)
	builder.WriteString(", ")
	builder.WriteString("edge_bind_address=")
	builder.WriteString(_m.EdgeBindAddress)
	builder.WriteString(", ")
	builder.WriteString("post_quantum=")
	builder.WriteString(fmt.Sprintf("%v", _m.PostQuantum))
	builder.WriteString(", ")
	builder.WriteString("no_tls_verify=")
	builder.WriteString(fmt.Sprintf("%v", _m.NoTLSVerify))
	builder.WriteString(", ")
	builder.WriteString("extra_args=")
	builder.WriteString(_m.ExtraArgs)
	builder.WriteString(", ")
	builder.WriteString("mcp_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.McpEnabled))
	builder.WriteString(", ")
	builder.WriteString("s3_webdav_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.S3WebdavEnabled))
	builder.WriteString(", ")
	builder.WriteString("s3_webdav_active_key=")
	builder.WriteString(_m.S3WebdavActiveKey)
	builder.WriteString(", ")
	builder.WriteString("s3_webdav_access_mode=")
	builder.WriteString(_m.S3WebdavAccessMode)
	builder.WriteString(", ")
	builder.WriteString("s3_webdav_dedicated_bind_host=")
	builder.WriteString(_m.S3WebdavDedicatedBindHost)
	builder.WriteString(", ")
	builder.WriteString("s3_webdav_dedicated_port=")
	builder.WriteString(fmt.Sprintf("%v", _m.S3WebdavDedicatedPort))
	builder.WriteString(", ")
	builder.WriteString("s3_webdav_dedicated_auto_start=")
	builder.WriteString(fmt.Sprintf("%v", _m.S3WebdavDedicatedAutoStart))
	builder.WriteString(", ")
	builder.WriteString("s3_webdav_dedicated_domain_mode=")
	builder.WriteString(_m.S3WebdavDedicatedDomainMode)
	builder.WriteString(", ")
	builder.WriteString("s3_webdav_dedicated_custom_domain=")
	builder.WriteString(_m.S3WebdavDedicatedCustomDomain)
	builder.WriteString(", ")
	builder.WriteString("s3_webdav_dedicated_tunnel_hostname=")
	builder.WriteString(_m.S3WebdavDedicatedTunnelHostname)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AppSettings is a parsable slice of AppSetting.
type AppSettings []*AppSetting
