// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cfui/internal/persist/ent/appsetting"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AppSettingCreate is the builder for creating a AppSetting entity.
type AppSettingCreate struct {
	config
	mutation *AppSettingMutation
	hooks    []Hook
}

// SetKey sets the "key" field.
func (_c *AppSettingCreate) SetKey(v string) *AppSettingCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetAutoStart sets the "auto_start" field.
func (_c *AppSettingCreate) SetAutoStart(v bool) *AppSettingCreate {
	_c.mutation.SetAutoStart(v)
	return _c
}

// SetNillableAutoStart sets the "auto_start" field if the given value is not nil.
func (_c *AppSettingCreate) SetNillableAutoStart(v *bool) *AppSettingCreate {
	if v != nil {
		_c.SetAutoStart(*v)
	}
	return _c
}

// SetAutoRestart sets the "auto_restart" field.
func (_c *AppSettingCreate) SetAutoRestart(v bool) *AppSettingCreate {
	_c.mutation.SetAutoRestart(v)
	return _c
}

// SetNillableAutoRestart sets the "auto_restart" field if the given value is not nil.
func (_c *AppSettingCreate) SetNillableAutoRestart(v *bool) *AppSettingCreate {
	if v != nil {
		_c.SetAutoRestart(*v)
	}
	return _c
}

// SetCustomTag sets the "custom_tag" field.
func (_c *AppSettingCreate) SetCustomTag(v string) *AppSettingCreate {
	_c.mutation.SetCustomTag(v)
	return _c
}

// SetNillableCustomTag sets the "custom_tag" field if the given value is not nil.
func (_c *AppSettingCreate) SetNillableCustomTag(v *string) *AppSettingCreate {
	if v != nil {
		_c.SetCustomTag(*v)
	}
	return _c
}

// SetSoftwareName sets the "software_name" field.
func (_c *AppSettingCreate) SetSoftwareName(v string) *AppSettingCreate {
	_c.mutation.SetSoftwareName(v)
	return _c
}

// SetNillableSoftwareName sets the "software_name" field if the given value is not nil.
func (_c *AppSettingCreate) SetNillableSoftwareName(v *string) *AppSettingCreate {
	if v != nil {
		_c.SetSoftwareName(*v)
	}
	return _c
}

// SetProtocol sets the "protocol" field.
func (_c *AppSettingCreate) SetProtocol(v string) *AppSettingCreate {
	_c.mutation.SetProtocol(v)
	return _c
}

// SetNillableProtocol sets the "protocol" field if the given value is not nil.
func (_c *AppSettingCreate) SetNillableProtocol(v *string) *AppSettingCreate {
	if v != nil {
		_c.SetProtocol(*v)
	}
	return _c
}

// SetGracePeriod sets the "grace_period" field.
func (_c *AppSettingCreate) SetGracePeriod(v string) *AppSettingCreate {
	_c.mutation.SetGracePeriod(v)
	return _c
}

// SetNillableGracePeriod sets the "grace_period" field if the given value is not nil.
func (_c *AppSettingCreate) SetNillableGracePeriod(v *string) *AppSettingCreate {
	if v != nil {
		_c.SetGracePeriod(*v)
	}
	return _c
}

// SetRegion sets the "region" field.
func (_c *AppSettingCreate) SetRegion(v string) *AppSettingCreate {
	_c.mutation.SetRegion(v)
	return _c
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_c *AppSettingCreate) SetNillableRegion(v *string) *AppSettingCreate {
	if v != nil {
		_c.SetRegion(*v)
	}
	return _c
}

// SetRetries sets the "retries" field.
func (_c *AppSettingCreate) SetRetries(v int) *AppSettingCreate {
	_c.mutation.SetRetries(v)
	return _c
}

// SetNillableRetries sets the "retries" field if the given value is not nil.
func (_c *AppSettingCreate) SetNillableRetries(v *int) *AppSettingCreate {
	if v != nil {
		_c.SetRetries(*v)
	}
	return _c
}

// SetMetricsEnable sets the "metrics_enable" field.
func (_c *AppSettingCreate) SetMetricsEnable(v bool) *AppSettingCreate {
	_c.mutation.SetMetricsEnable(v)
	return _c
}

// SetNillableMetricsEnable sets the "metrics_enable" field if the given value is not nil.
func (_c *AppSettingCreate) SetNillableMetricsEnable(v *bool) *AppSettingCreate {
	if v != nil {
		_c.SetMetricsEnable(*v)
	}
	return _c
}

// SetMetricsPort sets the "metrics_port" field.
func (_c *AppSettingCreate) SetMetricsPort(v int) *AppSettingCreate {
	_c.mutation.SetMetricsPort(v)
	return _c
}

// SetNillableMetricsPort sets the "metrics_port" field if the given value is not nil.
func (_c *AppSettingCreate) SetNillableMetricsPort(v *int) *AppSettingCreate {
	if v != nil {
		_c.SetMetricsPort(*v)
	}
	return _c
}

// SetLogLevel sets the "log_level" field.
func (_c *AppSettingCreate) SetLogLevel(v string) *AppSettingCreate {
	_c.mutation.SetLogLevel(v)
	return _c
}

// SetNillableLogLevel sets the "log_level" field if the given value is not nil.
func (_c *AppSettingCreate) SetNillableLogLevel(v *string) *AppSettingCreate {
	if v != nil {
		_c.SetLogLevel(*v)
	}
	return _c
}

// SetLogFile sets the "log_file" field.
func (_c *AppSettingCreate) SetLogFile(v string) *AppSettingCreate {
	_c.mutation.SetLogFile(v)
	return _c
}

// SetNillableLogFile sets the "log_file" field if the given value is not nil.
func (_c *AppSettingCreate) SetNillableLogFile(v *string) *AppSettingCreate {
	if v != nil {
		_c.SetLogFile(*v)
	}
	return _c
}

// SetLogJSON sets the "log_json" field.
func (_c *AppSettingCreate) SetLogJSON(v bool) *AppSettingCreate {
	_c.mutation.SetLogJSON(v)
	return _c
}

// SetNillableLogJSON sets the "log_json" field if the given value is not nil.
func (_c *AppSettingCreate) SetNillableLogJSON(v *bool) *AppSettingCreate {
	if v != nil {
		_c.SetLogJSON(*v)
	}
	return _c
}

// SetEdgeIPVersion sets the "edge_ip_version" field.
func (_c *AppSettingCreate) SetEdgeIPVersion(v string) *AppSettingCreate {
	_c.mutation.SetEdgeIPVersion(v)
	return _c
}

// SetNillableEdgeIPVersion sets the "edge_ip_version" field if the given value is not nil.
func (_c *AppSettingCreate) SetNillableEdgeIPVersion(v *string) *AppSettingCreate {
	if v != nil {
		_c.SetEdgeIPVersion(*v)
	}
	return _c
}

// SetEdgeBindAddress sets the "edge_bind_address" field.
func (_c *AppSettingCreate) SetEdgeBindAddress(v string) *AppSettingCreate {
	_c.mutation.SetEdgeBindAddress(v)
	return _c
}

// SetNillableEdgeBindAddress sets the "edge_bind_address" field if the given value is not nil.
func (_c *AppSettingCreate) SetNillableEdgeBindAddress(v *string) *AppSettingCreate {
	if v != nil {
		_c.SetEdgeBindAddress(*v)
	}
	return _c
}

// SetPostQuantum sets the "post_quantum" field.
func (_c *AppSettingCreate) SetPostQuantum(v bool) *AppSettingCreate {
	_c.mutation.SetPostQuantum(v)
	return _c
}

// SetNillablePostQuantum sets the "post_quantum" field if the given value is not nil.
func (_c *AppSettingCreate) SetNillablePostQuantum(v *bool) *AppSettingCreate {
	if v != nil {
		_c.SetPostQuantum(*v)
	}
	return _c
}

// SetNoTLSVerify sets the "no_tls_verify" field.
func (_c *AppSettingCreate) SetNoTLSVerify(v bool) *AppSettingCreate {
	_c.mutation.SetNoTLSVerify(v)
	return _c
}

// SetNillableNoTLSVerify sets the "no_tls_verify" field if the given value is not nil.
func (_c *AppSettingCreate) SetNillableNoTLSVerify(v *bool) *AppSettingCreate {
	if v != nil {
		_c.SetNoTLSVerify(*v)
	}
	return _c
}

// SetExtraArgs sets the "extra_args" field.
func (_c *AppSettingCreate) SetExtraArgs(v string) *AppSettingCreate {
	_c.mutation.SetExtraArgs(v)
	return _c
}

// SetNillableExtraArgs sets the "extra_args" field if the given value is not nil.
func (_c *AppSettingCreate) SetNillableExtraArgs(v *string) *AppSettingCreate {
	if v != nil {
		_c.SetExtraArgs(*v)
	}
	return _c
}

// SetMcpEnabled sets the "mcp_enabled" field.
func (_c *AppSettingCreate) SetMcpEnabled(v bool) *AppSettingCreate {
	_c.mutation.SetMcpEnabled(v)
	return _c
}

// SetNillableMcpEnabled sets the "mcp_enabled" field if the given value is not nil.
func (_c *AppSettingCreate) SetNillableMcpEnabled(v *bool) *AppSettingCreate {
	if v != nil {
		_c.SetMcpEnabled(*v)
	}
	return _c
}

// SetS3WebdavEnabled sets the "s3_webdav_enabled" field.
func (_c *AppSettingCreate) SetS3WebdavEnabled(v bool) *AppSettingCreate {
	_c.mutation.SetS3WebdavEnabled(v)
	return _c
}

// SetNillableS3WebdavEnabled sets the "s3_webdav_enabled" field if the given value is not nil.
func (_c *AppSettingCreate) SetNillableS3WebdavEnabled(v *bool) *AppSettingCreate {
	if v != nil {
		_c.SetS3WebdavEnabled(*v)
	}
	return _c
}

// SetS3WebdavActiveKey sets the "s3_webdav_active_key" field.
func (_c *AppSettingCreate) SetS3WebdavActiveKey(v string) *AppSettingCreate {
	_c.mutation.SetS3WebdavActiveKey(v)
	return _c
}

// SetNillableS3WebdavActiveKey sets the "s3_webdav_active_key" field if the given value is not nil.
func (_c *AppSettingCreate) SetNillableS3WebdavActiveKey(v *string) *AppSettingCreate {
	if v != nil {
		_c.SetS3WebdavActiveKey(*v)
	}
	return _c
}

// SetS3WebdavAccessMode sets the "s3_webdav_access_mode" field.
func (_c *AppSettingCreate) SetS3WebdavAccessMode(v string) *AppSettingCreate {
	_c.mutation.SetS3WebdavAccessMode(v)
	return _c
}

// SetNillableS3WebdavAccessMode sets the "s3_webdav_access_mode" field if the given value is not nil.
func (_c *AppSettingCreate) SetNillableS3WebdavAccessMode(v *string) *AppSettingCreate {
	if v != nil {
		_c.SetS3WebdavAccessMode(*v)
	}
	return _c
}

// SetS3WebdavDedicatedBindHost sets the "s3_webdav_dedicated_bind_host" field.
func (_c *AppSettingCreate) SetS3WebdavDedicatedBindHost(v string) *AppSettingCreate {
	_c.mutation.SetS3WebdavDedicatedBindHost(v)
	return _c
}

// SetNillableS3WebdavDedicatedBindHost sets the "s3_webdav_dedicated_bind_host" field if the given value is not nil.
func (_c *AppSettingCreate) SetNillableS3WebdavDedicatedBindHost(v *string) *AppSettingCreate {
	if v != nil {
		_c.SetS3WebdavDedicatedBindHost(*v)
	}
	return _c
}

// SetS3WebdavDedicatedPort sets the "s3_webdav_dedicated_port" field.
func (_c *AppSettingCreate) SetS3WebdavDedicatedPort(v int) *AppSettingCreate {
	_c.mutation.SetS3WebdavDedicatedPort(v)
	return _c
}

// SetNillableS3WebdavDedicatedPort sets the "s3_webdav_dedicated_port" field if the given value is not nil.
func (_c *AppSettingCreate) SetNillableS3WebdavDedicatedPort(v *int) *AppSettingCreate {
	if v != nil {
		_c.SetS3WebdavDedicatedPort(*v)
	}
	return _c
}

// SetS3WebdavDedicatedAutoStart sets the "s3_webdav_dedicated_auto_start" field.
func (_c *AppSettingCreate) SetS3WebdavDedicatedAutoStart(v bool) *AppSettingCreate {
	_c.mutation.SetS3WebdavDedicatedAutoStart(v)
	return _c
}

// SetNillableS3WebdavDedicatedAutoStart sets the "s3_webdav_dedicated_auto_start" field if the given value is not nil.
func (_c *AppSettingCreate) SetNillableS3WebdavDedicatedAutoStart(v *bool) *AppSettingCreate {
	if v != nil {
		_c.SetS3WebdavDedicatedAutoStart(*v)
	}
	return _c
}

// SetS3WebdavDedicatedDomainMode sets the "s3_webdav_dedicated_domain_mode" field.
func (_c *AppSettingCreate) SetS3WebdavDedicatedDomainMode(v string) *AppSettingCreate {
	_c.mutation.SetS3WebdavDedicatedDomainMode(v)
	return _c
}

// SetNillableS3WebdavDedicatedDomainMode sets the "s3_webdav_dedicated_domain_mode" field if the given value is not nil.
func (_c *AppSettingCreate) SetNillableS3WebdavDedicatedDomainMode(v *string) *AppSettingCreate {
	if v != nil {
		_c.SetS3WebdavDedicatedDomainMode(*v)
	}
	return _c
}

// SetS3WebdavDedicatedCustomDomain sets the "s3_webdav_dedicated_custom_domain" field.
func (_c *AppSettingCreate) SetS3WebdavDedicatedCustomDomain(v string) *AppSettingCreate {
	_c.mutation.SetS3WebdavDedicatedCustomDomain(v)
	return _c
}

// SetNillableS3WebdavDedicatedCustomDomain sets the "s3_webdav_dedicated_custom_domain" field if the given value is not nil.
func (_c *AppSettingCreate) SetNillableS3WebdavDedicatedCustomDomain(v *string) *AppSettingCreate {
	if v != nil {
		_c.SetS3WebdavDedicatedCustomDomain(*v)
	}
	return _c
}

// SetS3WebdavDedicatedTunnelHostname sets the "s3_webdav_dedicated_tunnel_hostname" field.
func (_c *AppSettingCreate) SetS3WebdavDedicatedTunnelHostname(v string) *AppSettingCreate {
	_c.mutation.SetS3WebdavDedicatedTunnelHostname(v)
	return _c
}

// SetNillableS3WebdavDedicatedTunnelHostname sets the "s3_webdav_dedicated_tunnel_hostname" field if the given value is not nil.
func (_c *AppSettingCreate) SetNillableS3WebdavDedicatedTunnelHostname(v *string) *AppSettingCreate {
	if v != nil {
		_c.SetS3WebdavDedicatedTunnelHostname(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AppSettingCreate) SetCreatedAt(v time.Time) *AppSettingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AppSettingCreate) SetNillableCreatedAt(v *time.Time) *AppSettingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AppSettingCreate) SetUpdatedAt(v time.Time) *AppSettingCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AppSettingCreate) SetNillableUpdatedAt(v *time.Time) *AppSettingCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the AppSettingMutation object of the builder.
func (_c *AppSettingCreate) Mutation() *AppSettingMutation {
	return _c.mutation
}

// Save creates the AppSetting in the database.
func (_c *AppSettingCreate) Save(ctx context.Context) (*AppSetting, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AppSettingCreate) SaveX(ctx context.Context) *AppSetting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AppSettingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AppSettingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AppSettingCreate) defaults() {
	if _, ok := _c.mutation.AutoStart(); !ok {
		v := appsetting.DefaultAutoStart
		_c.mutation.SetAutoStart(v)
	}
	if _, ok := _c.mutation.AutoRestart(); !ok {
		v := appsetting.DefaultAutoRestart
		_c.mutation.SetAutoRestart(v)
	}
	if _, ok := _c.mutation.CustomTag(); !ok {
		v := appsetting.DefaultCustomTag
		_c.mutation.SetCustomTag(v)
	}
	if _, ok := _c.mutation.SoftwareName(); !ok {
		v := appsetting.DefaultSoftwareName
		_c.mutation.SetSoftwareName(v)
	}
	if _, ok := _c.mutation.Protocol(); !ok {
		v := appsetting.DefaultProtocol
		_c.mutation.SetProtocol(v)
	}
	if _, ok := _c.mutation.GracePeriod(); !ok {
		v := appsetting.DefaultGracePeriod
		_c.mutation.SetGracePeriod(v)
	}
	if _, ok := _c.mutation.Region(); !ok {
		v := appsetting.DefaultRegion
		_c.mutation.SetRegion(v)
	}
	if _, ok := _c.mutation.Retries(); !ok {
		v := appsetting.DefaultRetries
		_c.mutation.SetRetries(v)
	}
	if _, ok := _c.mutation.MetricsEnable(); !ok {
		v := appsetting.DefaultMetricsEnable
		_c.mutation.SetMetricsEnable(v)
	}
	if _, ok := _c.mutation.MetricsPort(); !ok {
		v := appsetting.DefaultMetricsPort
		_c.mutation.SetMetricsPort(v)
	}
	if _, ok := _c.mutation.LogLevel(); !ok {
		v := appsetting.DefaultLogLevel
		_c.mutation.SetLogLevel(v)
	}
	if _, ok := _c.mutation.LogFile(); !ok {
		v := appsetting.DefaultLogFile
		_c.mutation.SetLogFile(v)
	}
	if _, ok := _c.mutation.LogJSON(); !ok {
		v := appsetting.DefaultLogJSON
		_c.mutation.SetLogJSON(v)
	}
	if _, ok := _c.mutation.EdgeIPVersion(); !ok {
		v := appsetting.DefaultEdgeIPVersion
		_c.mutation.SetEdgeIPVersion(v)
	}
	if _, ok := _c.mutation.EdgeBindAddress(); !ok {
		v := appsetting.DefaultEdgeBindAddress
		_c.mutation.SetEdgeBindAddress(v)
	}
	if _, ok := _c.mutation.PostQuantum(); !ok {
		v := appsetting.DefaultPostQuantum
		_c.mutation.SetPostQuantum(v)
	}
	if _, ok := _c.mutation.NoTLSVerify(); !ok {
		v := appsetting.DefaultNoTLSVerify
		_c.mutation.SetNoTLSVerify(v)
	}
	if _, ok := _c.mutation.ExtraArgs(); !ok {
		v := appsetting.DefaultExtraArgs
		_c.mutation.SetExtraArgs(v)
	}
	if _, ok := _c.mutation.McpEnabled(); !ok {
		v := appsetting.DefaultMcpEnabled
		_c.mutation.SetMcpEnabled(v)
	}
	if _, ok := _c.mutation.S3WebdavEnabled(); !ok {
		v := appsetting.DefaultS3WebdavEnabled
		_c.mutation.SetS3WebdavEnabled(v)
	}
	if _, ok := _c.mutation.S3WebdavActiveKey(); !ok {
		v := appsetting.DefaultS3WebdavActiveKey
		_c.mutation.SetS3WebdavActiveKey(v)
	}
	if _, ok := _c.mutation.S3WebdavAccessMode(); !ok {
		v := appsetting.DefaultS3WebdavAccessMode
		_c.mutation.SetS3WebdavAccessMode(v)
	}
	if _, ok := _c.mutation.S3WebdavDedicatedBindHost(); !ok {
		v := appsetting.DefaultS3WebdavDedicatedBindHost
		_c.mutation.SetS3WebdavDedicatedBindHost(v)
	}
	if _, ok := _c.mutation.S3WebdavDedicatedPort(); !ok {
		v := appsetting.DefaultS3WebdavDedicatedPort
		_c.mutation.SetS3WebdavDedicatedPort(v)
	}
	if _, ok := _c.mutation.S3WebdavDedicatedAutoStart(); !ok {
		v := appsetting.DefaultS3WebdavDedicatedAutoStart
		_c.mutation.SetS3WebdavDedicatedAutoStart(v)
	}
	if _, ok := _c.mutation.S3WebdavDedicatedDomainMode(); !ok {
		v := appsetting.DefaultS3WebdavDedicatedDomainMode
		_c.mutation.SetS3WebdavDedicatedDomainMode(v)
	}
	if _, ok := _c.mutation.S3WebdavDedicatedCustomDomain(); !ok {
		v := appsetting.DefaultS3WebdavDedicatedCustomDomain
		_c.mutation.SetS3WebdavDedicatedCustomDomain(v)
	}
	if _, ok := _c.mutation.S3WebdavDedicatedTunnelHostname(); !ok {
		v := appsetting.DefaultS3WebdavDedicatedTunnelHostname
		_c.mutation.SetS3WebdavDedicatedTunnelHostname(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := appsetting.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := appsetting.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AppSettingCreate) check() error {
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "AppSetting.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := appsetting.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "AppSetting.key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AutoStart(); !ok {
		return &ValidationError{Name: "auto_start", err: errors.New(`ent: missing required field "AppSetting.auto_start"`)}
	}
	if _, ok := _c.mutation.AutoRestart(); !ok {
		return &ValidationError{Name: "auto_restart", err: errors.New(`ent: missing required field "AppSetting.auto_restart"`)}
	}
	if _, ok := _c.mutation.CustomTag(); !ok {
		return &ValidationError{Name: "custom_tag", err: errors.New(`ent: missing required field "AppSetting.custom_tag"`)}
	}
	if _, ok := _c.mutation.SoftwareName(); !ok {
		return &ValidationError{Name: "software_name", err: errors.New(`ent: missing required field "AppSetting.software_name"`)}
	}
	if _, ok := _c.mutation.Protocol(); !ok {
		return &ValidationError{Name: "protocol", err: errors.New(`ent: missing required field "AppSetting.protocol"`)}
	}
	if _, ok := _c.mutation.GracePeriod(); !ok {
		return &ValidationError{Name: "grace_period", err: errors.New(`ent: missing required field "AppSetting.grace_period"`)}
	}
	if _, ok := _c.mutation.Region(); !ok {
		return &ValidationError{Name: "region", err: errors.New(`ent: missing required field "AppSetting.region"`)}
	}
	if _, ok := _c.mutation.Retries(); !ok {
		return &ValidationError{Name: "retries", err: errors.New(`ent: missing required field "AppSetting.retries"`)}
	}
	if _, ok := _c.mutation.MetricsEnable(); !ok {
		return &ValidationError{Name: "metrics_enable", err: errors.New(`ent: missing required field "AppSetting.metrics_enable"`)}
	}
	if _, ok := _c.mutation.MetricsPort(); !ok {
		return &ValidationError{Name: "metrics_port", err: errors.New(`ent: missing required field "AppSetting.metrics_port"`)}
	}
	if _, ok := _c.mutation.LogLevel(); !ok {
		return &ValidationError{Name: "log_level", err: errors.New(`ent: missing required field "AppSetting.log_level"`)}
	}
	if _, ok := _c.mutation.LogFile(); !ok {
		return &ValidationError{Name: "log_file", err: errors.New(`ent: missing required field "AppSetting.log_file"`)}
	}
	if _, ok := _c.mutation.LogJSON(); !ok {
		return &ValidationError{Name: "log_json", err: errors.New(`ent: missing required field "AppSetting.log_json"`)}
	}
	if _, ok := _c.mutation.EdgeIPVersion(); !ok {
		return &ValidationError{Name: "edge_ip_version", err: errors.New(`ent: missing required field "AppSetting.edge_ip_version"`)}
	}
	if _, ok := _c.mutation.EdgeBindAddress(); !ok {
		return &ValidationError{Name: "edge_bind_address", err: errors.New(`ent: missing required field "AppSetting.edge_bind_address"`)}
	}
	if _, ok := _c.mutation.PostQuantum(); !ok {
		return &ValidationError{Name: "post_quantum", err: errors.New(`ent: missing required field "AppSetting.post_quantum"`)}
	}
	if _, ok := _c.mutation.NoTLSVerify(); !ok {
		return &ValidationError{Name: "no_tls_verify", err: errors.New(`ent: missing required field "AppSetting.no_tls_verify"`)}
	}
	if _, ok := _c.mutation.ExtraArgs(); !ok {
		return &ValidationError{Name: "extra_args", err: errors.New(`ent: missing required field "AppSetting.extra_args"`)}
	}
	if _, ok := _c.mutation.McpEnabled(); !ok {
		return &ValidationError{Name: "mcp_enabled", err: errors.New(`ent: missing required field "AppSetting.mcp_enabled"`)}
	}
	if _, ok := _c.mutation.S3WebdavEnabled(); !ok {
		return &ValidationError{Name: "s3_webdav_enabled", err: errors.New(`ent: missing required field "AppSetting.s3_webdav_enabled"`)}
	}
	if _, ok := _c.mutation.S3WebdavActiveKey(); !ok {
		return &ValidationError{Name: "s3_webdav_active_key", err: errors.New(`ent: missing required field "AppSetting.s3_webdav_active_key"`)}
	}
	if _, ok := _c.mutation.S3WebdavAccessMode(); !ok {
		return &ValidationError{Name: "s3_webdav_access_mode", err: errors.New(`ent: missing required field "AppSetting.s3_webdav_access_mode"`)}
	}
	if _, ok := _c.mutation.S3WebdavDedicatedBindHost(); !ok {
		return &ValidationError{Name: "s3_webdav_dedicated_bind_host", err: errors.New(`ent: missing required field "AppSetting.s3_webdav_dedicated_bind_host"`)}
	}
	if _, ok := _c.mutation.S3WebdavDedicatedPort(); !ok {
		return &ValidationError{Name: "s3_webdav_dedicated_port", err: errors.New(`ent: missing required field "AppSetting.s3_webdav_dedicated_port"`)}
	}
	if _, ok := _c.mutation.S3WebdavDedicatedAutoStart(); !ok {
		return &ValidationError{Name: "s3_webdav_dedicated_auto_start", err: errors.New(`ent: missing required field "AppSetting.s3_webdav_dedicated_auto_start"`)}
	}
	if _, ok := _c.mutation.S3WebdavDedicatedDomainMode(); !ok {
		return &ValidationError{Name: "s3_webdav_dedicated_domain_mode", err: errors.New(`ent: missing required field "AppSetting.s3_webdav_dedicated_domain_mode"`)}
	}
	if _, ok := _c.mutation.S3WebdavDedicatedCustomDomain(); !ok {
		return &ValidationError{Name: "s3_webdav_dedicated_custom_domain", err: errors.New(`ent: missing required field "AppSetting.s3_webdav_dedicated_custom_domain"`)}
	}
	if _, ok := _c.mutation.S3WebdavDedicatedTunnelHostname(); !ok {
		return &ValidationError{Name: "s3_webdav_dedicated_tunnel_hostname", err: errors.New(`ent: missing required field "AppSetting.s3_webdav_dedicated_tunnel_hostname"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AppSetting.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AppSetting.updated_at"`)}
	}
	return nil
}

func (_c *AppSettingCreate) sqlSave(ctx context.Context) (*AppSetting, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AppSettingCreate) createSpec() (*AppSetting, *sqlgraph.CreateSpec) {
	var (
		_node = &AppSetting{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(appsetting.Table, sqlgraph.NewFieldSpec(appsetting.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(appsetting.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.AutoStart(); ok {
		_spec.SetField(appsetting.FieldAutoStart, field.TypeBool, value)
		_node.AutoStart = value
	}
	if value, ok := _c.mutation.AutoRestart(); ok {
		_spec.SetField(appsetting.FieldAutoRestart, field.TypeBool, value)
		_node.AutoRestart = value
	}
	if value, ok := _c.mutation.CustomTag(); ok {
		_spec.SetField(appsetting.FieldCustomTag, field.TypeString, value)
		_node.CustomTag = value
	}
	if value, ok := _c.mutation.SoftwareName(); ok {
		_spec.SetField(appsetting.FieldSoftwareName, field.TypeString, value)
		_node.SoftwareName = value
	}
	if value, ok := _c.mutation.Protocol(); ok {
		_spec.SetField(appsetting.FieldProtocol, field.TypeString, value)
		_node.Protocol = value
	}
	if value, ok := _c.mutation.GracePeriod(); ok {
		_spec.SetField(appsetting.FieldGracePeriod, field.TypeString, value)
		_node.GracePeriod = value
	}
	if value, ok := _c.mutation.Region(); ok {
		_spec.SetField(appsetting.FieldRegion, field.TypeString, value)
		_node.Region = value
	}
	if value, ok := _c.mutation.Retries(); ok {
		_spec.SetField(appsetting.FieldRetries, field.TypeInt, value)
		_node.Retries = value
	}
	if value, ok := _c.mutation.MetricsEnable(); ok {
		_spec.SetField(appsetting.FieldMetricsEnable, field.TypeBool, value)
		_node.MetricsEnable = value
	}
	if value, ok := _c.mutation.MetricsPort(); ok {
		_spec.SetField(appsetting.FieldMetricsPort, field.TypeInt, value)
		_node.MetricsPort = value
	}
	if value, ok := _c.mutation.LogLevel(); ok {
		_spec.SetField(appsetting.FieldLogLevel, field.TypeString, value)
		_node.LogLevel = value
	}
	if value, ok := _c.mutation.LogFile(); ok {
		_spec.SetField(appsetting.FieldLogFile, field.TypeString, value)
		_node.LogFile = value
	}
	if value, ok := _c.mutation.LogJSON(); ok {
		_spec.SetField(appsetting.FieldLogJSON, field.TypeBool, value)
		_node.LogJSON = value
	}
	if value, ok := _c.mutation.EdgeIPVersion(); ok {
		_spec.SetField(appsetting.FieldEdgeIPVersion, field.TypeString, value)
		_node.EdgeIPVersion = value
	}
	if value, ok := _c.mutation.EdgeBindAddress(); ok {
		_spec.SetField(appsetting.FieldEdgeBindAddress, field.TypeString, value)
		_node.EdgeBindAddress = value
	}
	if value, ok := _c.mutation.PostQuantum(); ok {
		_spec.SetField(appsetting.FieldPostQuantum, field.TypeBool, value)
		_node.PostQuantum = value
	}
	if value, ok := _c.mutation.NoTLSVerify(); ok {
		_spec.SetField(appsetting.FieldNoTLSVerify, field.TypeBool, value)
		_node.NoTLSVerify = value
	}
	if value, ok := _c.mutation.ExtraArgs(); ok {
		_spec.SetField(appsetting.FieldExtraArgs, field.TypeString, value)
		_node.ExtraArgs = value
	}
	if value, ok := _c.mutation.McpEnabled(); ok {
		_spec.SetField(appsetting.FieldMcpEnabled, field.TypeBool, value)
		_node.McpEnabled = value
	}
	if value, ok := _c.mutation.S3WebdavEnabled(); ok {
		_spec.SetField(appsetting.FieldS3WebdavEnabled, field.TypeBool, value)
		_node.S3WebdavEnabled = value
	}
	if value, ok := _c.mutation.S3WebdavActiveKey(); ok {
		_spec.SetField(appsetting.FieldS3WebdavActiveKey, field.TypeString, value)
		_node.S3WebdavActiveKey = value
	}
	if value, ok := _c.mutation.S3WebdavAccessMode(); ok {
		_spec.SetField(appsetting.FieldS3WebdavAccessMode, field.TypeString, value)
		_node.S3WebdavAccessMode = value
	}
	if value, ok := _c.mutation.S3WebdavDedicatedBindHost(); ok {
		_spec.SetField(appsetting.FieldS3WebdavDedicatedBindHost, field.TypeString, value)
		_node.S3WebdavDedicatedBindHost = value
	}
	if value, ok := _c.mutation.S3WebdavDedicatedPort(); ok {
		_spec.SetField(appsetting.FieldS3WebdavDedicatedPort, field.TypeInt, value)
		_node.S3WebdavDedicatedPort = value
	}
	if value, ok := _c.mutation.S3WebdavDedicatedAutoStart(); ok {
		_spec.SetField(appsetting.FieldS3WebdavDedicatedAutoStart, field.TypeBool, value)
		_node.S3WebdavDedicatedAutoStart = value
	}
	if value, ok := _c.mutation.S3WebdavDedicatedDomainMode(); ok {
		_spec.SetField(appsetting.FieldS3WebdavDedicatedDomainMode, field.TypeString, value)
		_node.S3WebdavDedicatedDomainMode = value
	}
	if value, ok := _c.mutation.S3WebdavDedicatedCustomDomain(); ok {
		_spec.SetField(appsetting.FieldS3WebdavDedicatedCustomDomain, field.TypeString, value)
		_node.S3WebdavDedicatedCustomDomain = value
	}
	if value, ok := _c.mutation.S3WebdavDedicatedTunnelHostname(); ok {
		_spec.SetField(appsetting.FieldS3WebdavDedicatedTunnelHostname, field.TypeString, value)
		_node.S3WebdavDedicatedTunnelHostname = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(appsetting.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(appsetting.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// AppSettingCreateBulk is the builder for creating many AppSetting entities in bulk.
type AppSettingCreateBulk struct {
	config
	err      error
	builders []*AppSettingCreate
}

// Save creates the AppSetting entities in the database.
func (_c *AppSettingCreateBulk) Save(ctx context.Context) ([]*AppSetting, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AppSetting, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AppSettingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AppSettingCreateBulk) SaveX(ctx context.Context) []*AppSetting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AppSettingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AppSettingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
