// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"cfui/internal/persist/ent/migrate"

	"cfui/internal/persist/ent/appsetting"
	"cfui/internal/persist/ent/ddnsipsource"
	"cfui/internal/persist/ent/ddnsrecord"
	"cfui/internal/persist/ent/ddnssetting"
	"cfui/internal/persist/ent/mcptoken"
	"cfui/internal/persist/ent/oauthsession"
	"cfui/internal/persist/ent/oauthstate"
	"cfui/internal/persist/ent/s3webdavsetting"
	"cfui/internal/persist/ent/tunnelmanagement"
	"cfui/internal/persist/ent/tunnelprofile"
	"cfui/internal/persist/ent/tunneltoken"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// AppSetting is the client for interacting with the AppSetting builders.
	AppSetting *AppSettingClient
	// DDNSIPSource is the client for interacting with the DDNSIPSource builders.
	DDNSIPSource *DDNSIPSourceClient
	// DDNSRecord is the client for interacting with the DDNSRecord builders.
	DDNSRecord *DDNSRecordClient
	// DDNSSetting is the client for interacting with the DDNSSetting builders.
	DDNSSetting *DDNSSettingClient
	// MCPToken is the client for interacting with the MCPToken builders.
	MCPToken *MCPTokenClient
	// OAuthSession is the client for interacting with the OAuthSession builders.
	OAuthSession *OAuthSessionClient
	// OAuthState is the client for interacting with the OAuthState builders.
	OAuthState *OAuthStateClient
	// S3WebDAVSetting is the client for interacting with the S3WebDAVSetting builders.
	S3WebDAVSetting *S3WebDAVSettingClient
	// TunnelManagement is the client for interacting with the TunnelManagement builders.
	TunnelManagement *TunnelManagementClient
	// TunnelProfile is the client for interacting with the TunnelProfile builders.
	TunnelProfile *TunnelProfileClient
	// TunnelToken is the client for interacting with the TunnelToken builders.
	TunnelToken *TunnelTokenClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.AppSetting = NewAppSettingClient(c.config)
	c.DDNSIPSource = NewDDNSIPSourceClient(c.config)
	c.DDNSRecord = NewDDNSRecordClient(c.config)
	c.DDNSSetting = NewDDNSSettingClient(c.config)
	c.MCPToken = NewMCPTokenClient(c.config)
	c.OAuthSession = NewOAuthSessionClient(c.config)
	c.OAuthState = NewOAuthStateClient(c.config)
	c.S3WebDAVSetting = NewS3WebDAVSettingClient(c.config)
	c.TunnelManagement = NewTunnelManagementClient(c.config)
	c.TunnelProfile = NewTunnelProfileClient(c.config)
	c.TunnelToken = NewTunnelTokenClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:              ctx,
		config:           cfg,
		AppSetting:       NewAppSettingClient(cfg),
		DDNSIPSource:     NewDDNSIPSourceClient(cfg),
		DDNSRecord:       NewDDNSRecordClient(cfg),
		DDNSSetting:      NewDDNSSettingClient(cfg),
		MCPToken:         NewMCPTokenClient(cfg),
		OAuthSession:     NewOAuthSessionClient(cfg),
		OAuthState:       NewOAuthStateClient(cfg),
		S3WebDAVSetting:  NewS3WebDAVSettingClient(cfg),
		TunnelManagement: NewTunnelManagementClient(cfg),
		TunnelProfile:    NewTunnelProfileClient(cfg),
		TunnelToken:      NewTunnelTokenClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:              ctx,
		config:           cfg,
		AppSetting:       NewAppSettingClient(cfg),
		DDNSIPSource:     NewDDNSIPSourceClient(cfg),
		DDNSRecord:       NewDDNSRecordClient(cfg),
		DDNSSetting:      NewDDNSSettingClient(cfg),
		MCPToken:         NewMCPTokenClient(cfg),
		OAuthSession:     NewOAuthSessionClient(cfg),
		OAuthState:       NewOAuthStateClient(cfg),
		S3WebDAVSetting:  NewS3WebDAVSettingClient(cfg),
		TunnelManagement: NewTunnelManagementClient(cfg),
		TunnelProfile:    NewTunnelProfileClient(cfg),
		TunnelToken:      NewTunnelTokenClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		AppSetting.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.AppSetting, c.DDNSIPSource, c.DDNSRecord, c.DDNSSetting, c.MCPToken,
		c.OAuthSession, c.OAuthState, c.S3WebDAVSetting, c.TunnelManagement,
		c.TunnelProfile, c.TunnelToken,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.AppSetting, c.DDNSIPSource, c.DDNSRecord, c.DDNSSetting, c.MCPToken,
		c.OAuthSession, c.OAuthState, c.S3WebDAVSetting, c.TunnelManagement,
		c.TunnelProfile, c.TunnelToken,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AppSettingMutation:
		return c.AppSetting.mutate(ctx, m)
	case *DDNSIPSourceMutation:
		return c.DDNSIPSource.mutate(ctx, m)
	case *DDNSRecordMutation:
		return c.DDNSRecord.mutate(ctx, m)
	case *DDNSSettingMutation:
		return c.DDNSSetting.mutate(ctx, m)
	case *MCPTokenMutation:
		return c.MCPToken.mutate(ctx, m)
	case *OAuthSessionMutation:
		return c.OAuthSession.mutate(ctx, m)
	case *OAuthStateMutation:
		return c.OAuthState.mutate(ctx, m)
	case *S3WebDAVSettingMutation:
		return c.S3WebDAVSetting.mutate(ctx, m)
	case *TunnelManagementMutation:
		return c.TunnelManagement.mutate(ctx, m)
	case *TunnelProfileMutation:
		return c.TunnelProfile.mutate(ctx, m)
	case *TunnelTokenMutation:
		return c.TunnelToken.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AppSettingClient is a client for the AppSetting schema.
type AppSettingClient struct {
	config
}

// NewAppSettingClient returns a client for the AppSetting from the given config.
func NewAppSettingClient(c config) *AppSettingClient {
	return &AppSettingClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `appsetting.Hooks(f(g(h())))`.
func (c *AppSettingClient) Use(hooks ...Hook) {
	c.hooks.AppSetting = append(c.hooks.AppSetting, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `appsetting.Intercept(f(g(h())))`.
func (c *AppSettingClient) Intercept(interceptors ...Interceptor) {
	c.inters.AppSetting = append(c.inters.AppSetting, interceptors...)
}

// Create returns a builder for creating a AppSetting entity.
func (c *AppSettingClient) Create() *AppSettingCreate {
	mutation := newAppSettingMutation(c.config, OpCreate)
	return &AppSettingCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AppSetting entities.
func (c *AppSettingClient) CreateBulk(builders ...*AppSettingCreate) *AppSettingCreateBulk {
	return &AppSettingCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AppSettingClient) MapCreateBulk(slice any, setFunc func(*AppSettingCreate, int)) *AppSettingCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AppSettingCreateBulk{err: fmt.Errorf("calling to AppSettingClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AppSettingCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AppSettingCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AppSetting.
func (c *AppSettingClient) Update() *AppSettingUpdate {
	mutation := newAppSettingMutation(c.config, OpUpdate)
	return &AppSettingUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AppSettingClient) UpdateOne(_m *AppSetting) *AppSettingUpdateOne {
	mutation := newAppSettingMutation(c.config, OpUpdateOne, withAppSetting(_m))
	return &AppSettingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AppSettingClient) UpdateOneID(id int) *AppSettingUpdateOne {
	mutation := newAppSettingMutation(c.config, OpUpdateOne, withAppSettingID(id))
	return &AppSettingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AppSetting.
func (c *AppSettingClient) Delete() *AppSettingDelete {
	mutation := newAppSettingMutation(c.config, OpDelete)
	return &AppSettingDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AppSettingClient) DeleteOne(_m *AppSetting) *AppSettingDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AppSettingClient) DeleteOneID(id int) *AppSettingDeleteOne {
	builder := c.Delete().Where(appsetting.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AppSettingDeleteOne{builder}
}

// Query returns a query builder for AppSetting.
func (c *AppSettingClient) Query() *AppSettingQuery {
	return &AppSettingQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAppSetting},
		inters: c.Interceptors(),
	}
}

// Get returns a AppSetting entity by its id.
func (c *AppSettingClient) Get(ctx context.Context, id int) (*AppSetting, error) {
	return c.Query().Where(appsetting.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AppSettingClient) GetX(ctx context.Context, id int) *AppSetting {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AppSettingClient) Hooks() []Hook {
	return c.hooks.AppSetting
}

// Interceptors returns the client interceptors.
func (c *AppSettingClient) Interceptors() []Interceptor {
	return c.inters.AppSetting
}

func (c *AppSettingClient) mutate(ctx context.Context, m *AppSettingMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AppSettingCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AppSettingUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AppSettingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AppSettingDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AppSetting mutation op: %q", m.Op())
	}
}

// DDNSIPSourceClient is a client for the DDNSIPSource schema.
type DDNSIPSourceClient struct {
	config
}

// NewDDNSIPSourceClient returns a client for the DDNSIPSource from the given config.
func NewDDNSIPSourceClient(c config) *DDNSIPSourceClient {
	return &DDNSIPSourceClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `ddnsipsource.Hooks(f(g(h())))`.
func (c *DDNSIPSourceClient) Use(hooks ...Hook) {
	c.hooks.DDNSIPSource = append(c.hooks.DDNSIPSource, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `ddnsipsource.Intercept(f(g(h())))`.
func (c *DDNSIPSourceClient) Intercept(interceptors ...Interceptor) {
	c.inters.DDNSIPSource = append(c.inters.DDNSIPSource, interceptors...)
}

// Create returns a builder for creating a DDNSIPSource entity.
func (c *DDNSIPSourceClient) Create() *DDNSIPSourceCreate {
	mutation := newDDNSIPSourceMutation(c.config, OpCreate)
	return &DDNSIPSourceCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DDNSIPSource entities.
func (c *DDNSIPSourceClient) CreateBulk(builders ...*DDNSIPSourceCreate) *DDNSIPSourceCreateBulk {
	return &DDNSIPSourceCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DDNSIPSourceClient) MapCreateBulk(slice any, setFunc func(*DDNSIPSourceCreate, int)) *DDNSIPSourceCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DDNSIPSourceCreateBulk{err: fmt.Errorf("calling to DDNSIPSourceClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DDNSIPSourceCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DDNSIPSourceCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DDNSIPSource.
func (c *DDNSIPSourceClient) Update() *DDNSIPSourceUpdate {
	mutation := newDDNSIPSourceMutation(c.config, OpUpdate)
	return &DDNSIPSourceUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DDNSIPSourceClient) UpdateOne(_m *DDNSIPSource) *DDNSIPSourceUpdateOne {
	mutation := newDDNSIPSourceMutation(c.config, OpUpdateOne, withDDNSIPSource(_m))
	return &DDNSIPSourceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DDNSIPSourceClient) UpdateOneID(id int) *DDNSIPSourceUpdateOne {
	mutation := newDDNSIPSourceMutation(c.config, OpUpdateOne, withDDNSIPSourceID(id))
	return &DDNSIPSourceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DDNSIPSource.
func (c *DDNSIPSourceClient) Delete() *DDNSIPSourceDelete {
	mutation := newDDNSIPSourceMutation(c.config, OpDelete)
	return &DDNSIPSourceDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DDNSIPSourceClient) DeleteOne(_m *DDNSIPSource) *DDNSIPSourceDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DDNSIPSourceClient) DeleteOneID(id int) *DDNSIPSourceDeleteOne {
	builder := c.Delete().Where(ddnsipsource.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DDNSIPSourceDeleteOne{builder}
}

// Query returns a query builder for DDNSIPSource.
func (c *DDNSIPSourceClient) Query() *DDNSIPSourceQuery {
	return &DDNSIPSourceQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDDNSIPSource},
		inters: c.Interceptors(),
	}
}

// Get returns a DDNSIPSource entity by its id.
func (c *DDNSIPSourceClient) Get(ctx context.Context, id int) (*DDNSIPSource, error) {
	return c.Query().Where(ddnsipsource.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DDNSIPSourceClient) GetX(ctx context.Context, id int) *DDNSIPSource {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *DDNSIPSourceClient) Hooks() []Hook {
	return c.hooks.DDNSIPSource
}

// Interceptors returns the client interceptors.
func (c *DDNSIPSourceClient) Interceptors() []Interceptor {
	return c.inters.DDNSIPSource
}

func (c *DDNSIPSourceClient) mutate(ctx context.Context, m *DDNSIPSourceMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DDNSIPSourceCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DDNSIPSourceUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DDNSIPSourceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DDNSIPSourceDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown DDNSIPSource mutation op: %q", m.Op())
	}
}

// DDNSRecordClient is a client for the DDNSRecord schema.
type DDNSRecordClient struct {
	config
}

// NewDDNSRecordClient returns a client for the DDNSRecord from the given config.
func NewDDNSRecordClient(c config) *DDNSRecordClient {
	return &DDNSRecordClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `ddnsrecord.Hooks(f(g(h())))`.
func (c *DDNSRecordClient) Use(hooks ...Hook) {
	c.hooks.DDNSRecord = append(c.hooks.DDNSRecord, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `ddnsrecord.Intercept(f(g(h())))`.
func (c *DDNSRecordClient) Intercept(interceptors ...Interceptor) {
	c.inters.DDNSRecord = append(c.inters.DDNSRecord, interceptors...)
}

// Create returns a builder for creating a DDNSRecord entity.
func (c *DDNSRecordClient) Create() *DDNSRecordCreate {
	mutation := newDDNSRecordMutation(c.config, OpCreate)
	return &DDNSRecordCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DDNSRecord entities.
func (c *DDNSRecordClient) CreateBulk(builders ...*DDNSRecordCreate) *DDNSRecordCreateBulk {
	return &DDNSRecordCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DDNSRecordClient) MapCreateBulk(slice any, setFunc func(*DDNSRecordCreate, int)) *DDNSRecordCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DDNSRecordCreateBulk{err: fmt.Errorf("calling to DDNSRecordClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DDNSRecordCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DDNSRecordCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DDNSRecord.
func (c *DDNSRecordClient) Update() *DDNSRecordUpdate {
	mutation := newDDNSRecordMutation(c.config, OpUpdate)
	return &DDNSRecordUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DDNSRecordClient) UpdateOne(_m *DDNSRecord) *DDNSRecordUpdateOne {
	mutation := newDDNSRecordMutation(c.config, OpUpdateOne, withDDNSRecord(_m))
	return &DDNSRecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DDNSRecordClient) UpdateOneID(id int) *DDNSRecordUpdateOne {
	mutation := newDDNSRecordMutation(c.config, OpUpdateOne, withDDNSRecordID(id))
	return &DDNSRecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DDNSRecord.
func (c *DDNSRecordClient) Delete() *DDNSRecordDelete {
	mutation := newDDNSRecordMutation(c.config, OpDelete)
	return &DDNSRecordDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DDNSRecordClient) DeleteOne(_m *DDNSRecord) *DDNSRecordDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DDNSRecordClient) DeleteOneID(id int) *DDNSRecordDeleteOne {
	builder := c.Delete().Where(ddnsrecord.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DDNSRecordDeleteOne{builder}
}

// Query returns a query builder for DDNSRecord.
func (c *DDNSRecordClient) Query() *DDNSRecordQuery {
	return &DDNSRecordQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDDNSRecord},
		inters: c.Interceptors(),
	}
}

// Get returns a DDNSRecord entity by its id.
func (c *DDNSRecordClient) Get(ctx context.Context, id int) (*DDNSRecord, error) {
	return c.Query().Where(ddnsrecord.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DDNSRecordClient) GetX(ctx context.Context, id int) *DDNSRecord {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *DDNSRecordClient) Hooks() []Hook {
	return c.hooks.DDNSRecord
}

// Interceptors returns the client interceptors.
func (c *DDNSRecordClient) Interceptors() []Interceptor {
	return c.inters.DDNSRecord
}

func (c *DDNSRecordClient) mutate(ctx context.Context, m *DDNSRecordMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DDNSRecordCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DDNSRecordUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DDNSRecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DDNSRecordDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown DDNSRecord mutation op: %q", m.Op())
	}
}

// DDNSSettingClient is a client for the DDNSSetting schema.
type DDNSSettingClient struct {
	config
}

// NewDDNSSettingClient returns a client for the DDNSSetting from the given config.
func NewDDNSSettingClient(c config) *DDNSSettingClient {
	return &DDNSSettingClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `ddnssetting.Hooks(f(g(h())))`.
func (c *DDNSSettingClient) Use(hooks ...Hook) {
	c.hooks.DDNSSetting = append(c.hooks.DDNSSetting, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `ddnssetting.Intercept(f(g(h())))`.
func (c *DDNSSettingClient) Intercept(interceptors ...Interceptor) {
	c.inters.DDNSSetting = append(c.inters.DDNSSetting, interceptors...)
}

// Create returns a builder for creating a DDNSSetting entity.
func (c *DDNSSettingClient) Create() *DDNSSettingCreate {
	mutation := newDDNSSettingMutation(c.config, OpCreate)
	return &DDNSSettingCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DDNSSetting entities.
func (c *DDNSSettingClient) CreateBulk(builders ...*DDNSSettingCreate) *DDNSSettingCreateBulk {
	return &DDNSSettingCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DDNSSettingClient) MapCreateBulk(slice any, setFunc func(*DDNSSettingCreate, int)) *DDNSSettingCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DDNSSettingCreateBulk{err: fmt.Errorf("calling to DDNSSettingClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DDNSSettingCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DDNSSettingCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DDNSSetting.
func (c *DDNSSettingClient) Update() *DDNSSettingUpdate {
	mutation := newDDNSSettingMutation(c.config, OpUpdate)
	return &DDNSSettingUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DDNSSettingClient) UpdateOne(_m *DDNSSetting) *DDNSSettingUpdateOne {
	mutation := newDDNSSettingMutation(c.config, OpUpdateOne, withDDNSSetting(_m))
	return &DDNSSettingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DDNSSettingClient) UpdateOneID(id int) *DDNSSettingUpdateOne {
	mutation := newDDNSSettingMutation(c.config, OpUpdateOne, withDDNSSettingID(id))
	return &DDNSSettingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DDNSSetting.
func (c *DDNSSettingClient) Delete() *DDNSSettingDelete {
	mutation := newDDNSSettingMutation(c.config, OpDelete)
	return &DDNSSettingDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DDNSSettingClient) DeleteOne(_m *DDNSSetting) *DDNSSettingDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DDNSSettingClient) DeleteOneID(id int) *DDNSSettingDeleteOne {
	builder := c.Delete().Where(ddnssetting.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DDNSSettingDeleteOne{builder}
}

// Query returns a query builder for DDNSSetting.
func (c *DDNSSettingClient) Query() *DDNSSettingQuery {
	return &DDNSSettingQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDDNSSetting},
		inters: c.Interceptors(),
	}
}

// Get returns a DDNSSetting entity by its id.
func (c *DDNSSettingClient) Get(ctx context.Context, id int) (*DDNSSetting, error) {
	return c.Query().Where(ddnssetting.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DDNSSettingClient) GetX(ctx context.Context, id int) *DDNSSetting {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *DDNSSettingClient) Hooks() []Hook {
	return c.hooks.DDNSSetting
}

// Interceptors returns the client interceptors.
func (c *DDNSSettingClient) Interceptors() []Interceptor {
	return c.inters.DDNSSetting
}

func (c *DDNSSettingClient) mutate(ctx context.Context, m *DDNSSettingMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DDNSSettingCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DDNSSettingUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DDNSSettingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DDNSSettingDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown DDNSSetting mutation op: %q", m.Op())
	}
}

// MCPTokenClient is a client for the MCPToken schema.
type MCPTokenClient struct {
	config
}

// NewMCPTokenClient returns a client for the MCPToken from the given config.
func NewMCPTokenClient(c config) *MCPTokenClient {
	return &MCPTokenClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `mcptoken.Hooks(f(g(h())))`.
func (c *MCPTokenClient) Use(hooks ...Hook) {
	c.hooks.MCPToken = append(c.hooks.MCPToken, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `mcptoken.Intercept(f(g(h())))`.
func (c *MCPTokenClient) Intercept(interceptors ...Interceptor) {
	c.inters.MCPToken = append(c.inters.MCPToken, interceptors...)
}

// Create returns a builder for creating a MCPToken entity.
func (c *MCPTokenClient) Create() *MCPTokenCreate {
	mutation := newMCPTokenMutation(c.config, OpCreate)
	return &MCPTokenCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MCPToken entities.
func (c *MCPTokenClient) CreateBulk(builders ...*MCPTokenCreate) *MCPTokenCreateBulk {
	return &MCPTokenCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MCPTokenClient) MapCreateBulk(slice any, setFunc func(*MCPTokenCreate, int)) *MCPTokenCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MCPTokenCreateBulk{err: fmt.Errorf("calling to MCPTokenClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MCPTokenCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MCPTokenCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MCPToken.
func (c *MCPTokenClient) Update() *MCPTokenUpdate {
	mutation := newMCPTokenMutation(c.config, OpUpdate)
	return &MCPTokenUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MCPTokenClient) UpdateOne(_m *MCPToken) *MCPTokenUpdateOne {
	mutation := newMCPTokenMutation(c.config, OpUpdateOne, withMCPToken(_m))
	return &MCPTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MCPTokenClient) UpdateOneID(id int) *MCPTokenUpdateOne {
	mutation := newMCPTokenMutation(c.config, OpUpdateOne, withMCPTokenID(id))
	return &MCPTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MCPToken.
func (c *MCPTokenClient) Delete() *MCPTokenDelete {
	mutation := newMCPTokenMutation(c.config, OpDelete)
	return &MCPTokenDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MCPTokenClient) DeleteOne(_m *MCPToken) *MCPTokenDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MCPTokenClient) DeleteOneID(id int) *MCPTokenDeleteOne {
	builder := c.Delete().Where(mcptoken.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MCPTokenDeleteOne{builder}
}

// Query returns a query builder for MCPToken.
func (c *MCPTokenClient) Query() *MCPTokenQuery {
	return &MCPTokenQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMCPToken},
		inters: c.Interceptors(),
	}
}

// Get returns a MCPToken entity by its id.
func (c *MCPTokenClient) Get(ctx context.Context, id int) (*MCPToken, error) {
	return c.Query().Where(mcptoken.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MCPTokenClient) GetX(ctx context.Context, id int) *MCPToken {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *MCPTokenClient) Hooks() []Hook {
	return c.hooks.MCPToken
}

// Interceptors returns the client interceptors.
func (c *MCPTokenClient) Interceptors() []Interceptor {
	return c.inters.MCPToken
}

func (c *MCPTokenClient) mutate(ctx context.Context, m *MCPTokenMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MCPTokenCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MCPTokenUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MCPTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MCPTokenDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown MCPToken mutation op: %q", m.Op())
	}
}

// OAuthSessionClient is a client for the OAuthSession schema.
type OAuthSessionClient struct {
	config
}

// NewOAuthSessionClient returns a client for the OAuthSession from the given config.
func NewOAuthSessionClient(c config) *OAuthSessionClient {
	return &OAuthSessionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `oauthsession.Hooks(f(g(h())))`.
func (c *OAuthSessionClient) Use(hooks ...Hook) {
	c.hooks.OAuthSession = append(c.hooks.OAuthSession, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `oauthsession.Intercept(f(g(h())))`.
func (c *OAuthSessionClient) Intercept(interceptors ...Interceptor) {
	c.inters.OAuthSession = append(c.inters.OAuthSession, interceptors...)
}

// Create returns a builder for creating a OAuthSession entity.
func (c *OAuthSessionClient) Create() *OAuthSessionCreate {
	mutation := newOAuthSessionMutation(c.config, OpCreate)
	return &OAuthSessionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of OAuthSession entities.
func (c *OAuthSessionClient) CreateBulk(builders ...*OAuthSessionCreate) *OAuthSessionCreateBulk {
	return &OAuthSessionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *OAuthSessionClient) MapCreateBulk(slice any, setFunc func(*OAuthSessionCreate, int)) *OAuthSessionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &OAuthSessionCreateBulk{err: fmt.Errorf("calling to OAuthSessionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*OAuthSessionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &OAuthSessionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for OAuthSession.
func (c *OAuthSessionClient) Update() *OAuthSessionUpdate {
	mutation := newOAuthSessionMutation(c.config, OpUpdate)
	return &OAuthSessionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *OAuthSessionClient) UpdateOne(_m *OAuthSession) *OAuthSessionUpdateOne {
	mutation := newOAuthSessionMutation(c.config, OpUpdateOne, withOAuthSession(_m))
	return &OAuthSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *OAuthSessionClient) UpdateOneID(id int) *OAuthSessionUpdateOne {
	mutation := newOAuthSessionMutation(c.config, OpUpdateOne, withOAuthSessionID(id))
	return &OAuthSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for OAuthSession.
func (c *OAuthSessionClient) Delete() *OAuthSessionDelete {
	mutation := newOAuthSessionMutation(c.config, OpDelete)
	return &OAuthSessionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *OAuthSessionClient) DeleteOne(_m *OAuthSession) *OAuthSessionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *OAuthSessionClient) DeleteOneID(id int) *OAuthSessionDeleteOne {
	builder := c.Delete().Where(oauthsession.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &OAuthSessionDeleteOne{builder}
}

// Query returns a query builder for OAuthSession.
func (c *OAuthSessionClient) Query() *OAuthSessionQuery {
	return &OAuthSessionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeOAuthSession},
		inters: c.Interceptors(),
	}
}

// Get returns a OAuthSession entity by its id.
func (c *OAuthSessionClient) Get(ctx context.Context, id int) (*OAuthSession, error) {
	return c.Query().Where(oauthsession.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *OAuthSessionClient) GetX(ctx context.Context, id int) *OAuthSession {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *OAuthSessionClient) Hooks() []Hook {
	return c.hooks.OAuthSession
}

// Interceptors returns the client interceptors.
func (c *OAuthSessionClient) Interceptors() []Interceptor {
	return c.inters.OAuthSession
}

func (c *OAuthSessionClient) mutate(ctx context.Context, m *OAuthSessionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&OAuthSessionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&OAuthSessionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&OAuthSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&OAuthSessionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown OAuthSession mutation op: %q", m.Op())
	}
}

// OAuthStateClient is a client for the OAuthState schema.
type OAuthStateClient struct {
	config
}

// NewOAuthStateClient returns a client for the OAuthState from the given config.
func NewOAuthStateClient(c config) *OAuthStateClient {
	return &OAuthStateClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `oauthstate.Hooks(f(g(h())))`.
func (c *OAuthStateClient) Use(hooks ...Hook) {
	c.hooks.OAuthState = append(c.hooks.OAuthState, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `oauthstate.Intercept(f(g(h())))`.
func (c *OAuthStateClient) Intercept(interceptors ...Interceptor) {
	c.inters.OAuthState = append(c.inters.OAuthState, interceptors...)
}

// Create returns a builder for creating a OAuthState entity.
func (c *OAuthStateClient) Create() *OAuthStateCreate {
	mutation := newOAuthStateMutation(c.config, OpCreate)
	return &OAuthStateCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of OAuthState entities.
func (c *OAuthStateClient) CreateBulk(builders ...*OAuthStateCreate) *OAuthStateCreateBulk {
	return &OAuthStateCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *OAuthStateClient) MapCreateBulk(slice any, setFunc func(*OAuthStateCreate, int)) *OAuthStateCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &OAuthStateCreateBulk{err: fmt.Errorf("calling to OAuthStateClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*OAuthStateCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &OAuthStateCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for OAuthState.
func (c *OAuthStateClient) Update() *OAuthStateUpdate {
	mutation := newOAuthStateMutation(c.config, OpUpdate)
	return &OAuthStateUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *OAuthStateClient) UpdateOne(_m *OAuthState) *OAuthStateUpdateOne {
	mutation := newOAuthStateMutation(c.config, OpUpdateOne, withOAuthState(_m))
	return &OAuthStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *OAuthStateClient) UpdateOneID(id int) *OAuthStateUpdateOne {
	mutation := newOAuthStateMutation(c.config, OpUpdateOne, withOAuthStateID(id))
	return &OAuthStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for OAuthState.
func (c *OAuthStateClient) Delete() *OAuthStateDelete {
	mutation := newOAuthStateMutation(c.config, OpDelete)
	return &OAuthStateDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *OAuthStateClient) DeleteOne(_m *OAuthState) *OAuthStateDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *OAuthStateClient) DeleteOneID(id int) *OAuthStateDeleteOne {
	builder := c.Delete().Where(oauthstate.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &OAuthStateDeleteOne{builder}
}

// Query returns a query builder for OAuthState.
func (c *OAuthStateClient) Query() *OAuthStateQuery {
	return &OAuthStateQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeOAuthState},
		inters: c.Interceptors(),
	}
}

// Get returns a OAuthState entity by its id.
func (c *OAuthStateClient) Get(ctx context.Context, id int) (*OAuthState, error) {
	return c.Query().Where(oauthstate.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *OAuthStateClient) GetX(ctx context.Context, id int) *OAuthState {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *OAuthStateClient) Hooks() []Hook {
	return c.hooks.OAuthState
}

// Interceptors returns the client interceptors.
func (c *OAuthStateClient) Interceptors() []Interceptor {
	return c.inters.OAuthState
}

func (c *OAuthStateClient) mutate(ctx context.Context, m *OAuthStateMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&OAuthStateCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&OAuthStateUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&OAuthStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&OAuthStateDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown OAuthState mutation op: %q", m.Op())
	}
}

// S3WebDAVSettingClient is a client for the S3WebDAVSetting schema.
type S3WebDAVSettingClient struct {
	config
}

// NewS3WebDAVSettingClient returns a client for the S3WebDAVSetting from the given config.
func NewS3WebDAVSettingClient(c config) *S3WebDAVSettingClient {
	return &S3WebDAVSettingClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `s3webdavsetting.Hooks(f(g(h())))`.
func (c *S3WebDAVSettingClient) Use(hooks ...Hook) {
	c.hooks.S3WebDAVSetting = append(c.hooks.S3WebDAVSetting, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `s3webdavsetting.Intercept(f(g(h())))`.
func (c *S3WebDAVSettingClient) Intercept(interceptors ...Interceptor) {
	c.inters.S3WebDAVSetting = append(c.inters.S3WebDAVSetting, interceptors...)
}

// Create returns a builder for creating a S3WebDAVSetting entity.
func (c *S3WebDAVSettingClient) Create() *S3WebDAVSettingCreate {
	mutation := newS3WebDAVSettingMutation(c.config, OpCreate)
	return &S3WebDAVSettingCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of S3WebDAVSetting entities.
func (c *S3WebDAVSettingClient) CreateBulk(builders ...*S3WebDAVSettingCreate) *S3WebDAVSettingCreateBulk {
	return &S3WebDAVSettingCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *S3WebDAVSettingClient) MapCreateBulk(slice any, setFunc func(*S3WebDAVSettingCreate, int)) *S3WebDAVSettingCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &S3WebDAVSettingCreateBulk{err: fmt.Errorf("calling to S3WebDAVSettingClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*S3WebDAVSettingCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &S3WebDAVSettingCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for S3WebDAVSetting.
func (c *S3WebDAVSettingClient) Update() *S3WebDAVSettingUpdate {
	mutation := newS3WebDAVSettingMutation(c.config, OpUpdate)
	return &S3WebDAVSettingUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *S3WebDAVSettingClient) UpdateOne(_m *S3WebDAVSetting) *S3WebDAVSettingUpdateOne {
	mutation := newS3WebDAVSettingMutation(c.config, OpUpdateOne, withS3WebDAVSetting(_m))
	return &S3WebDAVSettingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *S3WebDAVSettingClient) UpdateOneID(id int) *S3WebDAVSettingUpdateOne {
	mutation := newS3WebDAVSettingMutation(c.config, OpUpdateOne, withS3WebDAVSettingID(id))
	return &S3WebDAVSettingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for S3WebDAVSetting.
func (c *S3WebDAVSettingClient) Delete() *S3WebDAVSettingDelete {
	mutation := newS3WebDAVSettingMutation(c.config, OpDelete)
	return &S3WebDAVSettingDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *S3WebDAVSettingClient) DeleteOne(_m *S3WebDAVSetting) *S3WebDAVSettingDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *S3WebDAVSettingClient) DeleteOneID(id int) *S3WebDAVSettingDeleteOne {
	builder := c.Delete().Where(s3webdavsetting.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &S3WebDAVSettingDeleteOne{builder}
}

// Query returns a query builder for S3WebDAVSetting.
func (c *S3WebDAVSettingClient) Query() *S3WebDAVSettingQuery {
	return &S3WebDAVSettingQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeS3WebDAVSetting},
		inters: c.Interceptors(),
	}
}

// Get returns a S3WebDAVSetting entity by its id.
func (c *S3WebDAVSettingClient) Get(ctx context.Context, id int) (*S3WebDAVSetting, error) {
	return c.Query().Where(s3webdavsetting.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *S3WebDAVSettingClient) GetX(ctx context.Context, id int) *S3WebDAVSetting {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *S3WebDAVSettingClient) Hooks() []Hook {
	return c.hooks.S3WebDAVSetting
}

// Interceptors returns the client interceptors.
func (c *S3WebDAVSettingClient) Interceptors() []Interceptor {
	return c.inters.S3WebDAVSetting
}

func (c *S3WebDAVSettingClient) mutate(ctx context.Context, m *S3WebDAVSettingMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&S3WebDAVSettingCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&S3WebDAVSettingUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&S3WebDAVSettingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&S3WebDAVSettingDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown S3WebDAVSetting mutation op: %q", m.Op())
	}
}

// TunnelManagementClient is a client for the TunnelManagement schema.
type TunnelManagementClient struct {
	config
}

// NewTunnelManagementClient returns a client for the TunnelManagement from the given config.
func NewTunnelManagementClient(c config) *TunnelManagementClient {
	return &TunnelManagementClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `tunnelmanagement.Hooks(f(g(h())))`.
func (c *TunnelManagementClient) Use(hooks ...Hook) {
	c.hooks.TunnelManagement = append(c.hooks.TunnelManagement, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `tunnelmanagement.Intercept(f(g(h())))`.
func (c *TunnelManagementClient) Intercept(interceptors ...Interceptor) {
	c.inters.TunnelManagement = append(c.inters.TunnelManagement, interceptors...)
}

// Create returns a builder for creating a TunnelManagement entity.
func (c *TunnelManagementClient) Create() *TunnelManagementCreate {
	mutation := newTunnelManagementMutation(c.config, OpCreate)
	return &TunnelManagementCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TunnelManagement entities.
func (c *TunnelManagementClient) CreateBulk(builders ...*TunnelManagementCreate) *TunnelManagementCreateBulk {
	return &TunnelManagementCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TunnelManagementClient) MapCreateBulk(slice any, setFunc func(*TunnelManagementCreate, int)) *TunnelManagementCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TunnelManagementCreateBulk{err: fmt.Errorf("calling to TunnelManagementClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TunnelManagementCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TunnelManagementCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TunnelManagement.
func (c *TunnelManagementClient) Update() *TunnelManagementUpdate {
	mutation := newTunnelManagementMutation(c.config, OpUpdate)
	return &TunnelManagementUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TunnelManagementClient) UpdateOne(_m *TunnelManagement) *TunnelManagementUpdateOne {
	mutation := newTunnelManagementMutation(c.config, OpUpdateOne, withTunnelManagement(_m))
	return &TunnelManagementUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TunnelManagementClient) UpdateOneID(id int) *TunnelManagementUpdateOne {
	mutation := newTunnelManagementMutation(c.config, OpUpdateOne, withTunnelManagementID(id))
	return &TunnelManagementUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TunnelManagement.
func (c *TunnelManagementClient) Delete() *TunnelManagementDelete {
	mutation := newTunnelManagementMutation(c.config, OpDelete)
	return &TunnelManagementDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TunnelManagementClient) DeleteOne(_m *TunnelManagement) *TunnelManagementDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TunnelManagementClient) DeleteOneID(id int) *TunnelManagementDeleteOne {
	builder := c.Delete().Where(tunnelmanagement.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TunnelManagementDeleteOne{builder}
}

// Query returns a query builder for TunnelManagement.
func (c *TunnelManagementClient) Query() *TunnelManagementQuery {
	return &TunnelManagementQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTunnelManagement},
		inters: c.Interceptors(),
	}
}

// Get returns a TunnelManagement entity by its id.
func (c *TunnelManagementClient) Get(ctx context.Context, id int) (*TunnelManagement, error) {
	return c.Query().Where(tunnelmanagement.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TunnelManagementClient) GetX(ctx context.Context, id int) *TunnelManagement {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TunnelManagementClient) Hooks() []Hook {
	return c.hooks.TunnelManagement
}

// Interceptors returns the client interceptors.
func (c *TunnelManagementClient) Interceptors() []Interceptor {
	return c.inters.TunnelManagement
}

func (c *TunnelManagementClient) mutate(ctx context.Context, m *TunnelManagementMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TunnelManagementCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TunnelManagementUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TunnelManagementUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TunnelManagementDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown TunnelManagement mutation op: %q", m.Op())
	}
}

// TunnelProfileClient is a client for the TunnelProfile schema.
type TunnelProfileClient struct {
	config
}

// NewTunnelProfileClient returns a client for the TunnelProfile from the given config.
func NewTunnelProfileClient(c config) *TunnelProfileClient {
	return &TunnelProfileClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `tunnelprofile.Hooks(f(g(h())))`.
func (c *TunnelProfileClient) Use(hooks ...Hook) {
	c.hooks.TunnelProfile = append(c.hooks.TunnelProfile, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `tunnelprofile.Intercept(f(g(h())))`.
func (c *TunnelProfileClient) Intercept(interceptors ...Interceptor) {
	c.inters.TunnelProfile = append(c.inters.TunnelProfile, interceptors...)
}

// Create returns a builder for creating a TunnelProfile entity.
func (c *TunnelProfileClient) Create() *TunnelProfileCreate {
	mutation := newTunnelProfileMutation(c.config, OpCreate)
	return &TunnelProfileCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TunnelProfile entities.
func (c *TunnelProfileClient) CreateBulk(builders ...*TunnelProfileCreate) *TunnelProfileCreateBulk {
	return &TunnelProfileCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TunnelProfileClient) MapCreateBulk(slice any, setFunc func(*TunnelProfileCreate, int)) *TunnelProfileCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TunnelProfileCreateBulk{err: fmt.Errorf("calling to TunnelProfileClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TunnelProfileCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TunnelProfileCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TunnelProfile.
func (c *TunnelProfileClient) Update() *TunnelProfileUpdate {
	mutation := newTunnelProfileMutation(c.config, OpUpdate)
	return &TunnelProfileUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TunnelProfileClient) UpdateOne(_m *TunnelProfile) *TunnelProfileUpdateOne {
	mutation := newTunnelProfileMutation(c.config, OpUpdateOne, withTunnelProfile(_m))
	return &TunnelProfileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TunnelProfileClient) UpdateOneID(id int) *TunnelProfileUpdateOne {
	mutation := newTunnelProfileMutation(c.config, OpUpdateOne, withTunnelProfileID(id))
	return &TunnelProfileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TunnelProfile.
func (c *TunnelProfileClient) Delete() *TunnelProfileDelete {
	mutation := newTunnelProfileMutation(c.config, OpDelete)
	return &TunnelProfileDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TunnelProfileClient) DeleteOne(_m *TunnelProfile) *TunnelProfileDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TunnelProfileClient) DeleteOneID(id int) *TunnelProfileDeleteOne {
	builder := c.Delete().Where(tunnelprofile.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TunnelProfileDeleteOne{builder}
}

// Query returns a query builder for TunnelProfile.
func (c *TunnelProfileClient) Query() *TunnelProfileQuery {
	return &TunnelProfileQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTunnelProfile},
		inters: c.Interceptors(),
	}
}

// Get returns a TunnelProfile entity by its id.
func (c *TunnelProfileClient) Get(ctx context.Context, id int) (*TunnelProfile, error) {
	return c.Query().Where(tunnelprofile.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TunnelProfileClient) GetX(ctx context.Context, id int) *TunnelProfile {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TunnelProfileClient) Hooks() []Hook {
	return c.hooks.TunnelProfile
}

// Interceptors returns the client interceptors.
func (c *TunnelProfileClient) Interceptors() []Interceptor {
	return c.inters.TunnelProfile
}

func (c *TunnelProfileClient) mutate(ctx context.Context, m *TunnelProfileMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TunnelProfileCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TunnelProfileUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TunnelProfileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TunnelProfileDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown TunnelProfile mutation op: %q", m.Op())
	}
}

// TunnelTokenClient is a client for the TunnelToken schema.
type TunnelTokenClient struct {
	config
}

// NewTunnelTokenClient returns a client for the TunnelToken from the given config.
func NewTunnelTokenClient(c config) *TunnelTokenClient {
	return &TunnelTokenClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `tunneltoken.Hooks(f(g(h())))`.
func (c *TunnelTokenClient) Use(hooks ...Hook) {
	c.hooks.TunnelToken = append(c.hooks.TunnelToken, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `tunneltoken.Intercept(f(g(h())))`.
func (c *TunnelTokenClient) Intercept(interceptors ...Interceptor) {
	c.inters.TunnelToken = append(c.inters.TunnelToken, interceptors...)
}

// Create returns a builder for creating a TunnelToken entity.
func (c *TunnelTokenClient) Create() *TunnelTokenCreate {
	mutation := newTunnelTokenMutation(c.config, OpCreate)
	return &TunnelTokenCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TunnelToken entities.
func (c *TunnelTokenClient) CreateBulk(builders ...*TunnelTokenCreate) *TunnelTokenCreateBulk {
	return &TunnelTokenCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TunnelTokenClient) MapCreateBulk(slice any, setFunc func(*TunnelTokenCreate, int)) *TunnelTokenCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TunnelTokenCreateBulk{err: fmt.Errorf("calling to TunnelTokenClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TunnelTokenCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TunnelTokenCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TunnelToken.
func (c *TunnelTokenClient) Update() *TunnelTokenUpdate {
	mutation := newTunnelTokenMutation(c.config, OpUpdate)
	return &TunnelTokenUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TunnelTokenClient) UpdateOne(_m *TunnelToken) *TunnelTokenUpdateOne {
	mutation := newTunnelTokenMutation(c.config, OpUpdateOne, withTunnelToken(_m))
	return &TunnelTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TunnelTokenClient) UpdateOneID(id int) *TunnelTokenUpdateOne {
	mutation := newTunnelTokenMutation(c.config, OpUpdateOne, withTunnelTokenID(id))
	return &TunnelTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TunnelToken.
func (c *TunnelTokenClient) Delete() *TunnelTokenDelete {
	mutation := newTunnelTokenMutation(c.config, OpDelete)
	return &TunnelTokenDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TunnelTokenClient) DeleteOne(_m *TunnelToken) *TunnelTokenDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TunnelTokenClient) DeleteOneID(id int) *TunnelTokenDeleteOne {
	builder := c.Delete().Where(tunneltoken.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TunnelTokenDeleteOne{builder}
}

// Query returns a query builder for TunnelToken.
func (c *TunnelTokenClient) Query() *TunnelTokenQuery {
	return &TunnelTokenQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTunnelToken},
		inters: c.Interceptors(),
	}
}

// Get returns a TunnelToken entity by its id.
func (c *TunnelTokenClient) Get(ctx context.Context, id int) (*TunnelToken, error) {
	return c.Query().Where(tunneltoken.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TunnelTokenClient) GetX(ctx context.Context, id int) *TunnelToken {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TunnelTokenClient) Hooks() []Hook {
	return c.hooks.TunnelToken
}

// Interceptors returns the client interceptors.
func (c *TunnelTokenClient) Interceptors() []Interceptor {
	return c.inters.TunnelToken
}

func (c *TunnelTokenClient) mutate(ctx context.Context, m *TunnelTokenMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TunnelTokenCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TunnelTokenUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TunnelTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TunnelTokenDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown TunnelToken mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		AppSetting, DDNSIPSource, DDNSRecord, DDNSSetting, MCPToken, OAuthSession,
		OAuthState, S3WebDAVSetting, TunnelManagement, TunnelProfile,
		TunnelToken []ent.Hook
	}
	inters struct {
		AppSetting, DDNSIPSource, DDNSRecord, DDNSSetting, MCPToken, OAuthSession,
		OAuthState, S3WebDAVSetting, TunnelManagement, TunnelProfile,
		TunnelToken []ent.Interceptor
	}
)
