// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cfui/internal/persist/ent/appconfig"
	"cfui/internal/persist/ent/mcptoken"
	"cfui/internal/persist/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	appconfigFields := schema.AppConfig{}.Fields()
	_ = appconfigFields
	// appconfigDescKey is the schema descriptor for key field.
	appconfigDescKey := appconfigFields[0].Descriptor()
	// appconfig.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	appconfig.KeyValidator = appconfigDescKey.Validators[0].(func(string) error)
	// appconfigDescPayload is the schema descriptor for payload field.
	appconfigDescPayload := appconfigFields[1].Descriptor()
	// appconfig.PayloadValidator is a validator for the "payload" field. It is called by the builders before save.
	appconfig.PayloadValidator = appconfigDescPayload.Validators[0].(func([]byte) error)
	// appconfigDescCreatedAt is the schema descriptor for created_at field.
	appconfigDescCreatedAt := appconfigFields[2].Descriptor()
	// appconfig.DefaultCreatedAt holds the default value on creation for the created_at field.
	appconfig.DefaultCreatedAt = appconfigDescCreatedAt.Default.(func() time.Time)
	// appconfigDescUpdatedAt is the schema descriptor for updated_at field.
	appconfigDescUpdatedAt := appconfigFields[3].Descriptor()
	// appconfig.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	appconfig.DefaultUpdatedAt = appconfigDescUpdatedAt.Default.(func() time.Time)
	// appconfig.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	appconfig.UpdateDefaultUpdatedAt = appconfigDescUpdatedAt.UpdateDefault.(func() time.Time)
	mcptokenFields := schema.MCPToken{}.Fields()
	_ = mcptokenFields
	// mcptokenDescTokenID is the schema descriptor for token_id field.
	mcptokenDescTokenID := mcptokenFields[0].Descriptor()
	// mcptoken.TokenIDValidator is a validator for the "token_id" field. It is called by the builders before save.
	mcptoken.TokenIDValidator = mcptokenDescTokenID.Validators[0].(func(string) error)
	// mcptokenDescName is the schema descriptor for name field.
	mcptokenDescName := mcptokenFields[1].Descriptor()
	// mcptoken.NameValidator is a validator for the "name" field. It is called by the builders before save.
	mcptoken.NameValidator = mcptokenDescName.Validators[0].(func(string) error)
	// mcptokenDescTokenHash is the schema descriptor for token_hash field.
	mcptokenDescTokenHash := mcptokenFields[2].Descriptor()
	// mcptoken.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	mcptoken.TokenHashValidator = mcptokenDescTokenHash.Validators[0].(func(string) error)
	// mcptokenDescMasked is the schema descriptor for masked field.
	mcptokenDescMasked := mcptokenFields[3].Descriptor()
	// mcptoken.MaskedValidator is a validator for the "masked" field. It is called by the builders before save.
	mcptoken.MaskedValidator = mcptokenDescMasked.Validators[0].(func(string) error)
	// mcptokenDescCreatedAt is the schema descriptor for created_at field.
	mcptokenDescCreatedAt := mcptokenFields[4].Descriptor()
	// mcptoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	mcptoken.DefaultCreatedAt = mcptokenDescCreatedAt.Default.(func() time.Time)
}
