// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cfui/internal/persist/ent/s3webdavsetting"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// S3WebDAVSetting is the model entity for the S3WebDAVSetting schema.
type S3WebDAVSetting struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Key holds the value of the "key" field.
	Key string `json:"key,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder int `json:"sort_order,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// WebdavEnabled holds the value of the "webdav_enabled" field.
	WebdavEnabled bool `json:"webdav_enabled,omitempty"`
	// WebdavAuthEnabled holds the value of the "webdav_auth_enabled" field.
	WebdavAuthEnabled bool `json:"webdav_auth_enabled,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// EndpointURL holds the value of the "endpoint_url" field.
	EndpointURL string `json:"endpoint_url,omitempty"`
	// Region holds the value of the "region" field.
	Region string `json:"region,omitempty"`
	// PathStyle holds the value of the "path_style" field.
	PathStyle bool `json:"path_style,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID string `json:"account_id,omitempty"`
	// BucketName holds the value of the "bucket_name" field.
	BucketName string `json:"bucket_name,omitempty"`
	// RootPrefix holds the value of the "root_prefix" field.
	RootPrefix string `json:"root_prefix,omitempty"`
	// MountPath holds the value of the "mount_path" field.
	MountPath string `json:"mount_path,omitempty"`
	// Jurisdiction holds the value of the "jurisdiction" field.
	Jurisdiction string `json:"jurisdiction,omitempty"`
	// AccessKeyID holds the value of the "access_key_id" field.
	AccessKeyID string `json:"-"`
	// SecretAccessKey holds the value of the "secret_access_key" field.
	SecretAccessKey string `json:"-"`
	// WebdavUsername holds the value of the "webdav_username" field.
	WebdavUsername string `json:"webdav_username,omitempty"`
	// WebdavPasswordHash holds the value of the "webdav_password_hash" field.
	WebdavPasswordHash string `json:"-"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*S3WebDAVSetting) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case s3webdavsetting.FieldEnabled, s3webdavsetting.FieldWebdavEnabled, s3webdavsetting.FieldWebdavAuthEnabled, s3webdavsetting.FieldPathStyle:
			values[i] = new(sql.NullBool)
		case s3webdavsetting.FieldID, s3webdavsetting.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case s3webdavsetting.FieldKey, s3webdavsetting.FieldName, s3webdavsetting.FieldProvider, s3webdavsetting.FieldEndpointURL, s3webdavsetting.FieldRegion, s3webdavsetting.FieldAccountID, s3webdavsetting.FieldBucketName, s3webdavsetting.FieldRootPrefix, s3webdavsetting.FieldMountPath, s3webdavsetting.FieldJurisdiction, s3webdavsetting.FieldAccessKeyID, s3webdavsetting.FieldSecretAccessKey, s3webdavsetting.FieldWebdavUsername, s3webdavsetting.FieldWebdavPasswordHash:
			values[i] = new(sql.NullString)
		case s3webdavsetting.FieldCreatedAt, s3webdavsetting.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the S3WebDAVSetting fields.
func (_m *S3WebDAVSetting) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case s3webdavsetting.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case s3webdavsetting.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				_m.Key = value.String
			}
		case s3webdavsetting.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case s3webdavsetting.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		case s3webdavsetting.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case s3webdavsetting.FieldWebdavEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field webdav_enabled", values[i])
			} else if value.Valid {
				_m.WebdavEnabled = value.Bool
			}
		case s3webdavsetting.FieldWebdavAuthEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field webdav_auth_enabled", values[i])
			} else if value.Valid {
				_m.WebdavAuthEnabled = value.Bool
			}
		case s3webdavsetting.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case s3webdavsetting.FieldEndpointURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field endpoint_url", values[i])
			} else if value.Valid {
				_m.EndpointURL = value.String
			}
		case s3webdavsetting.FieldRegion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field region", values[i])
			} else if value.Valid {
				_m.Region = value.String
			}
		case s3webdavsetting.FieldPathStyle:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field path_style", values[i])
			} else if value.Valid {
				_m.PathStyle = value.Bool
			}
		case s3webdavsetting.FieldAccountID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.String
			}
		case s3webdavsetting.FieldBucketName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bucket_name", values[i])
			} else if value.Valid {
				_m.BucketName = value.String
			}
		case s3webdavsetting.FieldRootPrefix:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field root_prefix", values[i])
			} else if value.Valid {
				_m.RootPrefix = value.String
			}
		case s3webdavsetting.FieldMountPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mount_path", values[i])
			} else if value.Valid {
				_m.MountPath = value.String
			}
		case s3webdavsetting.FieldJurisdiction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field jurisdiction", values[i])
			} else if value.Valid {
				_m.Jurisdiction = value.String
			}
		case s3webdavsetting.FieldAccessKeyID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field access_key_id", values[i])
			} else if value.Valid {
				_m.AccessKeyID = value.String
			}
		case s3webdavsetting.FieldSecretAccessKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field secret_access_key", values[i])
			} else if value.Valid {
				_m.SecretAccessKey = value.String
			}
		case s3webdavsetting.FieldWebdavUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field webdav_username", values[i])
			} else if value.Valid {
				_m.WebdavUsername = value.String
			}
		case s3webdavsetting.FieldWebdavPasswordHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field webdav_password_hash", values[i])
			} else if value.Valid {
				_m.WebdavPasswordHash = value.String
			}
		case s3webdavsetting.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case s3webdavsetting.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the S3WebDAVSetting.
// This includes values selected through modifiers, order, etc.
func (_m *S3WebDAVSetting) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this S3WebDAVSetting.
// Note that you need to call S3WebDAVSetting.Unwrap() before calling this method if this S3WebDAVSetting
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *S3WebDAVSetting) Update() *S3WebDAVSettingUpdateOne {
	return NewS3WebDAVSettingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the S3WebDAVSetting entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *S3WebDAVSetting) Unwrap() *S3WebDAVSetting {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: S3WebDAVSetting is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *S3WebDAVSetting) String() string {
	var builder strings.Builder
	builder.WriteString("S3WebDAVSetting(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("key=")
	builder.WriteString(_m.Key)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("webdav_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.WebdavEnabled))
	builder.WriteString(", ")
	builder.WriteString("webdav_auth_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.WebdavAuthEnabled))
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("endpoint_url=")
	builder.WriteString(_m.EndpointURL)
	builder.WriteString(", ")
	builder.WriteString("region=")
	builder.WriteString(_m.Region)
	builder.WriteString(", ")
	builder.WriteString("path_style=")
	builder.WriteString(fmt.Sprintf("%v", _m.PathStyle))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(_m.AccountID)
	builder.WriteString(", ")
	builder.WriteString("bucket_name=")
	builder.WriteString(_m.BucketName)
	builder.WriteString(", ")
	builder.WriteString("root_prefix=")
	builder.WriteString(_m.RootPrefix)
	builder.WriteString(", ")
	builder.WriteString("mount_path=")
	builder.WriteString(_m.MountPath)
	builder.WriteString(", ")
	builder.WriteString("jurisdiction=")
	builder.WriteString(_m.Jurisdiction)
	builder.WriteString(", ")
	builder.WriteString("access_key_id=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("secret_access_key=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("webdav_username=")
	builder.WriteString(_m.WebdavUsername)
	builder.WriteString(", ")
	builder.WriteString("webdav_password_hash=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// S3WebDAVSettings is a parsable slice of S3WebDAVSetting.
type S3WebDAVSettings []*S3WebDAVSetting
