// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cfui/internal/persist/ent/predicate"
	"cfui/internal/persist/ent/s3webdavsetting"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// S3WebDAVSettingUpdate is the builder for updating S3WebDAVSetting entities.
type S3WebDAVSettingUpdate struct {
	config
	hooks    []Hook
	mutation *S3WebDAVSettingMutation
}

// Where appends a list predicates to the S3WebDAVSettingUpdate builder.
func (_u *S3WebDAVSettingUpdate) Where(ps ...predicate.S3WebDAVSetting) *S3WebDAVSettingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKey sets the "key" field.
func (_u *S3WebDAVSettingUpdate) SetKey(v string) *S3WebDAVSettingUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *S3WebDAVSettingUpdate) SetNillableKey(v *string) *S3WebDAVSettingUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *S3WebDAVSettingUpdate) SetName(v string) *S3WebDAVSettingUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *S3WebDAVSettingUpdate) SetNillableName(v *string) *S3WebDAVSettingUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *S3WebDAVSettingUpdate) SetSortOrder(v int) *S3WebDAVSettingUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *S3WebDAVSettingUpdate) SetNillableSortOrder(v *int) *S3WebDAVSettingUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *S3WebDAVSettingUpdate) AddSortOrder(v int) *S3WebDAVSettingUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *S3WebDAVSettingUpdate) SetEnabled(v bool) *S3WebDAVSettingUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *S3WebDAVSettingUpdate) SetNillableEnabled(v *bool) *S3WebDAVSettingUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetWebdavEnabled sets the "webdav_enabled" field.
func (_u *S3WebDAVSettingUpdate) SetWebdavEnabled(v bool) *S3WebDAVSettingUpdate {
	_u.mutation.SetWebdavEnabled(v)
	return _u
}

// SetNillableWebdavEnabled sets the "webdav_enabled" field if the given value is not nil.
func (_u *S3WebDAVSettingUpdate) SetNillableWebdavEnabled(v *bool) *S3WebDAVSettingUpdate {
	if v != nil {
		_u.SetWebdavEnabled(*v)
	}
	return _u
}

// SetWebdavAuthEnabled sets the "webdav_auth_enabled" field.
func (_u *S3WebDAVSettingUpdate) SetWebdavAuthEnabled(v bool) *S3WebDAVSettingUpdate {
	_u.mutation.SetWebdavAuthEnabled(v)
	return _u
}

// SetNillableWebdavAuthEnabled sets the "webdav_auth_enabled" field if the given value is not nil.
func (_u *S3WebDAVSettingUpdate) SetNillableWebdavAuthEnabled(v *bool) *S3WebDAVSettingUpdate {
	if v != nil {
		_u.SetWebdavAuthEnabled(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *S3WebDAVSettingUpdate) SetProvider(v string) *S3WebDAVSettingUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *S3WebDAVSettingUpdate) SetNillableProvider(v *string) *S3WebDAVSettingUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetEndpointURL sets the "endpoint_url" field.
func (_u *S3WebDAVSettingUpdate) SetEndpointURL(v string) *S3WebDAVSettingUpdate {
	_u.mutation.SetEndpointURL(v)
	return _u
}

// SetNillableEndpointURL sets the "endpoint_url" field if the given value is not nil.
func (_u *S3WebDAVSettingUpdate) SetNillableEndpointURL(v *string) *S3WebDAVSettingUpdate {
	if v != nil {
		_u.SetEndpointURL(*v)
	}
	return _u
}

// SetRegion sets the "region" field.
func (_u *S3WebDAVSettingUpdate) SetRegion(v string) *S3WebDAVSettingUpdate {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *S3WebDAVSettingUpdate) SetNillableRegion(v *string) *S3WebDAVSettingUpdate {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// SetPathStyle sets the "path_style" field.
func (_u *S3WebDAVSettingUpdate) SetPathStyle(v bool) *S3WebDAVSettingUpdate {
	_u.mutation.SetPathStyle(v)
	return _u
}

// SetNillablePathStyle sets the "path_style" field if the given value is not nil.
func (_u *S3WebDAVSettingUpdate) SetNillablePathStyle(v *bool) *S3WebDAVSettingUpdate {
	if v != nil {
		_u.SetPathStyle(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *S3WebDAVSettingUpdate) SetAccountID(v string) *S3WebDAVSettingUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *S3WebDAVSettingUpdate) SetNillableAccountID(v *string) *S3WebDAVSettingUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetBucketName sets the "bucket_name" field.
func (_u *S3WebDAVSettingUpdate) SetBucketName(v string) *S3WebDAVSettingUpdate {
	_u.mutation.SetBucketName(v)
	return _u
}

// SetNillableBucketName sets the "bucket_name" field if the given value is not nil.
func (_u *S3WebDAVSettingUpdate) SetNillableBucketName(v *string) *S3WebDAVSettingUpdate {
	if v != nil {
		_u.SetBucketName(*v)
	}
	return _u
}

// SetRootPrefix sets the "root_prefix" field.
func (_u *S3WebDAVSettingUpdate) SetRootPrefix(v string) *S3WebDAVSettingUpdate {
	_u.mutation.SetRootPrefix(v)
	return _u
}

// SetNillableRootPrefix sets the "root_prefix" field if the given value is not nil.
func (_u *S3WebDAVSettingUpdate) SetNillableRootPrefix(v *string) *S3WebDAVSettingUpdate {
	if v != nil {
		_u.SetRootPrefix(*v)
	}
	return _u
}

// SetMountPath sets the "mount_path" field.
func (_u *S3WebDAVSettingUpdate) SetMountPath(v string) *S3WebDAVSettingUpdate {
	_u.mutation.SetMountPath(v)
	return _u
}

// SetNillableMountPath sets the "mount_path" field if the given value is not nil.
func (_u *S3WebDAVSettingUpdate) SetNillableMountPath(v *string) *S3WebDAVSettingUpdate {
	if v != nil {
		_u.SetMountPath(*v)
	}
	return _u
}

// SetJurisdiction sets the "jurisdiction" field.
func (_u *S3WebDAVSettingUpdate) SetJurisdiction(v string) *S3WebDAVSettingUpdate {
	_u.mutation.SetJurisdiction(v)
	return _u
}

// SetNillableJurisdiction sets the "jurisdiction" field if the given value is not nil.
func (_u *S3WebDAVSettingUpdate) SetNillableJurisdiction(v *string) *S3WebDAVSettingUpdate {
	if v != nil {
		_u.SetJurisdiction(*v)
	}
	return _u
}

// SetAccessKeyID sets the "access_key_id" field.
func (_u *S3WebDAVSettingUpdate) SetAccessKeyID(v string) *S3WebDAVSettingUpdate {
	_u.mutation.SetAccessKeyID(v)
	return _u
}

// SetNillableAccessKeyID sets the "access_key_id" field if the given value is not nil.
func (_u *S3WebDAVSettingUpdate) SetNillableAccessKeyID(v *string) *S3WebDAVSettingUpdate {
	if v != nil {
		_u.SetAccessKeyID(*v)
	}
	return _u
}

// SetSecretAccessKey sets the "secret_access_key" field.
func (_u *S3WebDAVSettingUpdate) SetSecretAccessKey(v string) *S3WebDAVSettingUpdate {
	_u.mutation.SetSecretAccessKey(v)
	return _u
}

// SetNillableSecretAccessKey sets the "secret_access_key" field if the given value is not nil.
func (_u *S3WebDAVSettingUpdate) SetNillableSecretAccessKey(v *string) *S3WebDAVSettingUpdate {
	if v != nil {
		_u.SetSecretAccessKey(*v)
	}
	return _u
}

// SetWebdavUsername sets the "webdav_username" field.
func (_u *S3WebDAVSettingUpdate) SetWebdavUsername(v string) *S3WebDAVSettingUpdate {
	_u.mutation.SetWebdavUsername(v)
	return _u
}

// SetNillableWebdavUsername sets the "webdav_username" field if the given value is not nil.
func (_u *S3WebDAVSettingUpdate) SetNillableWebdavUsername(v *string) *S3WebDAVSettingUpdate {
	if v != nil {
		_u.SetWebdavUsername(*v)
	}
	return _u
}

// SetWebdavPasswordHash sets the "webdav_password_hash" field.
func (_u *S3WebDAVSettingUpdate) SetWebdavPasswordHash(v string) *S3WebDAVSettingUpdate {
	_u.mutation.SetWebdavPasswordHash(v)
	return _u
}

// SetNillableWebdavPasswordHash sets the "webdav_password_hash" field if the given value is not nil.
func (_u *S3WebDAVSettingUpdate) SetNillableWebdavPasswordHash(v *string) *S3WebDAVSettingUpdate {
	if v != nil {
		_u.SetWebdavPasswordHash(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *S3WebDAVSettingUpdate) SetUpdatedAt(v time.Time) *S3WebDAVSettingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the S3WebDAVSettingMutation object of the builder.
func (_u *S3WebDAVSettingUpdate) Mutation() *S3WebDAVSettingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *S3WebDAVSettingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *S3WebDAVSettingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *S3WebDAVSettingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *S3WebDAVSettingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *S3WebDAVSettingUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := s3webdavsetting.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *S3WebDAVSettingUpdate) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := s3webdavsetting.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "S3WebDAVSetting.key": %w`, err)}
		}
	}
	return nil
}

func (_u *S3WebDAVSettingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(s3webdavsetting.Table, s3webdavsetting.Columns, sqlgraph.NewFieldSpec(s3webdavsetting.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(s3webdavsetting.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(s3webdavsetting.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(s3webdavsetting.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(s3webdavsetting.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(s3webdavsetting.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.WebdavEnabled(); ok {
		_spec.SetField(s3webdavsetting.FieldWebdavEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.WebdavAuthEnabled(); ok {
		_spec.SetField(s3webdavsetting.FieldWebdavAuthEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(s3webdavsetting.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.EndpointURL(); ok {
		_spec.SetField(s3webdavsetting.FieldEndpointURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(s3webdavsetting.FieldRegion, field.TypeString, value)
	}
	if value, ok := _u.mutation.PathStyle(); ok {
		_spec.SetField(s3webdavsetting.FieldPathStyle, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(s3webdavsetting.FieldAccountID, field.TypeString, value)
	}
	if value, ok := _u.mutation.BucketName(); ok {
		_spec.SetField(s3webdavsetting.FieldBucketName, field.TypeString, value)
	}
	if value, ok := _u.mutation.RootPrefix(); ok {
		_spec.SetField(s3webdavsetting.FieldRootPrefix, field.TypeString, value)
	}
	if value, ok := _u.mutation.MountPath(); ok {
		_spec.SetField(s3webdavsetting.FieldMountPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Jurisdiction(); ok {
		_spec.SetField(s3webdavsetting.FieldJurisdiction, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccessKeyID(); ok {
		_spec.SetField(s3webdavsetting.FieldAccessKeyID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SecretAccessKey(); ok {
		_spec.SetField(s3webdavsetting.FieldSecretAccessKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.WebdavUsername(); ok {
		_spec.SetField(s3webdavsetting.FieldWebdavUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.WebdavPasswordHash(); ok {
		_spec.SetField(s3webdavsetting.FieldWebdavPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(s3webdavsetting.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{s3webdavsetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// S3WebDAVSettingUpdateOne is the builder for updating a single S3WebDAVSetting entity.
type S3WebDAVSettingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *S3WebDAVSettingMutation
}

// SetKey sets the "key" field.
func (_u *S3WebDAVSettingUpdateOne) SetKey(v string) *S3WebDAVSettingUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *S3WebDAVSettingUpdateOne) SetNillableKey(v *string) *S3WebDAVSettingUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *S3WebDAVSettingUpdateOne) SetName(v string) *S3WebDAVSettingUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *S3WebDAVSettingUpdateOne) SetNillableName(v *string) *S3WebDAVSettingUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *S3WebDAVSettingUpdateOne) SetSortOrder(v int) *S3WebDAVSettingUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *S3WebDAVSettingUpdateOne) SetNillableSortOrder(v *int) *S3WebDAVSettingUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *S3WebDAVSettingUpdateOne) AddSortOrder(v int) *S3WebDAVSettingUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *S3WebDAVSettingUpdateOne) SetEnabled(v bool) *S3WebDAVSettingUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *S3WebDAVSettingUpdateOne) SetNillableEnabled(v *bool) *S3WebDAVSettingUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetWebdavEnabled sets the "webdav_enabled" field.
func (_u *S3WebDAVSettingUpdateOne) SetWebdavEnabled(v bool) *S3WebDAVSettingUpdateOne {
	_u.mutation.SetWebdavEnabled(v)
	return _u
}

// SetNillableWebdavEnabled sets the "webdav_enabled" field if the given value is not nil.
func (_u *S3WebDAVSettingUpdateOne) SetNillableWebdavEnabled(v *bool) *S3WebDAVSettingUpdateOne {
	if v != nil {
		_u.SetWebdavEnabled(*v)
	}
	return _u
}

// SetWebdavAuthEnabled sets the "webdav_auth_enabled" field.
func (_u *S3WebDAVSettingUpdateOne) SetWebdavAuthEnabled(v bool) *S3WebDAVSettingUpdateOne {
	_u.mutation.SetWebdavAuthEnabled(v)
	return _u
}

// SetNillableWebdavAuthEnabled sets the "webdav_auth_enabled" field if the given value is not nil.
func (_u *S3WebDAVSettingUpdateOne) SetNillableWebdavAuthEnabled(v *bool) *S3WebDAVSettingUpdateOne {
	if v != nil {
		_u.SetWebdavAuthEnabled(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *S3WebDAVSettingUpdateOne) SetProvider(v string) *S3WebDAVSettingUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *S3WebDAVSettingUpdateOne) SetNillableProvider(v *string) *S3WebDAVSettingUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetEndpointURL sets the "endpoint_url" field.
func (_u *S3WebDAVSettingUpdateOne) SetEndpointURL(v string) *S3WebDAVSettingUpdateOne {
	_u.mutation.SetEndpointURL(v)
	return _u
}

// SetNillableEndpointURL sets the "endpoint_url" field if the given value is not nil.
func (_u *S3WebDAVSettingUpdateOne) SetNillableEndpointURL(v *string) *S3WebDAVSettingUpdateOne {
	if v != nil {
		_u.SetEndpointURL(*v)
	}
	return _u
}

// SetRegion sets the "region" field.
func (_u *S3WebDAVSettingUpdateOne) SetRegion(v string) *S3WebDAVSettingUpdateOne {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *S3WebDAVSettingUpdateOne) SetNillableRegion(v *string) *S3WebDAVSettingUpdateOne {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// SetPathStyle sets the "path_style" field.
func (_u *S3WebDAVSettingUpdateOne) SetPathStyle(v bool) *S3WebDAVSettingUpdateOne {
	_u.mutation.SetPathStyle(v)
	return _u
}

// SetNillablePathStyle sets the "path_style" field if the given value is not nil.
func (_u *S3WebDAVSettingUpdateOne) SetNillablePathStyle(v *bool) *S3WebDAVSettingUpdateOne {
	if v != nil {
		_u.SetPathStyle(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *S3WebDAVSettingUpdateOne) SetAccountID(v string) *S3WebDAVSettingUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *S3WebDAVSettingUpdateOne) SetNillableAccountID(v *string) *S3WebDAVSettingUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetBucketName sets the "bucket_name" field.
func (_u *S3WebDAVSettingUpdateOne) SetBucketName(v string) *S3WebDAVSettingUpdateOne {
	_u.mutation.SetBucketName(v)
	return _u
}

// SetNillableBucketName sets the "bucket_name" field if the given value is not nil.
func (_u *S3WebDAVSettingUpdateOne) SetNillableBucketName(v *string) *S3WebDAVSettingUpdateOne {
	if v != nil {
		_u.SetBucketName(*v)
	}
	return _u
}

// SetRootPrefix sets the "root_prefix" field.
func (_u *S3WebDAVSettingUpdateOne) SetRootPrefix(v string) *S3WebDAVSettingUpdateOne {
	_u.mutation.SetRootPrefix(v)
	return _u
}

// SetNillableRootPrefix sets the "root_prefix" field if the given value is not nil.
func (_u *S3WebDAVSettingUpdateOne) SetNillableRootPrefix(v *string) *S3WebDAVSettingUpdateOne {
	if v != nil {
		_u.SetRootPrefix(*v)
	}
	return _u
}

// SetMountPath sets the "mount_path" field.
func (_u *S3WebDAVSettingUpdateOne) SetMountPath(v string) *S3WebDAVSettingUpdateOne {
	_u.mutation.SetMountPath(v)
	return _u
}

// SetNillableMountPath sets the "mount_path" field if the given value is not nil.
func (_u *S3WebDAVSettingUpdateOne) SetNillableMountPath(v *string) *S3WebDAVSettingUpdateOne {
	if v != nil {
		_u.SetMountPath(*v)
	}
	return _u
}

// SetJurisdiction sets the "jurisdiction" field.
func (_u *S3WebDAVSettingUpdateOne) SetJurisdiction(v string) *S3WebDAVSettingUpdateOne {
	_u.mutation.SetJurisdiction(v)
	return _u
}

// SetNillableJurisdiction sets the "jurisdiction" field if the given value is not nil.
func (_u *S3WebDAVSettingUpdateOne) SetNillableJurisdiction(v *string) *S3WebDAVSettingUpdateOne {
	if v != nil {
		_u.SetJurisdiction(*v)
	}
	return _u
}

// SetAccessKeyID sets the "access_key_id" field.
func (_u *S3WebDAVSettingUpdateOne) SetAccessKeyID(v string) *S3WebDAVSettingUpdateOne {
	_u.mutation.SetAccessKeyID(v)
	return _u
}

// SetNillableAccessKeyID sets the "access_key_id" field if the given value is not nil.
func (_u *S3WebDAVSettingUpdateOne) SetNillableAccessKeyID(v *string) *S3WebDAVSettingUpdateOne {
	if v != nil {
		_u.SetAccessKeyID(*v)
	}
	return _u
}

// SetSecretAccessKey sets the "secret_access_key" field.
func (_u *S3WebDAVSettingUpdateOne) SetSecretAccessKey(v string) *S3WebDAVSettingUpdateOne {
	_u.mutation.SetSecretAccessKey(v)
	return _u
}

// SetNillableSecretAccessKey sets the "secret_access_key" field if the given value is not nil.
func (_u *S3WebDAVSettingUpdateOne) SetNillableSecretAccessKey(v *string) *S3WebDAVSettingUpdateOne {
	if v != nil {
		_u.SetSecretAccessKey(*v)
	}
	return _u
}

// SetWebdavUsername sets the "webdav_username" field.
func (_u *S3WebDAVSettingUpdateOne) SetWebdavUsername(v string) *S3WebDAVSettingUpdateOne {
	_u.mutation.SetWebdavUsername(v)
	return _u
}

// SetNillableWebdavUsername sets the "webdav_username" field if the given value is not nil.
func (_u *S3WebDAVSettingUpdateOne) SetNillableWebdavUsername(v *string) *S3WebDAVSettingUpdateOne {
	if v != nil {
		_u.SetWebdavUsername(*v)
	}
	return _u
}

// SetWebdavPasswordHash sets the "webdav_password_hash" field.
func (_u *S3WebDAVSettingUpdateOne) SetWebdavPasswordHash(v string) *S3WebDAVSettingUpdateOne {
	_u.mutation.SetWebdavPasswordHash(v)
	return _u
}

// SetNillableWebdavPasswordHash sets the "webdav_password_hash" field if the given value is not nil.
func (_u *S3WebDAVSettingUpdateOne) SetNillableWebdavPasswordHash(v *string) *S3WebDAVSettingUpdateOne {
	if v != nil {
		_u.SetWebdavPasswordHash(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *S3WebDAVSettingUpdateOne) SetUpdatedAt(v time.Time) *S3WebDAVSettingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the S3WebDAVSettingMutation object of the builder.
func (_u *S3WebDAVSettingUpdateOne) Mutation() *S3WebDAVSettingMutation {
	return _u.mutation
}

// Where appends a list predicates to the S3WebDAVSettingUpdate builder.
func (_u *S3WebDAVSettingUpdateOne) Where(ps ...predicate.S3WebDAVSetting) *S3WebDAVSettingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *S3WebDAVSettingUpdateOne) Select(field string, fields ...string) *S3WebDAVSettingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated S3WebDAVSetting entity.
func (_u *S3WebDAVSettingUpdateOne) Save(ctx context.Context) (*S3WebDAVSetting, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *S3WebDAVSettingUpdateOne) SaveX(ctx context.Context) *S3WebDAVSetting {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *S3WebDAVSettingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *S3WebDAVSettingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *S3WebDAVSettingUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := s3webdavsetting.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *S3WebDAVSettingUpdateOne) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := s3webdavsetting.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "S3WebDAVSetting.key": %w`, err)}
		}
	}
	return nil
}

func (_u *S3WebDAVSettingUpdateOne) sqlSave(ctx context.Context) (_node *S3WebDAVSetting, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(s3webdavsetting.Table, s3webdavsetting.Columns, sqlgraph.NewFieldSpec(s3webdavsetting.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "S3WebDAVSetting.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, s3webdavsetting.FieldID)
		for _, f := range fields {
			if !s3webdavsetting.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != s3webdavsetting.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(s3webdavsetting.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(s3webdavsetting.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(s3webdavsetting.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(s3webdavsetting.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(s3webdavsetting.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.WebdavEnabled(); ok {
		_spec.SetField(s3webdavsetting.FieldWebdavEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.WebdavAuthEnabled(); ok {
		_spec.SetField(s3webdavsetting.FieldWebdavAuthEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(s3webdavsetting.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.EndpointURL(); ok {
		_spec.SetField(s3webdavsetting.FieldEndpointURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(s3webdavsetting.FieldRegion, field.TypeString, value)
	}
	if value, ok := _u.mutation.PathStyle(); ok {
		_spec.SetField(s3webdavsetting.FieldPathStyle, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(s3webdavsetting.FieldAccountID, field.TypeString, value)
	}
	if value, ok := _u.mutation.BucketName(); ok {
		_spec.SetField(s3webdavsetting.FieldBucketName, field.TypeString, value)
	}
	if value, ok := _u.mutation.RootPrefix(); ok {
		_spec.SetField(s3webdavsetting.FieldRootPrefix, field.TypeString, value)
	}
	if value, ok := _u.mutation.MountPath(); ok {
		_spec.SetField(s3webdavsetting.FieldMountPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Jurisdiction(); ok {
		_spec.SetField(s3webdavsetting.FieldJurisdiction, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccessKeyID(); ok {
		_spec.SetField(s3webdavsetting.FieldAccessKeyID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SecretAccessKey(); ok {
		_spec.SetField(s3webdavsetting.FieldSecretAccessKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.WebdavUsername(); ok {
		_spec.SetField(s3webdavsetting.FieldWebdavUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.WebdavPasswordHash(); ok {
		_spec.SetField(s3webdavsetting.FieldWebdavPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(s3webdavsetting.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &S3WebDAVSetting{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{s3webdavsetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
