// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cfui/internal/persist/ent/tunnelprofile"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TunnelProfileCreate is the builder for creating a TunnelProfile entity.
type TunnelProfileCreate struct {
	config
	mutation *TunnelProfileMutation
	hooks    []Hook
}

// SetKey sets the "key" field.
func (_c *TunnelProfileCreate) SetKey(v string) *TunnelProfileCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetName sets the "name" field.
func (_c *TunnelProfileCreate) SetName(v string) *TunnelProfileCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *TunnelProfileCreate) SetNillableName(v *string) *TunnelProfileCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *TunnelProfileCreate) SetSortOrder(v int) *TunnelProfileCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *TunnelProfileCreate) SetNillableSortOrder(v *int) *TunnelProfileCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetToken sets the "token" field.
func (_c *TunnelProfileCreate) SetToken(v string) *TunnelProfileCreate {
	_c.mutation.SetToken(v)
	return _c
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_c *TunnelProfileCreate) SetNillableToken(v *string) *TunnelProfileCreate {
	if v != nil {
		_c.SetToken(*v)
	}
	return _c
}

// SetLocalEnabled sets the "local_enabled" field.
func (_c *TunnelProfileCreate) SetLocalEnabled(v bool) *TunnelProfileCreate {
	_c.mutation.SetLocalEnabled(v)
	return _c
}

// SetNillableLocalEnabled sets the "local_enabled" field if the given value is not nil.
func (_c *TunnelProfileCreate) SetNillableLocalEnabled(v *bool) *TunnelProfileCreate {
	if v != nil {
		_c.SetLocalEnabled(*v)
	}
	return _c
}

// SetRemoteManagementEnabled sets the "remote_management_enabled" field.
func (_c *TunnelProfileCreate) SetRemoteManagementEnabled(v bool) *TunnelProfileCreate {
	_c.mutation.SetRemoteManagementEnabled(v)
	return _c
}

// SetNillableRemoteManagementEnabled sets the "remote_management_enabled" field if the given value is not nil.
func (_c *TunnelProfileCreate) SetNillableRemoteManagementEnabled(v *bool) *TunnelProfileCreate {
	if v != nil {
		_c.SetRemoteManagementEnabled(*v)
	}
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *TunnelProfileCreate) SetAccountID(v string) *TunnelProfileCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_c *TunnelProfileCreate) SetNillableAccountID(v *string) *TunnelProfileCreate {
	if v != nil {
		_c.SetAccountID(*v)
	}
	return _c
}

// SetTunnelID sets the "tunnel_id" field.
func (_c *TunnelProfileCreate) SetTunnelID(v string) *TunnelProfileCreate {
	_c.mutation.SetTunnelID(v)
	return _c
}

// SetNillableTunnelID sets the "tunnel_id" field if the given value is not nil.
func (_c *TunnelProfileCreate) SetNillableTunnelID(v *string) *TunnelProfileCreate {
	if v != nil {
		_c.SetTunnelID(*v)
	}
	return _c
}

// SetAutoStart sets the "auto_start" field.
func (_c *TunnelProfileCreate) SetAutoStart(v bool) *TunnelProfileCreate {
	_c.mutation.SetAutoStart(v)
	return _c
}

// SetNillableAutoStart sets the "auto_start" field if the given value is not nil.
func (_c *TunnelProfileCreate) SetNillableAutoStart(v *bool) *TunnelProfileCreate {
	if v != nil {
		_c.SetAutoStart(*v)
	}
	return _c
}

// SetAutoRestart sets the "auto_restart" field.
func (_c *TunnelProfileCreate) SetAutoRestart(v bool) *TunnelProfileCreate {
	_c.mutation.SetAutoRestart(v)
	return _c
}

// SetNillableAutoRestart sets the "auto_restart" field if the given value is not nil.
func (_c *TunnelProfileCreate) SetNillableAutoRestart(v *bool) *TunnelProfileCreate {
	if v != nil {
		_c.SetAutoRestart(*v)
	}
	return _c
}

// SetCustomTag sets the "custom_tag" field.
func (_c *TunnelProfileCreate) SetCustomTag(v string) *TunnelProfileCreate {
	_c.mutation.SetCustomTag(v)
	return _c
}

// SetNillableCustomTag sets the "custom_tag" field if the given value is not nil.
func (_c *TunnelProfileCreate) SetNillableCustomTag(v *string) *TunnelProfileCreate {
	if v != nil {
		_c.SetCustomTag(*v)
	}
	return _c
}

// SetSoftwareName sets the "software_name" field.
func (_c *TunnelProfileCreate) SetSoftwareName(v string) *TunnelProfileCreate {
	_c.mutation.SetSoftwareName(v)
	return _c
}

// SetNillableSoftwareName sets the "software_name" field if the given value is not nil.
func (_c *TunnelProfileCreate) SetNillableSoftwareName(v *string) *TunnelProfileCreate {
	if v != nil {
		_c.SetSoftwareName(*v)
	}
	return _c
}

// SetProtocol sets the "protocol" field.
func (_c *TunnelProfileCreate) SetProtocol(v string) *TunnelProfileCreate {
	_c.mutation.SetProtocol(v)
	return _c
}

// SetNillableProtocol sets the "protocol" field if the given value is not nil.
func (_c *TunnelProfileCreate) SetNillableProtocol(v *string) *TunnelProfileCreate {
	if v != nil {
		_c.SetProtocol(*v)
	}
	return _c
}

// SetGracePeriod sets the "grace_period" field.
func (_c *TunnelProfileCreate) SetGracePeriod(v string) *TunnelProfileCreate {
	_c.mutation.SetGracePeriod(v)
	return _c
}

// SetNillableGracePeriod sets the "grace_period" field if the given value is not nil.
func (_c *TunnelProfileCreate) SetNillableGracePeriod(v *string) *TunnelProfileCreate {
	if v != nil {
		_c.SetGracePeriod(*v)
	}
	return _c
}

// SetRegion sets the "region" field.
func (_c *TunnelProfileCreate) SetRegion(v string) *TunnelProfileCreate {
	_c.mutation.SetRegion(v)
	return _c
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_c *TunnelProfileCreate) SetNillableRegion(v *string) *TunnelProfileCreate {
	if v != nil {
		_c.SetRegion(*v)
	}
	return _c
}

// SetRetries sets the "retries" field.
func (_c *TunnelProfileCreate) SetRetries(v int) *TunnelProfileCreate {
	_c.mutation.SetRetries(v)
	return _c
}

// SetNillableRetries sets the "retries" field if the given value is not nil.
func (_c *TunnelProfileCreate) SetNillableRetries(v *int) *TunnelProfileCreate {
	if v != nil {
		_c.SetRetries(*v)
	}
	return _c
}

// SetMetricsEnable sets the "metrics_enable" field.
func (_c *TunnelProfileCreate) SetMetricsEnable(v bool) *TunnelProfileCreate {
	_c.mutation.SetMetricsEnable(v)
	return _c
}

// SetNillableMetricsEnable sets the "metrics_enable" field if the given value is not nil.
func (_c *TunnelProfileCreate) SetNillableMetricsEnable(v *bool) *TunnelProfileCreate {
	if v != nil {
		_c.SetMetricsEnable(*v)
	}
	return _c
}

// SetMetricsPort sets the "metrics_port" field.
func (_c *TunnelProfileCreate) SetMetricsPort(v int) *TunnelProfileCreate {
	_c.mutation.SetMetricsPort(v)
	return _c
}

// SetNillableMetricsPort sets the "metrics_port" field if the given value is not nil.
func (_c *TunnelProfileCreate) SetNillableMetricsPort(v *int) *TunnelProfileCreate {
	if v != nil {
		_c.SetMetricsPort(*v)
	}
	return _c
}

// SetLogLevel sets the "log_level" field.
func (_c *TunnelProfileCreate) SetLogLevel(v string) *TunnelProfileCreate {
	_c.mutation.SetLogLevel(v)
	return _c
}

// SetNillableLogLevel sets the "log_level" field if the given value is not nil.
func (_c *TunnelProfileCreate) SetNillableLogLevel(v *string) *TunnelProfileCreate {
	if v != nil {
		_c.SetLogLevel(*v)
	}
	return _c
}

// SetLogFile sets the "log_file" field.
func (_c *TunnelProfileCreate) SetLogFile(v string) *TunnelProfileCreate {
	_c.mutation.SetLogFile(v)
	return _c
}

// SetNillableLogFile sets the "log_file" field if the given value is not nil.
func (_c *TunnelProfileCreate) SetNillableLogFile(v *string) *TunnelProfileCreate {
	if v != nil {
		_c.SetLogFile(*v)
	}
	return _c
}

// SetLogJSON sets the "log_json" field.
func (_c *TunnelProfileCreate) SetLogJSON(v bool) *TunnelProfileCreate {
	_c.mutation.SetLogJSON(v)
	return _c
}

// SetNillableLogJSON sets the "log_json" field if the given value is not nil.
func (_c *TunnelProfileCreate) SetNillableLogJSON(v *bool) *TunnelProfileCreate {
	if v != nil {
		_c.SetLogJSON(*v)
	}
	return _c
}

// SetEdgeIPVersion sets the "edge_ip_version" field.
func (_c *TunnelProfileCreate) SetEdgeIPVersion(v string) *TunnelProfileCreate {
	_c.mutation.SetEdgeIPVersion(v)
	return _c
}

// SetNillableEdgeIPVersion sets the "edge_ip_version" field if the given value is not nil.
func (_c *TunnelProfileCreate) SetNillableEdgeIPVersion(v *string) *TunnelProfileCreate {
	if v != nil {
		_c.SetEdgeIPVersion(*v)
	}
	return _c
}

// SetEdgeBindAddress sets the "edge_bind_address" field.
func (_c *TunnelProfileCreate) SetEdgeBindAddress(v string) *TunnelProfileCreate {
	_c.mutation.SetEdgeBindAddress(v)
	return _c
}

// SetNillableEdgeBindAddress sets the "edge_bind_address" field if the given value is not nil.
func (_c *TunnelProfileCreate) SetNillableEdgeBindAddress(v *string) *TunnelProfileCreate {
	if v != nil {
		_c.SetEdgeBindAddress(*v)
	}
	return _c
}

// SetEdge sets the "edge" field.
func (_c *TunnelProfileCreate) SetEdge(v string) *TunnelProfileCreate {
	_c.mutation.SetEdge(v)
	return _c
}

// SetNillableEdge sets the "edge" field if the given value is not nil.
func (_c *TunnelProfileCreate) SetNillableEdge(v *string) *TunnelProfileCreate {
	if v != nil {
		_c.SetEdge(*v)
	}
	return _c
}

// SetPostQuantum sets the "post_quantum" field.
func (_c *TunnelProfileCreate) SetPostQuantum(v bool) *TunnelProfileCreate {
	_c.mutation.SetPostQuantum(v)
	return _c
}

// SetNillablePostQuantum sets the "post_quantum" field if the given value is not nil.
func (_c *TunnelProfileCreate) SetNillablePostQuantum(v *bool) *TunnelProfileCreate {
	if v != nil {
		_c.SetPostQuantum(*v)
	}
	return _c
}

// SetNoTLSVerify sets the "no_tls_verify" field.
func (_c *TunnelProfileCreate) SetNoTLSVerify(v bool) *TunnelProfileCreate {
	_c.mutation.SetNoTLSVerify(v)
	return _c
}

// SetNillableNoTLSVerify sets the "no_tls_verify" field if the given value is not nil.
func (_c *TunnelProfileCreate) SetNillableNoTLSVerify(v *bool) *TunnelProfileCreate {
	if v != nil {
		_c.SetNoTLSVerify(*v)
	}
	return _c
}

// SetExtraArgs sets the "extra_args" field.
func (_c *TunnelProfileCreate) SetExtraArgs(v string) *TunnelProfileCreate {
	_c.mutation.SetExtraArgs(v)
	return _c
}

// SetNillableExtraArgs sets the "extra_args" field if the given value is not nil.
func (_c *TunnelProfileCreate) SetNillableExtraArgs(v *string) *TunnelProfileCreate {
	if v != nil {
		_c.SetExtraArgs(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TunnelProfileCreate) SetCreatedAt(v time.Time) *TunnelProfileCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TunnelProfileCreate) SetNillableCreatedAt(v *time.Time) *TunnelProfileCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TunnelProfileCreate) SetUpdatedAt(v time.Time) *TunnelProfileCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TunnelProfileCreate) SetNillableUpdatedAt(v *time.Time) *TunnelProfileCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the TunnelProfileMutation object of the builder.
func (_c *TunnelProfileCreate) Mutation() *TunnelProfileMutation {
	return _c.mutation
}

// Save creates the TunnelProfile in the database.
func (_c *TunnelProfileCreate) Save(ctx context.Context) (*TunnelProfile, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TunnelProfileCreate) SaveX(ctx context.Context) *TunnelProfile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TunnelProfileCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TunnelProfileCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TunnelProfileCreate) defaults() {
	if _, ok := _c.mutation.Name(); !ok {
		v := tunnelprofile.DefaultName
		_c.mutation.SetName(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := tunnelprofile.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.Token(); !ok {
		v := tunnelprofile.DefaultToken
		_c.mutation.SetToken(v)
	}
	if _, ok := _c.mutation.LocalEnabled(); !ok {
		v := tunnelprofile.DefaultLocalEnabled
		_c.mutation.SetLocalEnabled(v)
	}
	if _, ok := _c.mutation.RemoteManagementEnabled(); !ok {
		v := tunnelprofile.DefaultRemoteManagementEnabled
		_c.mutation.SetRemoteManagementEnabled(v)
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		v := tunnelprofile.DefaultAccountID
		_c.mutation.SetAccountID(v)
	}
	if _, ok := _c.mutation.TunnelID(); !ok {
		v := tunnelprofile.DefaultTunnelID
		_c.mutation.SetTunnelID(v)
	}
	if _, ok := _c.mutation.AutoStart(); !ok {
		v := tunnelprofile.DefaultAutoStart
		_c.mutation.SetAutoStart(v)
	}
	if _, ok := _c.mutation.AutoRestart(); !ok {
		v := tunnelprofile.DefaultAutoRestart
		_c.mutation.SetAutoRestart(v)
	}
	if _, ok := _c.mutation.CustomTag(); !ok {
		v := tunnelprofile.DefaultCustomTag
		_c.mutation.SetCustomTag(v)
	}
	if _, ok := _c.mutation.SoftwareName(); !ok {
		v := tunnelprofile.DefaultSoftwareName
		_c.mutation.SetSoftwareName(v)
	}
	if _, ok := _c.mutation.Protocol(); !ok {
		v := tunnelprofile.DefaultProtocol
		_c.mutation.SetProtocol(v)
	}
	if _, ok := _c.mutation.GracePeriod(); !ok {
		v := tunnelprofile.DefaultGracePeriod
		_c.mutation.SetGracePeriod(v)
	}
	if _, ok := _c.mutation.Region(); !ok {
		v := tunnelprofile.DefaultRegion
		_c.mutation.SetRegion(v)
	}
	if _, ok := _c.mutation.Retries(); !ok {
		v := tunnelprofile.DefaultRetries
		_c.mutation.SetRetries(v)
	}
	if _, ok := _c.mutation.MetricsEnable(); !ok {
		v := tunnelprofile.DefaultMetricsEnable
		_c.mutation.SetMetricsEnable(v)
	}
	if _, ok := _c.mutation.MetricsPort(); !ok {
		v := tunnelprofile.DefaultMetricsPort
		_c.mutation.SetMetricsPort(v)
	}
	if _, ok := _c.mutation.LogLevel(); !ok {
		v := tunnelprofile.DefaultLogLevel
		_c.mutation.SetLogLevel(v)
	}
	if _, ok := _c.mutation.LogFile(); !ok {
		v := tunnelprofile.DefaultLogFile
		_c.mutation.SetLogFile(v)
	}
	if _, ok := _c.mutation.LogJSON(); !ok {
		v := tunnelprofile.DefaultLogJSON
		_c.mutation.SetLogJSON(v)
	}
	if _, ok := _c.mutation.EdgeIPVersion(); !ok {
		v := tunnelprofile.DefaultEdgeIPVersion
		_c.mutation.SetEdgeIPVersion(v)
	}
	if _, ok := _c.mutation.EdgeBindAddress(); !ok {
		v := tunnelprofile.DefaultEdgeBindAddress
		_c.mutation.SetEdgeBindAddress(v)
	}
	if _, ok := _c.mutation.Edge(); !ok {
		v := tunnelprofile.DefaultEdge
		_c.mutation.SetEdge(v)
	}
	if _, ok := _c.mutation.PostQuantum(); !ok {
		v := tunnelprofile.DefaultPostQuantum
		_c.mutation.SetPostQuantum(v)
	}
	if _, ok := _c.mutation.NoTLSVerify(); !ok {
		v := tunnelprofile.DefaultNoTLSVerify
		_c.mutation.SetNoTLSVerify(v)
	}
	if _, ok := _c.mutation.ExtraArgs(); !ok {
		v := tunnelprofile.DefaultExtraArgs
		_c.mutation.SetExtraArgs(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := tunnelprofile.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := tunnelprofile.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TunnelProfileCreate) check() error {
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "TunnelProfile.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := tunnelprofile.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "TunnelProfile.key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "TunnelProfile.name"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "TunnelProfile.sort_order"`)}
	}
	if _, ok := _c.mutation.Token(); !ok {
		return &ValidationError{Name: "token", err: errors.New(`ent: missing required field "TunnelProfile.token"`)}
	}
	if _, ok := _c.mutation.LocalEnabled(); !ok {
		return &ValidationError{Name: "local_enabled", err: errors.New(`ent: missing required field "TunnelProfile.local_enabled"`)}
	}
	if _, ok := _c.mutation.RemoteManagementEnabled(); !ok {
		return &ValidationError{Name: "remote_management_enabled", err: errors.New(`ent: missing required field "TunnelProfile.remote_management_enabled"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "TunnelProfile.account_id"`)}
	}
	if _, ok := _c.mutation.TunnelID(); !ok {
		return &ValidationError{Name: "tunnel_id", err: errors.New(`ent: missing required field "TunnelProfile.tunnel_id"`)}
	}
	if _, ok := _c.mutation.AutoStart(); !ok {
		return &ValidationError{Name: "auto_start", err: errors.New(`ent: missing required field "TunnelProfile.auto_start"`)}
	}
	if _, ok := _c.mutation.AutoRestart(); !ok {
		return &ValidationError{Name: "auto_restart", err: errors.New(`ent: missing required field "TunnelProfile.auto_restart"`)}
	}
	if _, ok := _c.mutation.CustomTag(); !ok {
		return &ValidationError{Name: "custom_tag", err: errors.New(`ent: missing required field "TunnelProfile.custom_tag"`)}
	}
	if _, ok := _c.mutation.SoftwareName(); !ok {
		return &ValidationError{Name: "software_name", err: errors.New(`ent: missing required field "TunnelProfile.software_name"`)}
	}
	if _, ok := _c.mutation.Protocol(); !ok {
		return &ValidationError{Name: "protocol", err: errors.New(`ent: missing required field "TunnelProfile.protocol"`)}
	}
	if _, ok := _c.mutation.GracePeriod(); !ok {
		return &ValidationError{Name: "grace_period", err: errors.New(`ent: missing required field "TunnelProfile.grace_period"`)}
	}
	if _, ok := _c.mutation.Region(); !ok {
		return &ValidationError{Name: "region", err: errors.New(`ent: missing required field "TunnelProfile.region"`)}
	}
	if _, ok := _c.mutation.Retries(); !ok {
		return &ValidationError{Name: "retries", err: errors.New(`ent: missing required field "TunnelProfile.retries"`)}
	}
	if _, ok := _c.mutation.MetricsEnable(); !ok {
		return &ValidationError{Name: "metrics_enable", err: errors.New(`ent: missing required field "TunnelProfile.metrics_enable"`)}
	}
	if _, ok := _c.mutation.MetricsPort(); !ok {
		return &ValidationError{Name: "metrics_port", err: errors.New(`ent: missing required field "TunnelProfile.metrics_port"`)}
	}
	if _, ok := _c.mutation.LogLevel(); !ok {
		return &ValidationError{Name: "log_level", err: errors.New(`ent: missing required field "TunnelProfile.log_level"`)}
	}
	if _, ok := _c.mutation.LogFile(); !ok {
		return &ValidationError{Name: "log_file", err: errors.New(`ent: missing required field "TunnelProfile.log_file"`)}
	}
	if _, ok := _c.mutation.LogJSON(); !ok {
		return &ValidationError{Name: "log_json", err: errors.New(`ent: missing required field "TunnelProfile.log_json"`)}
	}
	if _, ok := _c.mutation.EdgeIPVersion(); !ok {
		return &ValidationError{Name: "edge_ip_version", err: errors.New(`ent: missing required field "TunnelProfile.edge_ip_version"`)}
	}
	if _, ok := _c.mutation.EdgeBindAddress(); !ok {
		return &ValidationError{Name: "edge_bind_address", err: errors.New(`ent: missing required field "TunnelProfile.edge_bind_address"`)}
	}
	if _, ok := _c.mutation.Edge(); !ok {
		return &ValidationError{Name: "edge", err: errors.New(`ent: missing required field "TunnelProfile.edge"`)}
	}
	if _, ok := _c.mutation.PostQuantum(); !ok {
		return &ValidationError{Name: "post_quantum", err: errors.New(`ent: missing required field "TunnelProfile.post_quantum"`)}
	}
	if _, ok := _c.mutation.NoTLSVerify(); !ok {
		return &ValidationError{Name: "no_tls_verify", err: errors.New(`ent: missing required field "TunnelProfile.no_tls_verify"`)}
	}
	if _, ok := _c.mutation.ExtraArgs(); !ok {
		return &ValidationError{Name: "extra_args", err: errors.New(`ent: missing required field "TunnelProfile.extra_args"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TunnelProfile.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TunnelProfile.updated_at"`)}
	}
	return nil
}

func (_c *TunnelProfileCreate) sqlSave(ctx context.Context) (*TunnelProfile, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TunnelProfileCreate) createSpec() (*TunnelProfile, *sqlgraph.CreateSpec) {
	var (
		_node = &TunnelProfile{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tunnelprofile.Table, sqlgraph.NewFieldSpec(tunnelprofile.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(tunnelprofile.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(tunnelprofile.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(tunnelprofile.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.Token(); ok {
		_spec.SetField(tunnelprofile.FieldToken, field.TypeString, value)
		_node.Token = value
	}
	if value, ok := _c.mutation.LocalEnabled(); ok {
		_spec.SetField(tunnelprofile.FieldLocalEnabled, field.TypeBool, value)
		_node.LocalEnabled = value
	}
	if value, ok := _c.mutation.RemoteManagementEnabled(); ok {
		_spec.SetField(tunnelprofile.FieldRemoteManagementEnabled, field.TypeBool, value)
		_node.RemoteManagementEnabled = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(tunnelprofile.FieldAccountID, field.TypeString, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.TunnelID(); ok {
		_spec.SetField(tunnelprofile.FieldTunnelID, field.TypeString, value)
		_node.TunnelID = value
	}
	if value, ok := _c.mutation.AutoStart(); ok {
		_spec.SetField(tunnelprofile.FieldAutoStart, field.TypeBool, value)
		_node.AutoStart = value
	}
	if value, ok := _c.mutation.AutoRestart(); ok {
		_spec.SetField(tunnelprofile.FieldAutoRestart, field.TypeBool, value)
		_node.AutoRestart = value
	}
	if value, ok := _c.mutation.CustomTag(); ok {
		_spec.SetField(tunnelprofile.FieldCustomTag, field.TypeString, value)
		_node.CustomTag = value
	}
	if value, ok := _c.mutation.SoftwareName(); ok {
		_spec.SetField(tunnelprofile.FieldSoftwareName, field.TypeString, value)
		_node.SoftwareName = value
	}
	if value, ok := _c.mutation.Protocol(); ok {
		_spec.SetField(tunnelprofile.FieldProtocol, field.TypeString, value)
		_node.Protocol = value
	}
	if value, ok := _c.mutation.GracePeriod(); ok {
		_spec.SetField(tunnelprofile.FieldGracePeriod, field.TypeString, value)
		_node.GracePeriod = value
	}
	if value, ok := _c.mutation.Region(); ok {
		_spec.SetField(tunnelprofile.FieldRegion, field.TypeString, value)
		_node.Region = value
	}
	if value, ok := _c.mutation.Retries(); ok {
		_spec.SetField(tunnelprofile.FieldRetries, field.TypeInt, value)
		_node.Retries = value
	}
	if value, ok := _c.mutation.MetricsEnable(); ok {
		_spec.SetField(tunnelprofile.FieldMetricsEnable, field.TypeBool, value)
		_node.MetricsEnable = value
	}
	if value, ok := _c.mutation.MetricsPort(); ok {
		_spec.SetField(tunnelprofile.FieldMetricsPort, field.TypeInt, value)
		_node.MetricsPort = value
	}
	if value, ok := _c.mutation.LogLevel(); ok {
		_spec.SetField(tunnelprofile.FieldLogLevel, field.TypeString, value)
		_node.LogLevel = value
	}
	if value, ok := _c.mutation.LogFile(); ok {
		_spec.SetField(tunnelprofile.FieldLogFile, field.TypeString, value)
		_node.LogFile = value
	}
	if value, ok := _c.mutation.LogJSON(); ok {
		_spec.SetField(tunnelprofile.FieldLogJSON, field.TypeBool, value)
		_node.LogJSON = value
	}
	if value, ok := _c.mutation.EdgeIPVersion(); ok {
		_spec.SetField(tunnelprofile.FieldEdgeIPVersion, field.TypeString, value)
		_node.EdgeIPVersion = value
	}
	if value, ok := _c.mutation.EdgeBindAddress(); ok {
		_spec.SetField(tunnelprofile.FieldEdgeBindAddress, field.TypeString, value)
		_node.EdgeBindAddress = value
	}
	if value, ok := _c.mutation.Edge(); ok {
		_spec.SetField(tunnelprofile.FieldEdge, field.TypeString, value)
		_node.Edge = value
	}
	if value, ok := _c.mutation.PostQuantum(); ok {
		_spec.SetField(tunnelprofile.FieldPostQuantum, field.TypeBool, value)
		_node.PostQuantum = value
	}
	if value, ok := _c.mutation.NoTLSVerify(); ok {
		_spec.SetField(tunnelprofile.FieldNoTLSVerify, field.TypeBool, value)
		_node.NoTLSVerify = value
	}
	if value, ok := _c.mutation.ExtraArgs(); ok {
		_spec.SetField(tunnelprofile.FieldExtraArgs, field.TypeString, value)
		_node.ExtraArgs = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(tunnelprofile.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(tunnelprofile.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// TunnelProfileCreateBulk is the builder for creating many TunnelProfile entities in bulk.
type TunnelProfileCreateBulk struct {
	config
	err      error
	builders []*TunnelProfileCreate
}

// Save creates the TunnelProfile entities in the database.
func (_c *TunnelProfileCreateBulk) Save(ctx context.Context) ([]*TunnelProfile, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TunnelProfile, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TunnelProfileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TunnelProfileCreateBulk) SaveX(ctx context.Context) []*TunnelProfile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TunnelProfileCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TunnelProfileCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
