// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cfui/internal/persist/ent/predicate"
	"cfui/internal/persist/ent/tunnelprofile"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TunnelProfileUpdate is the builder for updating TunnelProfile entities.
type TunnelProfileUpdate struct {
	config
	hooks    []Hook
	mutation *TunnelProfileMutation
}

// Where appends a list predicates to the TunnelProfileUpdate builder.
func (_u *TunnelProfileUpdate) Where(ps ...predicate.TunnelProfile) *TunnelProfileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKey sets the "key" field.
func (_u *TunnelProfileUpdate) SetKey(v string) *TunnelProfileUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *TunnelProfileUpdate) SetNillableKey(v *string) *TunnelProfileUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *TunnelProfileUpdate) SetName(v string) *TunnelProfileUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TunnelProfileUpdate) SetNillableName(v *string) *TunnelProfileUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *TunnelProfileUpdate) SetSortOrder(v int) *TunnelProfileUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *TunnelProfileUpdate) SetNillableSortOrder(v *int) *TunnelProfileUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *TunnelProfileUpdate) AddSortOrder(v int) *TunnelProfileUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetToken sets the "token" field.
func (_u *TunnelProfileUpdate) SetToken(v string) *TunnelProfileUpdate {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *TunnelProfileUpdate) SetNillableToken(v *string) *TunnelProfileUpdate {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetLocalEnabled sets the "local_enabled" field.
func (_u *TunnelProfileUpdate) SetLocalEnabled(v bool) *TunnelProfileUpdate {
	_u.mutation.SetLocalEnabled(v)
	return _u
}

// SetNillableLocalEnabled sets the "local_enabled" field if the given value is not nil.
func (_u *TunnelProfileUpdate) SetNillableLocalEnabled(v *bool) *TunnelProfileUpdate {
	if v != nil {
		_u.SetLocalEnabled(*v)
	}
	return _u
}

// SetRemoteManagementEnabled sets the "remote_management_enabled" field.
func (_u *TunnelProfileUpdate) SetRemoteManagementEnabled(v bool) *TunnelProfileUpdate {
	_u.mutation.SetRemoteManagementEnabled(v)
	return _u
}

// SetNillableRemoteManagementEnabled sets the "remote_management_enabled" field if the given value is not nil.
func (_u *TunnelProfileUpdate) SetNillableRemoteManagementEnabled(v *bool) *TunnelProfileUpdate {
	if v != nil {
		_u.SetRemoteManagementEnabled(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *TunnelProfileUpdate) SetAccountID(v string) *TunnelProfileUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *TunnelProfileUpdate) SetNillableAccountID(v *string) *TunnelProfileUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetTunnelID sets the "tunnel_id" field.
func (_u *TunnelProfileUpdate) SetTunnelID(v string) *TunnelProfileUpdate {
	_u.mutation.SetTunnelID(v)
	return _u
}

// SetNillableTunnelID sets the "tunnel_id" field if the given value is not nil.
func (_u *TunnelProfileUpdate) SetNillableTunnelID(v *string) *TunnelProfileUpdate {
	if v != nil {
		_u.SetTunnelID(*v)
	}
	return _u
}

// SetAutoStart sets the "auto_start" field.
func (_u *TunnelProfileUpdate) SetAutoStart(v bool) *TunnelProfileUpdate {
	_u.mutation.SetAutoStart(v)
	return _u
}

// SetNillableAutoStart sets the "auto_start" field if the given value is not nil.
func (_u *TunnelProfileUpdate) SetNillableAutoStart(v *bool) *TunnelProfileUpdate {
	if v != nil {
		_u.SetAutoStart(*v)
	}
	return _u
}

// SetAutoRestart sets the "auto_restart" field.
func (_u *TunnelProfileUpdate) SetAutoRestart(v bool) *TunnelProfileUpdate {
	_u.mutation.SetAutoRestart(v)
	return _u
}

// SetNillableAutoRestart sets the "auto_restart" field if the given value is not nil.
func (_u *TunnelProfileUpdate) SetNillableAutoRestart(v *bool) *TunnelProfileUpdate {
	if v != nil {
		_u.SetAutoRestart(*v)
	}
	return _u
}

// SetCustomTag sets the "custom_tag" field.
func (_u *TunnelProfileUpdate) SetCustomTag(v string) *TunnelProfileUpdate {
	_u.mutation.SetCustomTag(v)
	return _u
}

// SetNillableCustomTag sets the "custom_tag" field if the given value is not nil.
func (_u *TunnelProfileUpdate) SetNillableCustomTag(v *string) *TunnelProfileUpdate {
	if v != nil {
		_u.SetCustomTag(*v)
	}
	return _u
}

// SetSoftwareName sets the "software_name" field.
func (_u *TunnelProfileUpdate) SetSoftwareName(v string) *TunnelProfileUpdate {
	_u.mutation.SetSoftwareName(v)
	return _u
}

// SetNillableSoftwareName sets the "software_name" field if the given value is not nil.
func (_u *TunnelProfileUpdate) SetNillableSoftwareName(v *string) *TunnelProfileUpdate {
	if v != nil {
		_u.SetSoftwareName(*v)
	}
	return _u
}

// SetProtocol sets the "protocol" field.
func (_u *TunnelProfileUpdate) SetProtocol(v string) *TunnelProfileUpdate {
	_u.mutation.SetProtocol(v)
	return _u
}

// SetNillableProtocol sets the "protocol" field if the given value is not nil.
func (_u *TunnelProfileUpdate) SetNillableProtocol(v *string) *TunnelProfileUpdate {
	if v != nil {
		_u.SetProtocol(*v)
	}
	return _u
}

// SetGracePeriod sets the "grace_period" field.
func (_u *TunnelProfileUpdate) SetGracePeriod(v string) *TunnelProfileUpdate {
	_u.mutation.SetGracePeriod(v)
	return _u
}

// SetNillableGracePeriod sets the "grace_period" field if the given value is not nil.
func (_u *TunnelProfileUpdate) SetNillableGracePeriod(v *string) *TunnelProfileUpdate {
	if v != nil {
		_u.SetGracePeriod(*v)
	}
	return _u
}

// SetRegion sets the "region" field.
func (_u *TunnelProfileUpdate) SetRegion(v string) *TunnelProfileUpdate {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *TunnelProfileUpdate) SetNillableRegion(v *string) *TunnelProfileUpdate {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// SetRetries sets the "retries" field.
func (_u *TunnelProfileUpdate) SetRetries(v int) *TunnelProfileUpdate {
	_u.mutation.ResetRetries()
	_u.mutation.SetRetries(v)
	return _u
}

// SetNillableRetries sets the "retries" field if the given value is not nil.
func (_u *TunnelProfileUpdate) SetNillableRetries(v *int) *TunnelProfileUpdate {
	if v != nil {
		_u.SetRetries(*v)
	}
	return _u
}

// AddRetries adds value to the "retries" field.
func (_u *TunnelProfileUpdate) AddRetries(v int) *TunnelProfileUpdate {
	_u.mutation.AddRetries(v)
	return _u
}

// SetMetricsEnable sets the "metrics_enable" field.
func (_u *TunnelProfileUpdate) SetMetricsEnable(v bool) *TunnelProfileUpdate {
	_u.mutation.SetMetricsEnable(v)
	return _u
}

// SetNillableMetricsEnable sets the "metrics_enable" field if the given value is not nil.
func (_u *TunnelProfileUpdate) SetNillableMetricsEnable(v *bool) *TunnelProfileUpdate {
	if v != nil {
		_u.SetMetricsEnable(*v)
	}
	return _u
}

// SetMetricsPort sets the "metrics_port" field.
func (_u *TunnelProfileUpdate) SetMetricsPort(v int) *TunnelProfileUpdate {
	_u.mutation.ResetMetricsPort()
	_u.mutation.SetMetricsPort(v)
	return _u
}

// SetNillableMetricsPort sets the "metrics_port" field if the given value is not nil.
func (_u *TunnelProfileUpdate) SetNillableMetricsPort(v *int) *TunnelProfileUpdate {
	if v != nil {
		_u.SetMetricsPort(*v)
	}
	return _u
}

// AddMetricsPort adds value to the "metrics_port" field.
func (_u *TunnelProfileUpdate) AddMetricsPort(v int) *TunnelProfileUpdate {
	_u.mutation.AddMetricsPort(v)
	return _u
}

// SetLogLevel sets the "log_level" field.
func (_u *TunnelProfileUpdate) SetLogLevel(v string) *TunnelProfileUpdate {
	_u.mutation.SetLogLevel(v)
	return _u
}

// SetNillableLogLevel sets the "log_level" field if the given value is not nil.
func (_u *TunnelProfileUpdate) SetNillableLogLevel(v *string) *TunnelProfileUpdate {
	if v != nil {
		_u.SetLogLevel(*v)
	}
	return _u
}

// SetLogFile sets the "log_file" field.
func (_u *TunnelProfileUpdate) SetLogFile(v string) *TunnelProfileUpdate {
	_u.mutation.SetLogFile(v)
	return _u
}

// SetNillableLogFile sets the "log_file" field if the given value is not nil.
func (_u *TunnelProfileUpdate) SetNillableLogFile(v *string) *TunnelProfileUpdate {
	if v != nil {
		_u.SetLogFile(*v)
	}
	return _u
}

// SetLogJSON sets the "log_json" field.
func (_u *TunnelProfileUpdate) SetLogJSON(v bool) *TunnelProfileUpdate {
	_u.mutation.SetLogJSON(v)
	return _u
}

// SetNillableLogJSON sets the "log_json" field if the given value is not nil.
func (_u *TunnelProfileUpdate) SetNillableLogJSON(v *bool) *TunnelProfileUpdate {
	if v != nil {
		_u.SetLogJSON(*v)
	}
	return _u
}

// SetEdgeIPVersion sets the "edge_ip_version" field.
func (_u *TunnelProfileUpdate) SetEdgeIPVersion(v string) *TunnelProfileUpdate {
	_u.mutation.SetEdgeIPVersion(v)
	return _u
}

// SetNillableEdgeIPVersion sets the "edge_ip_version" field if the given value is not nil.
func (_u *TunnelProfileUpdate) SetNillableEdgeIPVersion(v *string) *TunnelProfileUpdate {
	if v != nil {
		_u.SetEdgeIPVersion(*v)
	}
	return _u
}

// SetEdgeBindAddress sets the "edge_bind_address" field.
func (_u *TunnelProfileUpdate) SetEdgeBindAddress(v string) *TunnelProfileUpdate {
	_u.mutation.SetEdgeBindAddress(v)
	return _u
}

// SetNillableEdgeBindAddress sets the "edge_bind_address" field if the given value is not nil.
func (_u *TunnelProfileUpdate) SetNillableEdgeBindAddress(v *string) *TunnelProfileUpdate {
	if v != nil {
		_u.SetEdgeBindAddress(*v)
	}
	return _u
}

// SetEdge sets the "edge" field.
func (_u *TunnelProfileUpdate) SetEdge(v string) *TunnelProfileUpdate {
	_u.mutation.SetEdge(v)
	return _u
}

// SetNillableEdge sets the "edge" field if the given value is not nil.
func (_u *TunnelProfileUpdate) SetNillableEdge(v *string) *TunnelProfileUpdate {
	if v != nil {
		_u.SetEdge(*v)
	}
	return _u
}

// SetPostQuantum sets the "post_quantum" field.
func (_u *TunnelProfileUpdate) SetPostQuantum(v bool) *TunnelProfileUpdate {
	_u.mutation.SetPostQuantum(v)
	return _u
}

// SetNillablePostQuantum sets the "post_quantum" field if the given value is not nil.
func (_u *TunnelProfileUpdate) SetNillablePostQuantum(v *bool) *TunnelProfileUpdate {
	if v != nil {
		_u.SetPostQuantum(*v)
	}
	return _u
}

// SetNoTLSVerify sets the "no_tls_verify" field.
func (_u *TunnelProfileUpdate) SetNoTLSVerify(v bool) *TunnelProfileUpdate {
	_u.mutation.SetNoTLSVerify(v)
	return _u
}

// SetNillableNoTLSVerify sets the "no_tls_verify" field if the given value is not nil.
func (_u *TunnelProfileUpdate) SetNillableNoTLSVerify(v *bool) *TunnelProfileUpdate {
	if v != nil {
		_u.SetNoTLSVerify(*v)
	}
	return _u
}

// SetExtraArgs sets the "extra_args" field.
func (_u *TunnelProfileUpdate) SetExtraArgs(v string) *TunnelProfileUpdate {
	_u.mutation.SetExtraArgs(v)
	return _u
}

// SetNillableExtraArgs sets the "extra_args" field if the given value is not nil.
func (_u *TunnelProfileUpdate) SetNillableExtraArgs(v *string) *TunnelProfileUpdate {
	if v != nil {
		_u.SetExtraArgs(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TunnelProfileUpdate) SetUpdatedAt(v time.Time) *TunnelProfileUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the TunnelProfileMutation object of the builder.
func (_u *TunnelProfileUpdate) Mutation() *TunnelProfileMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TunnelProfileUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TunnelProfileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TunnelProfileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TunnelProfileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TunnelProfileUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tunnelprofile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TunnelProfileUpdate) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := tunnelprofile.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "TunnelProfile.key": %w`, err)}
		}
	}
	return nil
}

func (_u *TunnelProfileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tunnelprofile.Table, tunnelprofile.Columns, sqlgraph.NewFieldSpec(tunnelprofile.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(tunnelprofile.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tunnelprofile.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(tunnelprofile.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(tunnelprofile.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(tunnelprofile.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.LocalEnabled(); ok {
		_spec.SetField(tunnelprofile.FieldLocalEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RemoteManagementEnabled(); ok {
		_spec.SetField(tunnelprofile.FieldRemoteManagementEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(tunnelprofile.FieldAccountID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TunnelID(); ok {
		_spec.SetField(tunnelprofile.FieldTunnelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AutoStart(); ok {
		_spec.SetField(tunnelprofile.FieldAutoStart, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AutoRestart(); ok {
		_spec.SetField(tunnelprofile.FieldAutoRestart, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CustomTag(); ok {
		_spec.SetField(tunnelprofile.FieldCustomTag, field.TypeString, value)
	}
	if value, ok := _u.mutation.SoftwareName(); ok {
		_spec.SetField(tunnelprofile.FieldSoftwareName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Protocol(); ok {
		_spec.SetField(tunnelprofile.FieldProtocol, field.TypeString, value)
	}
	if value, ok := _u.mutation.GracePeriod(); ok {
		_spec.SetField(tunnelprofile.FieldGracePeriod, field.TypeString, value)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(tunnelprofile.FieldRegion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Retries(); ok {
		_spec.SetField(tunnelprofile.FieldRetries, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetries(); ok {
		_spec.AddField(tunnelprofile.FieldRetries, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MetricsEnable(); ok {
		_spec.SetField(tunnelprofile.FieldMetricsEnable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MetricsPort(); ok {
		_spec.SetField(tunnelprofile.FieldMetricsPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMetricsPort(); ok {
		_spec.AddField(tunnelprofile.FieldMetricsPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LogLevel(); ok {
		_spec.SetField(tunnelprofile.FieldLogLevel, field.TypeString, value)
	}
	if value, ok := _u.mutation.LogFile(); ok {
		_spec.SetField(tunnelprofile.FieldLogFile, field.TypeString, value)
	}
	if value, ok := _u.mutation.LogJSON(); ok {
		_spec.SetField(tunnelprofile.FieldLogJSON, field.TypeBool, value)
	}
	if value, ok := _u.mutation.EdgeIPVersion(); ok {
		_spec.SetField(tunnelprofile.FieldEdgeIPVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.EdgeBindAddress(); ok {
		_spec.SetField(tunnelprofile.FieldEdgeBindAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Edge(); ok {
		_spec.SetField(tunnelprofile.FieldEdge, field.TypeString, value)
	}
	if value, ok := _u.mutation.PostQuantum(); ok {
		_spec.SetField(tunnelprofile.FieldPostQuantum, field.TypeBool, value)
	}
	if value, ok := _u.mutation.NoTLSVerify(); ok {
		_spec.SetField(tunnelprofile.FieldNoTLSVerify, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ExtraArgs(); ok {
		_spec.SetField(tunnelprofile.FieldExtraArgs, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tunnelprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tunnelprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TunnelProfileUpdateOne is the builder for updating a single TunnelProfile entity.
type TunnelProfileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TunnelProfileMutation
}

// SetKey sets the "key" field.
func (_u *TunnelProfileUpdateOne) SetKey(v string) *TunnelProfileUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *TunnelProfileUpdateOne) SetNillableKey(v *string) *TunnelProfileUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *TunnelProfileUpdateOne) SetName(v string) *TunnelProfileUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TunnelProfileUpdateOne) SetNillableName(v *string) *TunnelProfileUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *TunnelProfileUpdateOne) SetSortOrder(v int) *TunnelProfileUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *TunnelProfileUpdateOne) SetNillableSortOrder(v *int) *TunnelProfileUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *TunnelProfileUpdateOne) AddSortOrder(v int) *TunnelProfileUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetToken sets the "token" field.
func (_u *TunnelProfileUpdateOne) SetToken(v string) *TunnelProfileUpdateOne {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *TunnelProfileUpdateOne) SetNillableToken(v *string) *TunnelProfileUpdateOne {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetLocalEnabled sets the "local_enabled" field.
func (_u *TunnelProfileUpdateOne) SetLocalEnabled(v bool) *TunnelProfileUpdateOne {
	_u.mutation.SetLocalEnabled(v)
	return _u
}

// SetNillableLocalEnabled sets the "local_enabled" field if the given value is not nil.
func (_u *TunnelProfileUpdateOne) SetNillableLocalEnabled(v *bool) *TunnelProfileUpdateOne {
	if v != nil {
		_u.SetLocalEnabled(*v)
	}
	return _u
}

// SetRemoteManagementEnabled sets the "remote_management_enabled" field.
func (_u *TunnelProfileUpdateOne) SetRemoteManagementEnabled(v bool) *TunnelProfileUpdateOne {
	_u.mutation.SetRemoteManagementEnabled(v)
	return _u
}

// SetNillableRemoteManagementEnabled sets the "remote_management_enabled" field if the given value is not nil.
func (_u *TunnelProfileUpdateOne) SetNillableRemoteManagementEnabled(v *bool) *TunnelProfileUpdateOne {
	if v != nil {
		_u.SetRemoteManagementEnabled(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *TunnelProfileUpdateOne) SetAccountID(v string) *TunnelProfileUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *TunnelProfileUpdateOne) SetNillableAccountID(v *string) *TunnelProfileUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetTunnelID sets the "tunnel_id" field.
func (_u *TunnelProfileUpdateOne) SetTunnelID(v string) *TunnelProfileUpdateOne {
	_u.mutation.SetTunnelID(v)
	return _u
}

// SetNillableTunnelID sets the "tunnel_id" field if the given value is not nil.
func (_u *TunnelProfileUpdateOne) SetNillableTunnelID(v *string) *TunnelProfileUpdateOne {
	if v != nil {
		_u.SetTunnelID(*v)
	}
	return _u
}

// SetAutoStart sets the "auto_start" field.
func (_u *TunnelProfileUpdateOne) SetAutoStart(v bool) *TunnelProfileUpdateOne {
	_u.mutation.SetAutoStart(v)
	return _u
}

// SetNillableAutoStart sets the "auto_start" field if the given value is not nil.
func (_u *TunnelProfileUpdateOne) SetNillableAutoStart(v *bool) *TunnelProfileUpdateOne {
	if v != nil {
		_u.SetAutoStart(*v)
	}
	return _u
}

// SetAutoRestart sets the "auto_restart" field.
func (_u *TunnelProfileUpdateOne) SetAutoRestart(v bool) *TunnelProfileUpdateOne {
	_u.mutation.SetAutoRestart(v)
	return _u
}

// SetNillableAutoRestart sets the "auto_restart" field if the given value is not nil.
func (_u *TunnelProfileUpdateOne) SetNillableAutoRestart(v *bool) *TunnelProfileUpdateOne {
	if v != nil {
		_u.SetAutoRestart(*v)
	}
	return _u
}

// SetCustomTag sets the "custom_tag" field.
func (_u *TunnelProfileUpdateOne) SetCustomTag(v string) *TunnelProfileUpdateOne {
	_u.mutation.SetCustomTag(v)
	return _u
}

// SetNillableCustomTag sets the "custom_tag" field if the given value is not nil.
func (_u *TunnelProfileUpdateOne) SetNillableCustomTag(v *string) *TunnelProfileUpdateOne {
	if v != nil {
		_u.SetCustomTag(*v)
	}
	return _u
}

// SetSoftwareName sets the "software_name" field.
func (_u *TunnelProfileUpdateOne) SetSoftwareName(v string) *TunnelProfileUpdateOne {
	_u.mutation.SetSoftwareName(v)
	return _u
}

// SetNillableSoftwareName sets the "software_name" field if the given value is not nil.
func (_u *TunnelProfileUpdateOne) SetNillableSoftwareName(v *string) *TunnelProfileUpdateOne {
	if v != nil {
		_u.SetSoftwareName(*v)
	}
	return _u
}

// SetProtocol sets the "protocol" field.
func (_u *TunnelProfileUpdateOne) SetProtocol(v string) *TunnelProfileUpdateOne {
	_u.mutation.SetProtocol(v)
	return _u
}

// SetNillableProtocol sets the "protocol" field if the given value is not nil.
func (_u *TunnelProfileUpdateOne) SetNillableProtocol(v *string) *TunnelProfileUpdateOne {
	if v != nil {
		_u.SetProtocol(*v)
	}
	return _u
}

// SetGracePeriod sets the "grace_period" field.
func (_u *TunnelProfileUpdateOne) SetGracePeriod(v string) *TunnelProfileUpdateOne {
	_u.mutation.SetGracePeriod(v)
	return _u
}

// SetNillableGracePeriod sets the "grace_period" field if the given value is not nil.
func (_u *TunnelProfileUpdateOne) SetNillableGracePeriod(v *string) *TunnelProfileUpdateOne {
	if v != nil {
		_u.SetGracePeriod(*v)
	}
	return _u
}

// SetRegion sets the "region" field.
func (_u *TunnelProfileUpdateOne) SetRegion(v string) *TunnelProfileUpdateOne {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *TunnelProfileUpdateOne) SetNillableRegion(v *string) *TunnelProfileUpdateOne {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// SetRetries sets the "retries" field.
func (_u *TunnelProfileUpdateOne) SetRetries(v int) *TunnelProfileUpdateOne {
	_u.mutation.ResetRetries()
	_u.mutation.SetRetries(v)
	return _u
}

// SetNillableRetries sets the "retries" field if the given value is not nil.
func (_u *TunnelProfileUpdateOne) SetNillableRetries(v *int) *TunnelProfileUpdateOne {
	if v != nil {
		_u.SetRetries(*v)
	}
	return _u
}

// AddRetries adds value to the "retries" field.
func (_u *TunnelProfileUpdateOne) AddRetries(v int) *TunnelProfileUpdateOne {
	_u.mutation.AddRetries(v)
	return _u
}

// SetMetricsEnable sets the "metrics_enable" field.
func (_u *TunnelProfileUpdateOne) SetMetricsEnable(v bool) *TunnelProfileUpdateOne {
	_u.mutation.SetMetricsEnable(v)
	return _u
}

// SetNillableMetricsEnable sets the "metrics_enable" field if the given value is not nil.
func (_u *TunnelProfileUpdateOne) SetNillableMetricsEnable(v *bool) *TunnelProfileUpdateOne {
	if v != nil {
		_u.SetMetricsEnable(*v)
	}
	return _u
}

// SetMetricsPort sets the "metrics_port" field.
func (_u *TunnelProfileUpdateOne) SetMetricsPort(v int) *TunnelProfileUpdateOne {
	_u.mutation.ResetMetricsPort()
	_u.mutation.SetMetricsPort(v)
	return _u
}

// SetNillableMetricsPort sets the "metrics_port" field if the given value is not nil.
func (_u *TunnelProfileUpdateOne) SetNillableMetricsPort(v *int) *TunnelProfileUpdateOne {
	if v != nil {
		_u.SetMetricsPort(*v)
	}
	return _u
}

// AddMetricsPort adds value to the "metrics_port" field.
func (_u *TunnelProfileUpdateOne) AddMetricsPort(v int) *TunnelProfileUpdateOne {
	_u.mutation.AddMetricsPort(v)
	return _u
}

// SetLogLevel sets the "log_level" field.
func (_u *TunnelProfileUpdateOne) SetLogLevel(v string) *TunnelProfileUpdateOne {
	_u.mutation.SetLogLevel(v)
	return _u
}

// SetNillableLogLevel sets the "log_level" field if the given value is not nil.
func (_u *TunnelProfileUpdateOne) SetNillableLogLevel(v *string) *TunnelProfileUpdateOne {
	if v != nil {
		_u.SetLogLevel(*v)
	}
	return _u
}

// SetLogFile sets the "log_file" field.
func (_u *TunnelProfileUpdateOne) SetLogFile(v string) *TunnelProfileUpdateOne {
	_u.mutation.SetLogFile(v)
	return _u
}

// SetNillableLogFile sets the "log_file" field if the given value is not nil.
func (_u *TunnelProfileUpdateOne) SetNillableLogFile(v *string) *TunnelProfileUpdateOne {
	if v != nil {
		_u.SetLogFile(*v)
	}
	return _u
}

// SetLogJSON sets the "log_json" field.
func (_u *TunnelProfileUpdateOne) SetLogJSON(v bool) *TunnelProfileUpdateOne {
	_u.mutation.SetLogJSON(v)
	return _u
}

// SetNillableLogJSON sets the "log_json" field if the given value is not nil.
func (_u *TunnelProfileUpdateOne) SetNillableLogJSON(v *bool) *TunnelProfileUpdateOne {
	if v != nil {
		_u.SetLogJSON(*v)
	}
	return _u
}

// SetEdgeIPVersion sets the "edge_ip_version" field.
func (_u *TunnelProfileUpdateOne) SetEdgeIPVersion(v string) *TunnelProfileUpdateOne {
	_u.mutation.SetEdgeIPVersion(v)
	return _u
}

// SetNillableEdgeIPVersion sets the "edge_ip_version" field if the given value is not nil.
func (_u *TunnelProfileUpdateOne) SetNillableEdgeIPVersion(v *string) *TunnelProfileUpdateOne {
	if v != nil {
		_u.SetEdgeIPVersion(*v)
	}
	return _u
}

// SetEdgeBindAddress sets the "edge_bind_address" field.
func (_u *TunnelProfileUpdateOne) SetEdgeBindAddress(v string) *TunnelProfileUpdateOne {
	_u.mutation.SetEdgeBindAddress(v)
	return _u
}

// SetNillableEdgeBindAddress sets the "edge_bind_address" field if the given value is not nil.
func (_u *TunnelProfileUpdateOne) SetNillableEdgeBindAddress(v *string) *TunnelProfileUpdateOne {
	if v != nil {
		_u.SetEdgeBindAddress(*v)
	}
	return _u
}

// SetEdge sets the "edge" field.
func (_u *TunnelProfileUpdateOne) SetEdge(v string) *TunnelProfileUpdateOne {
	_u.mutation.SetEdge(v)
	return _u
}

// SetNillableEdge sets the "edge" field if the given value is not nil.
func (_u *TunnelProfileUpdateOne) SetNillableEdge(v *string) *TunnelProfileUpdateOne {
	if v != nil {
		_u.SetEdge(*v)
	}
	return _u
}

// SetPostQuantum sets the "post_quantum" field.
func (_u *TunnelProfileUpdateOne) SetPostQuantum(v bool) *TunnelProfileUpdateOne {
	_u.mutation.SetPostQuantum(v)
	return _u
}

// SetNillablePostQuantum sets the "post_quantum" field if the given value is not nil.
func (_u *TunnelProfileUpdateOne) SetNillablePostQuantum(v *bool) *TunnelProfileUpdateOne {
	if v != nil {
		_u.SetPostQuantum(*v)
	}
	return _u
}

// SetNoTLSVerify sets the "no_tls_verify" field.
func (_u *TunnelProfileUpdateOne) SetNoTLSVerify(v bool) *TunnelProfileUpdateOne {
	_u.mutation.SetNoTLSVerify(v)
	return _u
}

// SetNillableNoTLSVerify sets the "no_tls_verify" field if the given value is not nil.
func (_u *TunnelProfileUpdateOne) SetNillableNoTLSVerify(v *bool) *TunnelProfileUpdateOne {
	if v != nil {
		_u.SetNoTLSVerify(*v)
	}
	return _u
}

// SetExtraArgs sets the "extra_args" field.
func (_u *TunnelProfileUpdateOne) SetExtraArgs(v string) *TunnelProfileUpdateOne {
	_u.mutation.SetExtraArgs(v)
	return _u
}

// SetNillableExtraArgs sets the "extra_args" field if the given value is not nil.
func (_u *TunnelProfileUpdateOne) SetNillableExtraArgs(v *string) *TunnelProfileUpdateOne {
	if v != nil {
		_u.SetExtraArgs(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TunnelProfileUpdateOne) SetUpdatedAt(v time.Time) *TunnelProfileUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the TunnelProfileMutation object of the builder.
func (_u *TunnelProfileUpdateOne) Mutation() *TunnelProfileMutation {
	return _u.mutation
}

// Where appends a list predicates to the TunnelProfileUpdate builder.
func (_u *TunnelProfileUpdateOne) Where(ps ...predicate.TunnelProfile) *TunnelProfileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TunnelProfileUpdateOne) Select(field string, fields ...string) *TunnelProfileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TunnelProfile entity.
func (_u *TunnelProfileUpdateOne) Save(ctx context.Context) (*TunnelProfile, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TunnelProfileUpdateOne) SaveX(ctx context.Context) *TunnelProfile {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TunnelProfileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TunnelProfileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TunnelProfileUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tunnelprofile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TunnelProfileUpdateOne) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := tunnelprofile.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "TunnelProfile.key": %w`, err)}
		}
	}
	return nil
}

func (_u *TunnelProfileUpdateOne) sqlSave(ctx context.Context) (_node *TunnelProfile, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tunnelprofile.Table, tunnelprofile.Columns, sqlgraph.NewFieldSpec(tunnelprofile.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TunnelProfile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tunnelprofile.FieldID)
		for _, f := range fields {
			if !tunnelprofile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tunnelprofile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(tunnelprofile.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tunnelprofile.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(tunnelprofile.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(tunnelprofile.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(tunnelprofile.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.LocalEnabled(); ok {
		_spec.SetField(tunnelprofile.FieldLocalEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RemoteManagementEnabled(); ok {
		_spec.SetField(tunnelprofile.FieldRemoteManagementEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(tunnelprofile.FieldAccountID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TunnelID(); ok {
		_spec.SetField(tunnelprofile.FieldTunnelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AutoStart(); ok {
		_spec.SetField(tunnelprofile.FieldAutoStart, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AutoRestart(); ok {
		_spec.SetField(tunnelprofile.FieldAutoRestart, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CustomTag(); ok {
		_spec.SetField(tunnelprofile.FieldCustomTag, field.TypeString, value)
	}
	if value, ok := _u.mutation.SoftwareName(); ok {
		_spec.SetField(tunnelprofile.FieldSoftwareName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Protocol(); ok {
		_spec.SetField(tunnelprofile.FieldProtocol, field.TypeString, value)
	}
	if value, ok := _u.mutation.GracePeriod(); ok {
		_spec.SetField(tunnelprofile.FieldGracePeriod, field.TypeString, value)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(tunnelprofile.FieldRegion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Retries(); ok {
		_spec.SetField(tunnelprofile.FieldRetries, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetries(); ok {
		_spec.AddField(tunnelprofile.FieldRetries, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MetricsEnable(); ok {
		_spec.SetField(tunnelprofile.FieldMetricsEnable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MetricsPort(); ok {
		_spec.SetField(tunnelprofile.FieldMetricsPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMetricsPort(); ok {
		_spec.AddField(tunnelprofile.FieldMetricsPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LogLevel(); ok {
		_spec.SetField(tunnelprofile.FieldLogLevel, field.TypeString, value)
	}
	if value, ok := _u.mutation.LogFile(); ok {
		_spec.SetField(tunnelprofile.FieldLogFile, field.TypeString, value)
	}
	if value, ok := _u.mutation.LogJSON(); ok {
		_spec.SetField(tunnelprofile.FieldLogJSON, field.TypeBool, value)
	}
	if value, ok := _u.mutation.EdgeIPVersion(); ok {
		_spec.SetField(tunnelprofile.FieldEdgeIPVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.EdgeBindAddress(); ok {
		_spec.SetField(tunnelprofile.FieldEdgeBindAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Edge(); ok {
		_spec.SetField(tunnelprofile.FieldEdge, field.TypeString, value)
	}
	if value, ok := _u.mutation.PostQuantum(); ok {
		_spec.SetField(tunnelprofile.FieldPostQuantum, field.TypeBool, value)
	}
	if value, ok := _u.mutation.NoTLSVerify(); ok {
		_spec.SetField(tunnelprofile.FieldNoTLSVerify, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ExtraArgs(); ok {
		_spec.SetField(tunnelprofile.FieldExtraArgs, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tunnelprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &TunnelProfile{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tunnelprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
