// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cfui/internal/persist/ent/tunnelprofile"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// TunnelProfile is the model entity for the TunnelProfile schema.
type TunnelProfile struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Key holds the value of the "key" field.
	Key string `json:"key,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder int `json:"sort_order,omitempty"`
	// Token holds the value of the "token" field.
	Token string `json:"-"`
	// LocalEnabled holds the value of the "local_enabled" field.
	LocalEnabled bool `json:"local_enabled,omitempty"`
	// RemoteManagementEnabled holds the value of the "remote_management_enabled" field.
	RemoteManagementEnabled bool `json:"remote_management_enabled,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID string `json:"account_id,omitempty"`
	// TunnelID holds the value of the "tunnel_id" field.
	TunnelID string `json:"tunnel_id,omitempty"`
	// AutoStart holds the value of the "auto_start" field.
	AutoStart bool `json:"auto_start,omitempty"`
	// AutoRestart holds the value of the "auto_restart" field.
	AutoRestart bool `json:"auto_restart,omitempty"`
	// CustomTag holds the value of the "custom_tag" field.
	CustomTag string `json:"custom_tag,omitempty"`
	// SoftwareName holds the value of the "software_name" field.
	SoftwareName string `json:"software_name,omitempty"`
	// Protocol holds the value of the "protocol" field.
	Protocol string `json:"protocol,omitempty"`
	// GracePeriod holds the value of the "grace_period" field.
	GracePeriod string `json:"grace_period,omitempty"`
	// Region holds the value of the "region" field.
	Region string `json:"region,omitempty"`
	// Retries holds the value of the "retries" field.
	Retries int `json:"retries,omitempty"`
	// MetricsEnable holds the value of the "metrics_enable" field.
	MetricsEnable bool `json:"metrics_enable,omitempty"`
	// MetricsPort holds the value of the "metrics_port" field.
	MetricsPort int `json:"metrics_port,omitempty"`
	// LogLevel holds the value of the "log_level" field.
	LogLevel string `json:"log_level,omitempty"`
	// LogFile holds the value of the "log_file" field.
	LogFile string `json:"log_file,omitempty"`
	// LogJSON holds the value of the "log_json" field.
	LogJSON bool `json:"log_json,omitempty"`
	// EdgeIPVersion holds the value of the "edge_ip_version" field.
	EdgeIPVersion string `json:"edge_ip_version,omitempty"`
	// EdgeBindAddress holds the value of the "edge_bind_address" field.
	EdgeBindAddress string `json:"edge_bind_address,omitempty"`
	// Edge holds the value of the "edge" field.
	Edge string `json:"edge,omitempty"`
	// PostQuantum holds the value of the "post_quantum" field.
	PostQuantum bool `json:"post_quantum,omitempty"`
	// NoTLSVerify holds the value of the "no_tls_verify" field.
	NoTLSVerify bool `json:"no_tls_verify,omitempty"`
	// ExtraArgs holds the value of the "extra_args" field.
	ExtraArgs string `json:"extra_args,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TunnelProfile) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tunnelprofile.FieldLocalEnabled, tunnelprofile.FieldRemoteManagementEnabled, tunnelprofile.FieldAutoStart, tunnelprofile.FieldAutoRestart, tunnelprofile.FieldMetricsEnable, tunnelprofile.FieldLogJSON, tunnelprofile.FieldPostQuantum, tunnelprofile.FieldNoTLSVerify:
			values[i] = new(sql.NullBool)
		case tunnelprofile.FieldID, tunnelprofile.FieldSortOrder, tunnelprofile.FieldRetries, tunnelprofile.FieldMetricsPort:
			values[i] = new(sql.NullInt64)
		case tunnelprofile.FieldKey, tunnelprofile.FieldName, tunnelprofile.FieldToken, tunnelprofile.FieldAccountID, tunnelprofile.FieldTunnelID, tunnelprofile.FieldCustomTag, tunnelprofile.FieldSoftwareName, tunnelprofile.FieldProtocol, tunnelprofile.FieldGracePeriod, tunnelprofile.FieldRegion, tunnelprofile.FieldLogLevel, tunnelprofile.FieldLogFile, tunnelprofile.FieldEdgeIPVersion, tunnelprofile.FieldEdgeBindAddress, tunnelprofile.FieldEdge, tunnelprofile.FieldExtraArgs:
			values[i] = new(sql.NullString)
		case tunnelprofile.FieldCreatedAt, tunnelprofile.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TunnelProfile fields.
func (_m *TunnelProfile) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tunnelprofile.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case tunnelprofile.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				_m.Key = value.String
			}
		case tunnelprofile.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case tunnelprofile.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		case tunnelprofile.FieldToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token", values[i])
			} else if value.Valid {
				_m.Token = value.String
			}
		case tunnelprofile.FieldLocalEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field local_enabled", values[i])
			} else if value.Valid {
				_m.LocalEnabled = value.Bool
			}
		case tunnelprofile.FieldRemoteManagementEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field remote_management_enabled", values[i])
			} else if value.Valid {
				_m.RemoteManagementEnabled = value.Bool
			}
		case tunnelprofile.FieldAccountID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.String
			}
		case tunnelprofile.FieldTunnelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tunnel_id", values[i])
			} else if value.Valid {
				_m.TunnelID = value.String
			}
		case tunnelprofile.FieldAutoStart:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field auto_start", values[i])
			} else if value.Valid {
				_m.AutoStart = value.Bool
			}
		case tunnelprofile.FieldAutoRestart:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field auto_restart", values[i])
			} else if value.Valid {
				_m.AutoRestart = value.Bool
			}
		case tunnelprofile.FieldCustomTag:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field custom_tag", values[i])
			} else if value.Valid {
				_m.CustomTag = value.String
			}
		case tunnelprofile.FieldSoftwareName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field software_name", values[i])
			} else if value.Valid {
				_m.SoftwareName = value.String
			}
		case tunnelprofile.FieldProtocol:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field protocol", values[i])
			} else if value.Valid {
				_m.Protocol = value.String
			}
		case tunnelprofile.FieldGracePeriod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field grace_period", values[i])
			} else if value.Valid {
				_m.GracePeriod = value.String
			}
		case tunnelprofile.FieldRegion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field region", values[i])
			} else if value.Valid {
				_m.Region = value.String
			}
		case tunnelprofile.FieldRetries:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field retries", values[i])
			} else if value.Valid {
				_m.Retries = int(value.Int64)
			}
		case tunnelprofile.FieldMetricsEnable:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field metrics_enable", values[i])
			} else if value.Valid {
				_m.MetricsEnable = value.Bool
			}
		case tunnelprofile.FieldMetricsPort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field metrics_port", values[i])
			} else if value.Valid {
				_m.MetricsPort = int(value.Int64)
			}
		case tunnelprofile.FieldLogLevel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field log_level", values[i])
			} else if value.Valid {
				_m.LogLevel = value.String
			}
		case tunnelprofile.FieldLogFile:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field log_file", values[i])
			} else if value.Valid {
				_m.LogFile = value.String
			}
		case tunnelprofile.FieldLogJSON:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field log_json", values[i])
			} else if value.Valid {
				_m.LogJSON = value.Bool
			}
		case tunnelprofile.FieldEdgeIPVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field edge_ip_version", values[i])
			} else if value.Valid {
				_m.EdgeIPVersion = value.String
			}
		case tunnelprofile.FieldEdgeBindAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field edge_bind_address", values[i])
			} else if value.Valid {
				_m.EdgeBindAddress = value.String
			}
		case tunnelprofile.FieldEdge:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field edge", values[i])
			} else if value.Valid {
				_m.Edge = value.String
			}
		case tunnelprofile.FieldPostQuantum:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field post_quantum", values[i])
			} else if value.Valid {
				_m.PostQuantum = value.Bool
			}
		case tunnelprofile.FieldNoTLSVerify:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field no_tls_verify", values[i])
			} else if value.Valid {
				_m.NoTLSVerify = value.Bool
			}
		case tunnelprofile.FieldExtraArgs:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field extra_args", values[i])
			} else if value.Valid {
				_m.ExtraArgs = value.String
			}
		case tunnelprofile.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case tunnelprofile.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TunnelProfile.
// This includes values selected through modifiers, order, etc.
func (_m *TunnelProfile) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this TunnelProfile.
// Note that you need to call TunnelProfile.Unwrap() before calling this method if this TunnelProfile
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TunnelProfile) Update() *TunnelProfileUpdateOne {
	return NewTunnelProfileClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TunnelProfile entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TunnelProfile) Unwrap() *TunnelProfile {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TunnelProfile is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TunnelProfile) String() string {
	var builder strings.Builder
	builder.WriteString("TunnelProfile(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("key=")
	builder.WriteString(_m.Key)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteString(", ")
	builder.WriteString("token=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("local_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.LocalEnabled))
	builder.WriteString(", ")
	builder.WriteString("remote_management_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.RemoteManagementEnabled))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(_m.AccountID)
	builder.WriteString(", ")
	builder.WriteString("tunnel_id=")
	builder.WriteString(_m.TunnelID)
	builder.WriteString(", ")
	builder.WriteString("auto_start=")
	builder.WriteString(fmt.Sprintf("%v", _m.AutoStart))
	builder.WriteString(", ")
	builder.WriteString("auto_restart=")
	builder.WriteString(fmt.Sprintf("%v", _m.AutoRestart))
	builder.WriteString(", ")
	builder.WriteString("custom_tag=")
	builder.WriteString(_m.CustomTag)
	builder.WriteString(", ")
	builder.WriteString("software_name=")
	builder.WriteString(_m.SoftwareName)
	builder.WriteString(", ")
	builder.WriteString("protocol=")
	builder.WriteString(_m.Protocol)
	builder.WriteString(", ")
	builder.WriteString("grace_period=")
	builder.WriteString(_m.GracePeriod)
	builder.WriteString(", ")
	builder.WriteString("region=")
	builder.WriteString(_m.Region)
	builder.WriteString(", ")
	builder.WriteString("retries=")
	builder.WriteString(fmt.Sprintf("%v", _m.Retries))
	builder.WriteString(", ")
	builder.WriteString("metrics_enable=")
	builder.WriteString(fmt.Sprintf("%v", _m.MetricsEnable))
	builder.WriteString(", ")
	builder.WriteString("metrics_port=")
	builder.WriteString(fmt.Sprintf("%v", _m.MetricsPort))
	builder.WriteString(", ")
	builder.WriteString("log_level=")
	builder.WriteString(_m.LogLevel)
	builder.WriteString(", ")
	builder.WriteString("log_file=")
	builder.WriteString(_m.LogFile)
	builder.WriteString(", ")
	builder.WriteString("log_json=")
	builder.WriteString(fmt.Sprintf("%v", _m.LogJSON))
	builder.WriteString(", ")
	builder.WriteString("edge_ip_version=")
	builder.WriteString(_m.EdgeIPVersion)
	builder.WriteString(", ")
	builder.WriteString("edge_bind_address=")
	builder.WriteString(_m.EdgeBindAddress)
	builder.WriteString(", ")
	builder.WriteString("edge=")
	builder.WriteString(_m.Edge)
	builder.WriteString(", ")
	builder.WriteString("post_quantum=")
	builder.WriteString(fmt.Sprintf("%v", _m.PostQuantum))
	builder.WriteString(", ")
	builder.WriteString("no_tls_verify=")
	builder.WriteString(fmt.Sprintf("%v", _m.NoTLSVerify))
	builder.WriteString(", ")
	builder.WriteString("extra_args=")
	builder.WriteString(_m.ExtraArgs)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TunnelProfiles is a parsable slice of TunnelProfile.
type TunnelProfiles []*TunnelProfile
